### ISSUE TITLE
[Discworld 2 (E)] GFX messed + Master SH2 invalid opcode...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [devmiyax/yabause#102]
Left picture : Yabause Devmiyax 05.05.2016 (Software)
Right picture : Yabause Devmiyax05.05.2016 (OpenGl)

![discworld2](https://cloud.githubusercontent.com/assets/12481242/11761751/4c15caf4-a0cf-11e5-8cfd-0916c4e23cf6.PNG)

**Comment by BenjaminSiskoo** [comment]
With a real bios, you have the picture (1st post).
With the built in bios, there is an error message :+1: 

Master SH2 invalid opcode

R0 =  00000000	R12 =  00000000
R1 =  0602F3EC	R13 =  00000000
R2 =  00000000	R14 =  00000000
R3 =  000002DC	R15 =  0605CB04
R4 =  00000003	SR =   00000001
R5 =  060002DC	GBR =  00000000
R6 =  00000000	VBR =  06000000
R7 =  00000000	MACH = 00000000
R8 =  00000000	MACL = 00000000
R9 =  00000000	PR =   0604ADEC
R10 = 00000000	PC =   00000000
R11 = 00000000

**Comment by BenjaminSiskoo** [comment]
UoYabause 0.3.0 06.12.2016  - same problem

**Comment by BenjaminSiskoo** [comment]
UoYabause 0.3.8 - same problem

**Comment by BenjaminSiskoo** [comment]
UoYabause 0.4.1 : same problem.

**Comment by FCare** [comment]
This patch is fixing Discworld 2 tearing effect.
FCare/piYabause@8143054

Shall fix #102 in case of real bios usage.

**Comment by BenjaminSiskoo** [comment]
UoYabause 0.4.6 : fixed
