### ISSUE TITLE
[Magical Drop 3 (J)] Transparencies problems...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [devmiyax/yabause#104]
Left picture : Yabause Devmiyax 12.12.2015 (OpenGL)
Right picture : SSF 0.12 Beta R2

![magicaldrop3](https://cloud.githubusercontent.com/assets/12481242/11761777/1a677f24-a0d0-11e5-97fc-41abbcc5f3a0.JPG)

**Comment by devmiyax** [comment]
it needs to implement 'color calculation window'

**Comment by devmiyax** [comment]
Color Calculation window is implemented.

![cc_win0_in](https://cloud.githubusercontent.com/assets/1174152/14408425/92b7fc84-ff2f-11e5-894d-eff4923824e5.png)
![cc_win0_out](https://cloud.githubusercontent.com/assets/1174152/14408427/9bb880b0-ff2f-11e5-95b5-fd8149f3db5a.png)
![cc_and_win0_in_win1_in](https://cloud.githubusercontent.com/assets/1174
![cc_or_win0_in_win1_in](https://cloud.githubusercontent.com/assets/1174152/14408432/a99f230a-ff2f-11e5-9c53-24e4f4aedbaa.png)
![cc_or_win0_out_win1_out](https://cloud.githubusercontent.com/assets/1174152/14408434/ac073d12-ff2f-11e5-9b0e-0a6881efe244.png)

152/14408429/a2311056-ff2f-11e5-9e55-e1ce275dda66.png)
![cc_and_win0_out_win1_out](https://cloud.githubusercontent.com/assets/1174152/14408431/a6277448-ff2f-11e5-8151-0af80eee2359.png)

**Comment by devmiyax** [comment]
And the game graphics is also fixed.

![image](https://cloud.githubusercontent.com/assets/1174152/14408439/e87e206c-ff2f-11e5-88d9-298ac13f91d98.png)
![image](https://cloud.githubusercontent.com/assets/1174152/14408441/ede4cb46-ff2f-11e5-9a48-57c62cab0cda.png)

**Comment by BenjaminSiskoo** [comment]
Perfect
