### ISSUE TITLE
[Mortal Kombat 2 (U)] Freeze after pushing start...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [devmiyax/yabause#105]
Yabause Devmiyax 12.12.2015

On the screen menu, after pushing start, the game freeze.

**Comment by BenjaminSiskoo** [comment]
UoYabause 0.3.0 06.12.2016 - same problem

**Comment by devmiyax** [comment]
Infinity loop


0x0603F3D6: tst ((r0)0x060A2B1C), ((r0)0x060A2B1C)
0x0603F3D8: bt 0x0603F408
0x0603F3DA: mov.l @(0x000, ((r0)0x060A2B1C)), ((r1)0x00000115)
0x0603F3DC: mov.l ((r1)0x060A3424), @-((r15)0x060A33D8)
0x0603F3DE: cmp/eq ((r0)0x060A2B1C), ((r4)0x060A2FA0)
0x0603F3E0: bt 0x0603F404
0x0603F3E2: mov.l @(0x008, ((r0)0x060A2B1C)), ((r1)0x060A3424)
0x0603F3E4: and ((r6)0xFFFFFFFF), ((r1)0x00000101)
0x0603F3E6: cmp/eq ((r1)0x00000101), ((r5)0x00000114)
0x0603F3E8: bf 0x0603F404
0x0603F404: bra 0x0603F3D6

**Comment by BenjaminSiskoo** [comment]
UoYabause 0.4.1 : same problem

**Comment by devmiyax** [comment]
![image](https://cloud.githubusercontent.com/assets/1174152/25561017/752bc1da-2d9d-11e7-9f89-2d2f616652ee.png)
![image](https://cloud.githubusercontent.com/assets/1174152/25561020/863f26c4-2d9d-11e7-86b3-dd209de3f177.png)
