### ISSUE TITLE
[Samurai Spirits IV (J)] Vertical thin line on the character...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [devmiyax/yabause#107]
Left picture : Yabause Devmiyax 12.12.2015 (Software)
Right picture : Yabause Devmiyax 12.12.2015 (OpenGl)

![ssh4](https://cloud.githubusercontent.com/assets/12481242/11761930/50577306-a0d4-11e5-8cbb-3654faa76fa0.PNG)

![ssh4_ingame](https://cloud.githubusercontent.com/assets/12481242/11761934/55ef73f4-a0d4-11e5-8d9b-37d6769c623e.PNG)

**Comment by devmiyax** [comment]
![image](https://cloud.githubusercontent.com/assets/1174152/12004518/06bbde7a-aba2-11e5-8da0-545e5e8ad11d.png)
![image](https://cloud.githubusercontent.com/assets/1174152/12004519/0f0379bc-aba2-11e5-93d9-c637610aec55.png)

VIDOGLVdp1ScaledSpriteDraw

**Comment by BenjaminSiskoo** [comment]
Great :)
