### ISSUE TITLE
Sonic Jam does not scroll

### ISSUE THREAD

**Issue by devmiyax** [devmiyax/yabause#11]
[![](http://img.youtube.com/vi/BqYqTkYiY4o/0.jpg)](https://www.youtube.com/watch?v=BqYqTkYiY4o)

https://www.youtube.com/watch?v=BqYqTkYiY4o

**Comment by devmiyax** [comment]
4-bit(16 colors)
Tile(1H x 1V)
Plane Size = 1H x 1V
Pattern Name data size = 2 words
Plane A Address = 00018000
Plane B Address = 00018000
Plane C Address = 00018000
Plane D Address = 00018000
Screen Scroll x = 0, y = 0
Coordinate Increments x = 1.000000, y = 1.000000
Line Scroll Horizontal enabled
Line Scroll Enabled
Line Scroll Table Address = 05E30380
Line Scroll Interval = Each Line
Vertical Cell Scroll enabled
Vertical Cell Scroll Table Address = 05E30700
Window disabled whole screen
Color Ram Address Offset = 0
Special Priority Mode 1 used(per tile)
Priority = 2
Color Offset A Enabled
R = 0, G = 0, B = 0
Special Color Calculation 0

**Comment by devmiyax** [comment]
Line Scroll is not implemented.

> Line Scroll Enabled
> Line Scroll Table Address = 05E30380

**Comment by devmiyax** [comment]
http://youtu.be/qJcRI2fhZdU

**Comment by Rufusruffcut08** [comment]
I think there has been a mix up as this is not my issue that was posted.  My issue was regarding Yabause working on Kit Kat.
