### ISSUE TITLE
[Virtua Fighter Kid (J)] Freeze after the now loading screen (Slave SH2 invalid opcode)..

### ISSUE THREAD

**Issue by BenjaminSiskoo** [devmiyax/yabause#112]
Yabause Devmiayx 12.12.2015

Info : error messsage and the game freeze on the "now loading" screen.

Slave SH2 invalid opcode

R0 = 260FA16C R12 = 060E4AAC
R1 = 260FA16C R13 = 00000000
R2 = 260FFC48 R14 = 00000000
R3 = 0000001E R15 = 06001000
R4 = 260FA16C SR = 000003F1
R5 = 060F9C34 GBR = 060FFC00
R6 = 0000001F VBR = 06000400
R7 = 0000001F MACH = 00000000
R8 = 00000000 MACL = 00002D88
R9 = 00000000 PR = 060D02C0
R10 = 060E46A8 PC = 060D02A6
R11 = 060E2018

**Comment by BenjaminSiskoo** [comment]
Yabause Devmiyax 05.12.2016 (OpenGL)

Same problem

**Comment by BenjaminSiskoo** [comment]
UoYabause 0.3.0 06.12.2016 - same problem

**Comment by BenjaminSiskoo** [comment]
UoYabause 0.3.8 - same problem

**Comment by BenjaminSiskoo** [comment]
UoYabause 0.4.1 : same problem

**Comment by BenjaminSiskoo** [comment]
UoYabause 0.4.6 : same problem

Slave SH2 invalid opcode

R0 =  260FA16C	R12 =  060E4AAC
R1 =  260FA16C	R13 =  00000000
R2 =  260FFC48	R14 =  00000000
R3 =  0000001E	R15 =  06001000
R4 =  260FA16C	SR =   000003F1
R5 =  060F9C34	GBR =  060FFC00
R6 =  0000001F	VBR =  06000400
R7 =  0000001F	MACH = 00000000
R8 =  00000000	MACL = 00002D88
R9 =  00000000	PR =   060D02C0
R10 = 060E46A8	PC =   060D02A8
R11 = 060E201

**Comment by BenjaminSiskoo** [comment]
UoYabause 0.5.2 : same problem

**Comment by BenjaminSiskoo** [comment]
Same problem with UoYabause 0.5.5

**Comment by BenjaminSiskoo** [comment]
Same problem with Yaba Sanshiro 1.3.0 RC

Slave SH2 invalid opcode

R0 =  260FA16C	R12 =  060E4AAC
R1 =  260FA16C	R13 =  00000000
R2 =  260FFC48	R14 =  00000000
R3 =  0000001E	R15 =  06001000
R4 =  260FA16C	SR =   000003F1
R5 =  060F9C34	GBR =  060FFC00
R6 =  0000001F	VBR =  06000400
R7 =  0000001F	MACH = 00000000
R8 =  00000000	MACL = 00002D88
R9 =  00000000	PR =   060D02C0
R10 = 060E46A8	PC =   060D02A6
R11 = 060E2018

**Comment by devmiyax** [comment]
Fixed!

![Uploading image.png…]()

**Comment by devmiyax** [comment]
![image](https://user-images.githubusercontent.com/1174152/44947073-67f53d80-ae42-11e8-8c35-08431c3808b7.png)

**Comment by BenjaminSiskoo** [comment]
:o Are you kidding ? and it's seems totally playable in game. I'm really really really happy.  Many thanks. Arigato gozaimasu, Devmiyax San...

**Comment by BenjaminSiskoo** [comment]
Fixed with Yaba Sanshiro 2.2.0.
