### ISSUE TITLE
CHAOS SEED                                                                                                      

### ISSUE THREAD

**Issue by devmiyax** [devmiyax/yabause#114]
version:0.1.18a
device:LG-F240K
cpu_type:0
video_type:2
The game can be run with graphic problems, including flashing screen with openGL on, and ghost with software mode on.
The game constantly freeze at this screen but the background music is still playing.
I love this game, please help to make it work.
![screenshot](http://www.uoyabause.org//system/reports/screenshots/000/000/257/original/_storage_emulated_0_yabause_screenshots_T-30902G_2015_12_18_08_58_56.png?1450400457)

**Comment by devmiyax** [comment]
freeze is caused by cache coherency.
Master CPU writes 0 at 0x0601eeaa. then Slave CPU reads that address as instruction. then invalid opecode exception is occurred.

**Comment by devmiyax** [comment]
Black Screen & Character problem is caused by VDP2's per line color  offset function. CPU changes VDP2 color offset value each HBLANK . BGs and Sprites need to reflect the value per line.

**Comment by devmiyax** [comment]
![image](https://cloud.githubusercontent.com/assets/1174152/14617411/1580d694-05e9-11e6-8adf-6c614279d5f1.png)

**Comment by devmiyax** [comment]
![image](https://cloud.githubusercontent.com/assets/1174152/14617460/455e4f36-05e9-11e6-95f0-bff9d1789444.png)

**Comment by devmiyax** [comment]
0x0601fe84   mov.b @r5+,r6  r6 = 0x076
0x0601fe98   mov.b @r5+,r0  r0 = 0x0B  ?????

0x0601FEA2

**Comment by devmiyax** [comment]
force r6 0x06zzzzzzzz

![image](https://cloud.githubusercontent.com/assets/1174152/14940955/1365179e-0fc6-11e6-9d12-4043964ca07c.png)

**Comment by BenjaminSiskoo** [comment]
I like any progress :) Congrats

**Comment by devmiyax** [comment]
main (C:\ext\GitHub\YabauseLocal\yabause\src\cs2.c:1136): cs2	: Command: getSectorData 0f54 6100 0000 0300 0001

main (C:\ext\GitHub\YabauseLocal\yabause\src\cs2.c:1138): cs2	: ret: 0fd7 0100 4101 0100 e8f2

main (C:\ext\GitHub\YabauseLocal\yabause\src\sh2core.c:1973): sh2 dma src=25818000,dst=060046F0,512

main (C:\ext\GitHub\YabauseLocal\yabause\src\sh2core.c:1973): sh2 dma src=06004788,dst=06001EF0,2

main (C:\ext\GitHub\YabauseLocal\yabause\src\cs2.c:1051): cs2	: Command: endDataTransfer 0fd4 0600 0000 0000 0000

main (C:\ext\GitHub\YabauseLocal\yabause\src\cs2.c:1053): cs2	: ret: 0fd5 0100 0400 0000 0000

main (C:\ext\GitHub\YabauseLocal\yabause\src\cs2.c:1028): cs2	: Command: getStatus

main (C:\ext\GitHub\YabauseLocal\yabause\src\cs2.c:1030): cs2	: ret: 0fd5 0100 4101 0100 e8f2

main (C:\ext\GitHub\YabauseLocal\yabause\src\cs2.c:1136): cs2	: Command: getSectorData 0f54 6100 000d 0300 0001

main (C:\ext\GitHub\YabauseLocal\yabause\src\cs2.c:1138): cs2	: ret: 0fd7 0100 4101 0100 e8f2

main (C:\ext\GitHub\YabauseLocal\yabause\src\sh2core.c:1973): sh2 dma src=25818000,dst=060046F0,512

main (C:\ext\GitHub\YabauseLocal\yabause\src\sh2core.c:1973): sh2 dma src=0600485B,dst=06001EF8,4

main (C:\ext\GitHub\YabauseLocal\yabause\src\cs2.c:1051): cs2	: Command: endDataTransfer 0fd4 0600 0000 0000 0000

main (C:\ext\GitHub\YabauseLocal\yabause\src\cs2.c:1053): cs2	: ret: 0fd5 0100 0400 0000 0000

main (C:\ext\GitHub\YabauseLocal\yabause\src\cs2.c:1028): cs2	: Command: getStatus

main (C:\ext\GitHub\YabauseLocal\yabause\src\cs2.c:1030): cs2	: ret: 0fd5 0100 4101 0100 e8f2

main (C:\ext\GitHub\YabauseLocal\yabause\src\sh2core.c:1973): sh2 dma src=0600485B,dst=060E1EC8,1685 !!!!!!!!!!!!!

main (C:\ext\GitHub\YabauseLocal\yabause\src\cs2.c:1136): cs2	: Command: getSectorData 0f54 6100 000e 0300 0001

main (C:\ext\GitHub\YabauseLocal\yabause\src\cs2.c:1138): cs2	: ret: 0fd7 0100 4101 0100 e8f2

main (C:\ext\GitHub\YabauseLocal\yabause\src\sh2core.c:1973): sh2 dma src=25818000,dst=060046F0,512

main (C:\ext\GitHub\YabauseLocal\yabause\src\sh2core.c:1973): sh2 dma src=060046F0,dst=060E255D,1471

main (C:\ext\GitHub\YabauseLocal\yabause\src\cs2.c:1051): cs2	: Command: endDataTransfer 0fd4 0600 0000 0000 0000

main (C:\ext\GitHub\YabauseLocal\yabause\src\cs2.c:1053): cs2	: ret: 0fd5 0100 0400 0000 0000

**Comment by devmiyax** [comment]
Yes!

![image](https://cloud.githubusercontent.com/assets/1174152/14947589/d213c032-1070-11e6-893c-7ad7ff5f7872.png)
