### ISSUE TITLE
RAYMAN                                                                                                          

### ISSUE THREAD

**Issue by devmiyax** [devmiyax/yabause#115]
version:0.1.18a
device:SHIELD Android TV
cpu_type:0
video_type:1

![screenshot](http://www.uoyabause.org//system/reports/screenshots/000/000/263/original/_storage_emulated_0_yabause_screenshots_T-17701H_2015_12_19_18_02_37.png?1450577079)

**Comment by BenjaminSiskoo** [comment]
Yabause Devmiyax 05.12.2016

Same problem with windows version

**Comment by BenjaminSiskoo** [comment]
UoYabause 0.3.8 - Same problem

**Comment by BenjaminSiskoo** [comment]
UoYabause 0.5.2 commit 4105 : same problem

**Comment by fivefeet8** [comment]
Seems to be fixed in 2.2.x versions.
