### ISSUE TITLE
MK TRILOGY                                                                                                      

### ISSUE THREAD

**Issue by devmiyax** [devmiyax/yabause#116]
version:0.1.18a
device:SHIELD Android TV
cpu_type:0
video_type:1

![screenshot](http://www.uoyabause.org//system/reports/screenshots/000/000/262/original/_storage_emulated_0_yabause_screenshots_T-25414H50VV1.000_2015_12_19_18_00_10.png?1450576935)

**Comment by khaleeluae** [comment]
Nice

**Comment by devmiyax** [comment]
screenshot is lost. but this game works fine on 2.7.5
