### ISSUE TITLE
MARVEL SUPER HEROES VS. STREET FIGHTER                                                                          

### ISSUE THREAD

**Issue by devmiyax** [devmiyax/yabause#118]
version:0.1.18a
device:SHIELD Android TV
cpu_type:0
video_type:1

![screenshot](http://www.uoyabause.org//system/reports/screenshots/000/000/249/original/_storage_emulated_0_yabause_screenshots_T-1238G_2015_12_14_18_43_13.png?1450147503)

**Comment by devmiyax** [comment]
![image](https://cloud.githubusercontent.com/assets/1174152/12004462/3300096a-ab9e-11e5-8122-529181618561.png)

fixed

**Comment by fivefeet8** [comment]
Awesome.  Is a test build coming?

**Comment by fivefeet8** [comment]
The graphics are fixed, but when you start a game, it's performance is somehow hindered.  When you load the game and watch the demo matches, they run full speed with full animations.
