### ISSUE TITLE
[3D Lemmings] No boot (Master SH2 invalid opcode)

### ISSUE THREAD

**Issue by BenjaminSiskoo** [devmiyax/yabause#122]
Yabause Devmiyax 12.21.2015

The game don't boot. Black screen.

Built in bios : there is an error message 

Master SH2 invalid opcode

R0 =  00000000  R12 =  00000000
R1 =  00000022  R13 =  00000000
R2 =  002ED289  R14 =  060FFED4
R3 =  00000000  R15 =  060FFED0
R4 =  00000003  SR =   00000001
R5 =  00000022  GBR =  00000000
R6 =  002ED268  VBR =  06000000
R7 =  00000022  MACH = 00000000
R8 =  00000000  MACL = 00000000
R9 =  06011EC0  PR =   0604A0D0
R10 = 00000000  PC =   00000000
R11 = 00000022

Real bios : no error message.

**Comment by devmiyax** [comment]
Master SH2 try to get jump address from 0x060002dc.
0x060002dc is a adress of system reserved region( from 0x06000000 to 0x06001FFF), Therefore BIOS is needed.

**Comment by BenjaminSiskoo** [comment]
Yabause Devmiyax 05.15.2016 (OpenGL)

No boot

**Comment by BenjaminSiskoo** [comment]
UoYabause 0.4.1 : same problem

**Comment by devmiyax** [comment]
![image](https://cloud.githubusercontent.com/assets/1174152/25561216/b2d41bb4-2da1-11e7-9f8f-9554a322f04c.png)
