### ISSUE TITLE
[Capcom Generation 4] horizontal display is not correct...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [devmiyax/yabause#128]
Left video : Yabause Devmiyax 12.25.2015 (Software)
Right video : Yabause Devmiyax 12.25.2015 (OpenGL)

Here a video : 

https://youtu.be/UTRD1heGsjo

**Comment by devmiyax** [comment]
VDP1: TV mode select

**Comment by devmiyax** [comment]
06_33

**Comment by devmiyax** [comment]
![image](https://cloud.githubusercontent.com/assets/1174152/14641723/9fe7ee50-0682-11e6-9ebe-d24e169034f8.png)

**Comment by BenjaminSiskoo** [comment]
Perfect now :)
