### ISSUE TITLE
Shield TV Support

### ISSUE THREAD

**Issue by fivefeet8** [devmiyax/yabause#13]
Does the emulator work on the new Shield TV console?  I'm getting it soon and would like to test the emulator on it.  Also, is there a step by step instruction page to compile binaries for this Android version of Yabause with Windows?

**Comment by devmiyax** [comment]
>is there a step by step instruction page to compile binaries for this Android version of Yabause with Windows?

check it out
https://github.com/devmiyax/yabause/blob/extui/yabause/src/android/CMakeLists.txt
