### ISSUE TITLE
[Metal Slug] Screen messed in game...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [devmiyax/yabause#130]
Yabause Devmiyax 12.25.2015

Here a video of the problem : 

https://youtu.be/D9fPrZcINQ8

**Comment by BenjaminSiskoo** [comment]
Yes, finally, this bug is over \o/

**Comment by paul-met** [comment]
Unfortunately, the problem is still relevant in the version 0.9.15.
![metal_slug](https://cloud.githubusercontent.com/assets/13948032/16896666/5b9701b8-4ba2-11e6-9697-25a97580605a.png)

**Comment by BenjaminSiskoo** [comment]
Software or OpenGL ? It works with the OpenGL, not the software one.

**Comment by paul-met** [comment]
In both cases.

**Comment by BenjaminSiskoo** [comment]
UoYabause or Yabause ? It works with UoYabause 0.3.0.

[http://tradu-france.com/download.php?emul=136]UoYabause 0.3.0

**Comment by paul-met** [comment]
I know that UoYabause does. But why in the regular version of Yabause is still not fixed it? After all, the branch has a fix.

**Comment by BenjaminSiskoo** [comment]
The official fork is not merged with the Devmiyax fork.

**Comment by paul-met** [comment]
Too bad.
