### ISSUE TITLE
[Jissen Pachinko Hisshouhou ! Twin (J)] GFX problems...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [devmiyax/yabause#136]
Left picture : Yabause Devmiyax 12.25.2015 (Software)
Right picture : Yabause Devmiyax 12.25.2015 (OpenGL)

![pachinko_enter](https://cloud.githubusercontent.com/assets/12481242/12017960/443711ea-ad5d-11e5-83dd-5175e2009d04.PNG)
![pachinko_enter_name](https://cloud.githubusercontent.com/assets/12481242/12017961/443812c0-ad5d-11e5-9372-3185cbaf25a8.PNG)

**Comment by devmiyax** [comment]
![image](https://cloud.githubusercontent.com/assets/1174152/12048761/93a2476a-af22-11e5-8a30-8a24410e7ecf.png)

![image](https://cloud.githubusercontent.com/assets/1174152/12048766/a203a9ca-af22-11e5-8956-6ab2307746d8.png)

Colors are shown, but priority issue it there.

**Comment by devmiyax** [comment]
![image](https://cloud.githubusercontent.com/assets/1174152/12057719/2d360808-af87-11e5-96b7-7dddd48915a5.png)

![image](https://cloud.githubusercontent.com/assets/1174152/12057722/37e9233e-af87-11e5-851e-8032dac47c2c.png)


it seems correct.

**Comment by BenjaminSiskoo** [comment]
Fixed :) thanks
