### ISSUE TITLE
[Dungeons & Dragons - Shadow Over Mystara] Character messed...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [devmiyax/yabause#137]
Yabause Devmiyax 12.29.2015 (OpenGL and Software).

When you move  the character, he's scrambled. Check the video.

https://youtu.be/OB7Jm6Ltg_I

**Comment by fivefeet8** [comment]
Strange, I don't get that issue at that scene on my Shield TV.

**Comment by BenjaminSiskoo** [comment]
I always know this bug with the window release. Thanks to your video :)

**Comment by fivefeet8** [comment]
It still flickers in a few instances, but not as much as your video is showing.  Would be nice to fix it completely though.

**Comment by BenjaminSiskoo** [comment]
UoYabause 0.3.0 06.12.2016  - same problem

**Comment by BenjaminSiskoo** [comment]
UoYabause 0.4.6 : same problem

**Comment by BenjaminSiskoo** [comment]
UoYabause 0.5.2 : same problem

**Comment by BenjaminSiskoo** [comment]
UoYabause 0.5.2 commit 4106:  same problem

**Comment by BenjaminSiskoo** [comment]
Same problem with UoYabause 0.5.5

**Comment by BenjaminSiskoo** [comment]
Same problem with Yaba Sanshiro 1.3.0 RC

**Comment by BenjaminSiskoo** [comment]
Same problem with Yaba Sanshiro 2.2.0.

**Comment by BenjaminSiskoo** [comment]
Same problem with Yaba 3.2 b2

**Comment by BenjaminSiskoo** [comment]
Fixed, remaining glitches  when you jump

**Comment by Gamemulatorer** [comment]
I cannot reproduce this issue on my Redmi Note 9 Mali-G52 GPU Helio G85 Processor.
![Screenshot_2021-09-13-08-17-24-146_org devmiyax yabasanshioro2](https://user-images.githubusercontent.com/37603562/133007688-a62ec12c-cf76-4830-96d1-4f3376a01f40.jpg)
But the problem is the touchscreen buttons turn dark when my phone us set to dark mode :/

**Comment by devmiyax** [comment]
no problem in 1.8.0

![image](https://user-images.githubusercontent.com/1174152/162559694-88cff9f3-c7a7-4d29-af0f-92ae5f67986c.png)
