### ISSUE TITLE
Yabause on Kit Kat.

### ISSUE THREAD

**Issue by Rufusruffcut08** [devmiyax/yabause#14]
First of all, just a quick word to say what fantastic progress you have made from the youtube vids I have seen - the emu is really gathering exciting pace.
Now my issue:- I am running a note 4 on Kit Kat and as you are no doubt aware I cannot use latest Yabause builds, to my utter disappointment.  Please can you tell me if and when you intend to make latest builds Kit Kat compatible as I am dying to try it.  It seems unfair you would limit Yabause to just Lollipop as Kit Kat uses opengl es3 too.  I am not the only one asking this question so any info you could pass on would be much appreciated.
King regards.

**Comment by Rufusruffcut08** [comment]
Any Info at all on this yet.........?

**Comment by devmiyax** [comment]
I commited @ 7ddb10cf93586f438ce27fba8b04b22fb90880bf
Now you can build for Android 4.4, and get the APK from Google Play.

But I get reports that Yabause crashes on the Kitkat devices which is not support es3 ( like SHEILD portable ),
