### ISSUE TITLE
X-input is not recognize 

### ISSUE THREAD

**Issue by jvhellraiser** [devmiyax/yabause#140]
I have and xbox one controller + usb wireless adapter, the problem is that the emulator wont recognize it
at all it wont recognize the L2 + R2 <- or any of the buttons to say it clear since your version don't have 
and option to select X -input i can't use it. fix this please.

**Comment by devmiyax** [comment]
What version do you use?
Other emulators or games work fine?

**Comment by jvhellraiser** [comment]
Yabause-Devmiyax_29.12.2015 downloaded this morning, Pc games working fine with it, Emulators some do work others wont, example SSF emulator since it don't have X input that is what the Xbox one controller uses when trying to configure the D-Pad it goes bunkers i had never been able to play any games with SSF emulator, But Mame works, PPSSPP works,Original Yabause works but not fully had never been able to configure L1 + R2, ePSXe works too,Dolphin works too,PCSX2 works as well. 
![capture](https://cloud.githubusercontent.com/assets/16488761/12051570/1d697708-aedc-11e5-8434-0e71594e4fd3.PNG) see PCSX2 Dpad configuration,The controller inputs are X input only without X input i cannot configure the D -pad in the emulator.

**Comment by devmiyax** [comment]
Windows version?? Sorry, currently I want to focus on Android version.

**Comment by jvhellraiser** [comment]
why would you release a windows version? if you are not working on it? there only one thing missing from the windows version and is for it to accept X-input that's all. if one day your work on it try to fix this issue. many of us in PC we are already using either a 360 controller or and Xbox one controller or the PS4 controller.

**Comment by fivefeet8** [comment]
This version of Yabause is specifically for Android.  The main Yabause repo should be where you want to ask this.

**Comment by jvhellraiser** [comment]
please guide me to the repo cause i have idea where to located, by the way Happy New Year 2016.

**Comment by fivefeet8** [comment]
https://github.com/Yabause/yabause

**Comment by devmiyax** [comment]
Windows version specified isuue
