### ISSUE TITLE
[Silhouette Mirage (J)] GFX problem on the start screen...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [devmiyax/yabause#148]
Left Picture : Yabause Devmiyax 12.31.2015 (Software)
Right Picture : Yabause Devmiyax 12.31.2015 (OpenGL)

![silhouettemirage_main](https://cloud.githubusercontent.com/assets/12481242/12064558/4a7f8922-afc6-11e5-96fb-805c8e8d2b9b.PNG)

**Comment by devmiyax** [comment]
fixed by a434b96c2848b0c15f8172612d02b74c1f1a0322
