### ISSUE TITLE
DOOM, Ultimate Mortal Kombat and Classic Daytona USA

### ISSUE THREAD

**Issue by Grabisoft** [devmiyax/yabause#153]
DOOM: doesnt even start. every time i load it it gives a black screen and thats it.

ULTIMATE MORTAL KOMBAT: its playable, but a bit slower than usual. there is no background music. SFX work to some point but sfx sounds pop out randomly. for example; you are fighting and suddendly you may hear shao khan shout or some random female ninja scream. 
Anyhow, finding out that UMK works (at some extent) was very surprising, due to the fact that MK trilogy doesnt even reach the main menu. Something completely opposite of what happens with SSF emulator for pc. In SSF, mortal kombat trilogy runs perfect but UMK doesnt even launch. weird.

DAYTONA USA CLASSIC: its very payable, but it has some minor slowdowns as well. no SFX and no backround music. when you finish a race, when the GAMEOVER letters appear, they are all glitched, as they are lacking the right sprites, and instead they seem all painted in green or some other colors.﻿

**Comment by devmiyax** [comment]
dduplicated.
