### ISSUE TITLE
[Virtual Hydlide (U)] Freeze after pushing start...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [devmiyax/yabause#163]
Yabause Devmiyax 01.03.2016

The game freeze just after pushing start on the main screen.

![virtual hydlide](https://cloud.githubusercontent.com/assets/12481242/12087998/e5b4ef04-b2d7-11e5-83f5-e44f16555f99.PNG)

**Comment by BenjaminSiskoo** [comment]
UoYabause 0.4.6 : same problem

**Comment by BenjaminSiskoo** [comment]
UoYabause 0.5.2 : same problem

**Comment by BenjaminSiskoo** [comment]
UoYabause 0.5.2 commit 4106:  same problem

**Comment by BenjaminSiskoo** [comment]
Same problem with Yaba Sanshiro 1.3.0 RC

**Comment by BenjaminSiskoo** [comment]
Yaba Sanshiro 1.7.0 : same problem.

**Comment by devmiyax** [comment]
Implementing time01 lead to the next screen.
 
![image](https://user-images.githubusercontent.com/1174152/44940105-849f6000-adc5-11e8-8bad-a325bee215cf.png)

![image](https://user-images.githubusercontent.com/1174152/44940115-9123b880-adc5-11e8-836c-3101c77e737a.png)

![image](https://user-images.githubusercontent.com/1174152/44940120-98e35d00-adc5-11e8-9f53-fe1bf609f0fe.png)

**Comment by devmiyax** [comment]
![image](https://user-images.githubusercontent.com/1174152/44940133-a567b580-adc5-11e8-9882-fe8bf30262b4.png)

**Comment by devmiyax** [comment]
But hung up on the game screen.

**Comment by BenjaminSiskoo** [comment]
omg so great, this game was working for a moment and now it's almost back. Congrats.

**Comment by BenjaminSiskoo** [comment]
Fixed
