### ISSUE TITLE
(NBG0-NBG1) scaling bug in OGL rendering mode

### ISSUE THREAD

**Issue by paul-met** [devmiyax/yabause#170]
Sometimes I have a problems, If In the OGL rendering mode the NBG0 or NBG1 layers receiving a fractional value of "Coordinate Increments" or more than 1, then this layers is not scaled or scaled not properly. In the software rendering mode scaling is working correctly.

**Comment by devmiyax** [comment]
Could you give me specific examples? screenshot or something.

**Comment by paul-met** [comment]
For example in the game "Story of thor 2" (PAL). Apply the following cheat:
Address: 0x6075004
Value: hD01C
This cheat increases the value of coordinate increments up to 2.000000

**Comment by devmiyax** [comment]
@paul-met Do you have a example without cheat?

**Comment by devmiyax** [comment]
no respond
