### ISSUE TITLE
[Astal] Bios problem

### ISSUE THREAD

**Issue by BenjaminSiskoo** [devmiyax/yabause#176]
Yabause Devmiyax 02.01.2016

built in bios : the game works
real bios : the game freeze on a black screen at the start.

**Comment by BenjaminSiskoo** [comment]
D356 fixed this, but fps drop down

https://github.com/Yabause/yabause/commit/d08d2a787bf2093ed0601eaf12a8f4f27b4c8ddd

**Comment by BenjaminSiskoo** [comment]
UoYabause 0.4.1 : same problem

**Comment by BenjaminSiskoo** [comment]
UoYabause 0.4.6 : same problem

**Comment by BenjaminSiskoo** [comment]
UoYabause 0.5.2 : same problem

**Comment by BenjaminSiskoo** [comment]
UoYabause 0.5.2 commit 4106 :  no boot with the real bios.

**Comment by BenjaminSiskoo** [comment]
Same problem with Yaba Sanshiro 2.2.0.

**Comment by devmiyax** [comment]
confirmed boot when SH2 cache is enabled. but Dracula X doe not boot

**Comment by BenjaminSiskoo** [comment]
Same problem with Yaba 3.2 b2
