### ISSUE TITLE
[Shining Force 3 - Scenario 2] Graphics problem with spell... 

### ISSUE THREAD

**Issue by BenjaminSiskoo** [devmiyax/yabause#180]
Picture SSF 2 : SSF 0.12 Beta R4
Picture Yabause 1 : Yabause DEvmiyax 01.02.2016

![ssf2](https://cloud.githubusercontent.com/assets/12481242/13173692/59904612-d6ff-11e5-9f78-be81d3c666b1.jpg)
![yabause1](https://cloud.githubusercontent.com/assets/12481242/13173695/5e518efe-d6ff-11e5-8d69-5ba2f2ef4a7f.jpg)

**Comment by DarkSki** [comment]
Yup no effects at all , ditto here - sometimes you see some low textured flame but it's very sporadic and badly rendered

**Comment by devmiyax** [comment]
little progress, not enough.
![image](https://cloud.githubusercontent.com/assets/1174152/20648146/1347d21c-b4e2-11e6-831c-38cea2991cb0.png)

**Comment by devmiyax** [comment]
enough?
![image](https://cloud.githubusercontent.com/assets/1174152/20852148/aa9a1dde-b927-11e6-922a-64ba50da53e1.png)

**Comment by devmiyax** [comment]
Gradation is not enough
![image](https://cloud.githubusercontent.com/assets/1174152/20852726/bf6e7612-b92a-11e6-803e-aceb2cf1b136.png)

**Comment by BenjaminSiskoo** [comment]
Nice progress

**Comment by devmiyax** [comment]
it seems perfect.
![image](https://cloud.githubusercontent.com/assets/1174152/20854358/858a61c0-b936-11e6-9f4c-b5068c268c28.png)

**Comment by devmiyax** [comment]
![image](https://cloud.githubusercontent.com/assets/1174152/20854385/c409d160-b936-11e6-97de-c4720eb70732.png)

**Comment by devmiyax** [comment]
regression... :(

![image](https://cloud.githubusercontent.com/assets/1174152/20854467/b32eb5bc-b937-11e6-99a2-ac310110436e.png)

**Comment by devmiyax** [comment]
fixed

![image](https://cloud.githubusercontent.com/assets/1174152/20854566/56d102c4-b938-11e6-99d7-ed249f380118.png)

**Comment by devmiyax** [comment]
@BenjaminSiskoo 

Do you any other game which uses SCU DSP?

**Comment by BenjaminSiskoo** [comment]
SCU DSP is about sound ?

**Comment by devmiyax** [comment]
Nope. Scu dsp is used for vertex calculation in some games like dead or alive.  I want to test this unit more.

**Comment by BenjaminSiskoo** [comment]
I can't rembember where i did get this list, I hope it's good : 
- Battle Monsters
- Blazing Tornado
- Blue Chicago Blues - J.B.Harold  
- Blue Seed
- Bubble Symphony
- Capcom Generations 1 
- Capcom Generations 4
- Crimewave
- Daisuki
- Dark Savior
- Dead or Alive
- Don Pachi
- Doom 
- Dragon Ball Z Shinbuthoden
- DX Jinsei Game - The Game of Life
- Fatal Fury 3
- Find Love 2
- Gal Panic SS
- Galaxy Force 2(sega ages)
- Grandia
- Grandia: Digital Museum
- GT24
- Guardian Force
- Guyferd
- Jissen Pachinko Hisshouhou! Twin
- Lunar 2 : Eternal Blue
- Magical Night Dreams Cotton Boomerang (J)
- Mega Man X4
- Momotaroudouchuuki
- Nadesico
- Mighty Hits
- Planet Joker
- Psychic Killer Taromaru
- Real Bout FF
- Real Bout FF Special
- Samurai Shodown RPG
- Sega Ages Memorial Selection - Vol. 1
- Shining Force 3 Scenario 1
- Shining Force 3 Scenario 2
- Shining Force 3 Scenario 3
- Sky Target
- Slam Dunk - I love Basketball (heavy usage)
- Slayers Royal
- Sonic R
- Stakes Winner SS
- Steeldom
- Street Fighter Collection Disc 1
- Super Real Mahjong P7
- Sword & Sorcery
- Tenga Seiha
- Tengai Makyou Dai Yon no Mokujiroku - The Apocalypse IV
- Toshinden Ura
- The Yakuyaken Special
- Thunderforce Gold Pack 1
- Victory Boxing
- Virtua Racing
- Virtua Fighter Remix
- Winter Heat
- Wonder 3
- Worms
- Yellow Brick Road
- Zero4 Champ DooZy-J Type-R

**Comment by devmiyax** [comment]
Great! Thank you.

**Comment by BenjaminSiskoo** [comment]
No problem. Dark Savior improvements, after pushing start, I can see the next screen to choose your saving slot. Then black screen :)

**Comment by VictorianTech** [comment]
Did you guys ever figure out a fix for the Shining Force 3 spell glitch?
