### ISSUE TITLE
[Beach Da Reach (J)] Missing logo at the start...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [devmiyax/yabause#181]
Left Picture : Yabause 02.21.2016 (Software)
Right Picture : Yabause Devmiyax 01.02.2016 (OpenGL)

![beachdareach](https://cloud.githubusercontent.com/assets/12481242/13202299/f7f1b290-d895-11e5-9fff-002e668377ec.JPG)
![beachdareach1](https://cloud.githubusercontent.com/assets/12481242/13202300/fae84b12-d895-11e5-93da-e2718bb73ca7.JPG)

**Comment by BenjaminSiskoo** [comment]
If you unchecked VDP1 Layer, logo are displayed but the main menu is not displayed

**Comment by devmiyax** [comment]
This issue is fixed by https://github.com/devmiyax/yabause/commit/e988b884cdbb65f2fc7e05c7b309b90d464ec12b

Please confirm, then close.

**Comment by BenjaminSiskoo** [comment]
Fixed, thanks
