### ISSUE TITLE
[Shining Force 3 - All Scenarios] - Text box crashes to main menu

### ISSUE THREAD

**Issue by SeanNOLA** [devmiyax/yabause#185]
On Samsung Galaxy Note 4:
Using Open GL
Game crashes when it tries to create a text box. Runs smoothly up until that point.

**Comment by devmiyax** [comment]
can't reproduce 

![image](https://user-images.githubusercontent.com/1174152/65154233-1a0ba180-da66-11e9-8aa8-559a2218eb16.png)
