### ISSUE TITLE
[Taito Chase HQ] Missing sky...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [devmiyax/yabause#188]
Left Picture : Yabause 03.06.2016 (Software)
Right Picture : Yabause 03.06.2016 (OpenGL)

![taito](https://cloud.githubusercontent.com/assets/12481242/13554215/7b0ab6c4-e3a2-11e5-8aa4-b37d74a2ad94.JPG)

**Comment by devmiyax** [comment]
This code is included?
https://github.com/devmiyax/yabause/commit/86c4f91b1cfc6bd2f5c4f22957a6c9a56b66a602

**Comment by BenjaminSiskoo** [comment]
I guess I missed this one, weird !!!

It's ok
