### ISSUE TITLE
BLAZING DRAGONS                                                                                                 

### ISSUE THREAD

**Issue by devmiyax** [devmiyax/yabause#189]
version:0.2.3
device:DL718M
cpu_type:2
video_type:2
The game appears to work with all the logos that are perfectly displayed, but you can't get past flickers bedroom cutscene,when it finishes,the game hangs

**Comment by BenjaminSiskoo** [comment]
Yabause Devmiyax 05.12.2016 (OpenGL)

No problem with windows version, it works properly. Maybe an iso problem !!!
