### ISSUE TITLE
Asynchronous rendring 

### ISSUE THREAD

**Issue by devmiyax** [devmiyax/yabause#19]
Asynchronous rendering is highly recommended!

Currently, Yabause emulates CPU and VDP(GPU) synchronously. 
At first, CPU is emulated for 16.666 msec(in emulated time), then VDP(GPU) is emulated.
CPU is not emulated while VDP(GPU) is emulated.

But on the real SEGA SATURN, CPU and VDP(GPU) is independent and run asynchronously. 
Furthermore modern CPUs are multi-core.

Separating CPU and VDP(GPU) emulation is expected to increase total emulation speed.

So, I implement it.

https://www.youtube.com/watch?v=Og11R6-b_T4

**Comment by wurz311** [comment]
Will this allow improvements to older hardware like snapdragon 801 and tegra 4 level hardware. Or does it require stronger cpus to take full advantage of changes?

**Comment by fivefeet8** [comment]
This branch requires the device to support OpenGL es3.  A Tegra 4 device lacks the drivers and hardware support for it.  A Snapdragon 801 however does support it and should benefit from the multi-processing improvements from this development.

**Comment by wurz311** [comment]
Thanks for the heads up. Hard to keep up with what supports what with mobile tech evolving like mad.

**Comment by wurz311** [comment]
Also. Sorry for double post. Any eta on a compiled apk for public consumption?
