### ISSUE TITLE
POWER SLAVE                                                                                                     

### ISSUE THREAD

**Issue by devmiyax** [devmiyax/yabause#191]
version:0.2.3
device:DL718M
cpu_type:2
video_type:2
Powerslave freezes when attempting to play the intro and the game music does not play 

![screenshot](http://www.uoyabause.org//system/reports/screenshots/000/000/791/original/_storage_emulated_0_yabause_screenshots_T-13205H_2016_03_05_14_49_02.png?1457207615)

**Comment by BenjaminSiskoo** [comment]
Yabause Devmiyax 05.12.2016 (OpenGL)

The game works with windows version. Maybe an iso problem ?
