### ISSUE TITLE
[Beach de Reach] Character window transparcy

### ISSUE THREAD

**Issue by devmiyax** [devmiyax/yabause#194]
![image](https://cloud.githubusercontent.com/assets/1174152/13683770/f020a9e4-e74b-11e5-8cdc-d35b9948323c.png)

**Comment by BenjaminSiskoo** [comment]
Seems ok !

![beachdareach](https://cloud.githubusercontent.com/assets/12481242/14409661/433e5e2e-ff1a-11e5-9569-d55359857a07.JPG)

**Comment by BenjaminSiskoo** [comment]
Seem the same problem than Resident Evil (with F1 Challenge fix).

![beachdareach_f1circuit_regression](https://cloud.githubusercontent.com/assets/12481242/14409999/71cfef60-ff23-11e5-8669-cf6ea5c6a28c.JPG)

**Comment by BenjaminSiskoo** [comment]
Fixed

**Comment by BenjaminSiskoo** [comment]
Yabause 05.12.2016

Fixed

![beach](https://cloud.githubusercontent.com/assets/12481242/15242189/0774a08e-18f5-11e6-9018-5d920474f21b.JPG)

**Comment by BenjaminSiskoo** [comment]
It works, guess topic could be closed !!!
