### ISSUE TITLE
[F1 Challenge] Missing circuit

### ISSUE THREAD

**Issue by BenjaminSiskoo** [devmiyax/yabause#198]
Left Picture : SSF 0.12 Beta r4
Right Picture : Yabause Devmiyax 03.12.2016 (OpenGL).

In the 1st person view, no problem. In the 3rd person view, small circuit is missing.

![f1 challenge](https://cloud.githubusercontent.com/assets/12481242/13817350/3364504e-eb92-11e5-8027-714f8c58fe6f.JPG)

**Comment by devmiyax** [comment]
per line operation using h-blank

LineCount	143	int
Vdp2Regs->BGON = 0x0011

LineCount	0x00000000	int
Vdp2Regs->BGON  = 0x0013

**Comment by devmiyax** [comment]
implement per line operation using hblank-in

![image](https://cloud.githubusercontent.com/assets/1174152/14586786/9bb491a8-04de-11e6-9455-5bdd070b1fbc.png)

**Comment by BenjaminSiskoo** [comment]
Great :)
