### ISSUE TITLE
AZEL does not start game

### ISSUE THREAD

**Issue by devmiyax** [devmiyax/yabause#20]
0x0601f3f4: sts.l pr. @-r15

PR = 0601ec00
R15 = 05FFEFE0  <--!!!!

**Comment by devmiyax** [comment]
0x0601ebf0: mov r15, r7
0x0601ebf2: bra 0x0601ec04
0x0601ebf4: nop
0x0601ebf6: mob.b r0, @r0
0x0601ebf8: bsr 0x0601EE60
0x0601ebfA: nop
0x0601ebfc: bsr 0x0601f3f4

**Comment by devmiyax** [comment]
PC: 0x0601ebf8
instruction: 0x3f18
sub R15 - R1

**Comment by devmiyax** [comment]
it seems that initial stack adrress is not used.

Cs2GetIP
  cdip->msh2stack	0x06006000
  cdip->ssh2stack	0x06003700

**Comment by devmiyax** [comment]
Welcome back AZEL!

![image](https://cloud.githubusercontent.com/assets/1174152/8638054/434ad8b0-28e8-11e5-95b4-d2b0c3f0547c.png)

**Comment by fivefeet8** [comment]
Awesome.  Hopefully an update coming soon.
