### ISSUE TITLE
GPU Tessellation

### ISSUE THREAD

**Issue by devmiyax** [devmiyax/yabause#200]
GPU Tessellation version for 
https://www.youtube.com/watch?v=8TleepxIORU

**Comment by BenjaminSiskoo** [comment]
congrats

**Comment by ADormant** [comment]
@devmiyax 
If you're already using tessellation for emulation would it be possible to implement additional tessellation like here?

https://github.com/Tinob/Ishiiruka/commit/07086223650bf2f7e13cfdaeddbc19c6f3f80d75
https://github.com/Tinob/Ishiiruka/commit/5408233340fab4e31a35ef074ec44df71638736e
https://github.com/Tinob/Ishiiruka/commit/d40f9df7ef04e467533ec515ef1c3075d06de12d
https://github.com/Tinob/Ishiiruka/commit/3374eb731c5128dcb843cbd17d904a1121f72aa1
https://github.com/Tinob/Ishiiruka/commit/db83d1d1c3abb9b6e3a750ecda7da6405822e56c
https://github.com/Tinob/Ishiiruka/commit/07086223650bf2f7e13cfdaeddbc19c6f3f80d75
https://github.com/Tinob/Ishiiruka/commit/bbccbe938486cb954bc13f0935610abdc5885f45
https://github.com/Tinob/Ishiiruka/commit/d4f525085234d54cc8d81f99eb4efa5e899b7bbc
https://github.com/Tinob/Ishiiruka/commit/5fe34864ff93b9010890b7ac8ba04cbebbab0123
https://github.com/Tinob/Ishiiruka/commit/6bf5062b7656d9d1d026478a2a639497cad2357b
https://github.com/Tinob/Ishiiruka/commit/8fbdccf842a08e5689c8f7f711d9010c1f71b496
https://github.com/Tinob/Ishiiruka/commit/f8cacdab52861d89eacabd7a69ae6019c3afc2da
https://github.com/Tinob/Ishiiruka/commit/bc87a8ea2705c1c17df96ad8dbd26b86154f09e1
https://github.com/Tinob/Ishiiruka/commit/bfa2915b1f34e1487a43672e6b3522007e8a761e
https://github.com/Tinob/Ishiiruka/commit/8f63da6f0985897e6f35a52d4f6c1a9536d1474f

**Comment by ADormant** [comment]
tessellation and displacement mapping
