### ISSUE TITLE
OpenGL crash with last sources

### ISSUE THREAD

**Issue by BenjaminSiskoo** [devmiyax/yabause#205]
I build windows release with last sources (more recent sources). If I set OpenGL mode, yabause crashes.

**Comment by devmiyax** [comment]
Do you have call stack when yabause crashes?

**Comment by BenjaminSiskoo** [comment]
No error message except this one : 

"Yabause Devmiyax 05.04.2016 has stopped working". No problem with the software renderer.

https://www.youtube.com/watch?v=CsbTI3pzn1s&feature=youtu.be

**Comment by devmiyax** [comment]
No. What I want to see is call stack window on Visual Studio.

![image](https://cloud.githubusercontent.com/assets/1174152/14332293/ce27a516-fc83-11e5-9b8c-c4e1aee9b191.png)

**Comment by BenjaminSiskoo** [comment]
![callstack_opengl](https://cloud.githubusercontent.com/assets/12481242/14334671/430d800e-fc56-11e5-9dbb-9a026959ccc4.jpg)
 is it ok ?

**Comment by devmiyax** [comment]
Push "Recommencer", then you can get call stack.

**Comment by BenjaminSiskoo** [comment]
here the pictures

![callstack 1](https://cloud.githubusercontent.com/assets/12481242/14367410/3eb81e20-fd18-11e5-8e06-c91e73114b47.png)
![callstack 2](https://cloud.githubusercontent.com/assets/12481242/14367413/433cb064-fd18-11e5-8db1-572a1fd745e1.png)

**Comment by devmiyax** [comment]
Add break point at yglshaderes.c line 56 with pressing 'F9' at the line. 
Select menu [DEBUG]->[Start Debugging].
Drag and drop 'infoLog' to Memory Window (you can show this window with selecting menu [DEBUG]->[Windows]->[Memory]->[Memory1]).

Then you can get error message.

![image](https://cloud.githubusercontent.com/assets/1174152/14398036/03eb736e-fe1c-11e5-9e93-61d56e967db6.png)

**Comment by BenjaminSiskoo** [comment]
Thanks to your time :) I hope I made it properly

![errorfragment](https://cloud.githubusercontent.com/assets/12481242/14399923/2ad57044-fdf2-11e5-9cc6-46d4af7c79e6.jpg)

**Comment by devmiyax** [comment]
Can you try this commit?

**Comment by BenjaminSiskoo** [comment]
Perfect it works, thank you very much.
