### ISSUE TITLE
SAKURA TAISEN2                                                                                                  

### ISSUE THREAD

**Issue by devmiyax** [devmiyax/yabause#208]
version:0.2.5
device:SO-02E
cpu_type:2
video_type:1
sony/XPERIA Z SO-02E/Android4.4 kitkat
![screenshot](http://www.uoyabause.org//system/reports/screenshots/000/000/952/original/_storage_emulated_0_yabause_screenshots_GS-9169_2016_04_08_22_03_01.png?1460120924)

**Comment by BenjaminSiskoo** [comment]
here another bug in game : Yabause Devmiyax 04.20.2016

![sakura taisen 2](https://cloud.githubusercontent.com/assets/12481242/14693931/fae8cbe4-0763-11e6-96e8-d6e14ba1cd6b.JPG)

**Comment by devmiyax** [comment]
still hapend on 2.7.5

![image](https://user-images.githubusercontent.com/1174152/65049731-37c30300-d9a1-11e9-8ddb-2c127f767e34.png)

**Comment by BenjaminSiskoo** [comment]
seems ok with 3.2.4 (windows)
