### ISSUE TITLE
DRAGON FORCE	GS-9028	JT

### ISSUE THREAD

**Issue by z4796158** [devmiyax/yabause#210]
Game title:
DRAGON FORCE
Maker:
SEGA ENTERPRISES
Product number:
GS-9028
Version:
V1.007
Release date:
1996-08-03
Device infomation:
CD-1/1
Area:
JT
Input device:
J

not play  plz   help   ,There is no picture ,Thanks

**Comment by devmiyax** [comment]
works very well on 2.7.5
![image](https://user-images.githubusercontent.com/1174152/65048864-cafb3900-d99f-11e9-8921-d4dac453d825.png)
