### ISSUE TITLE
[Akumajou Dracula X] menu problem...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [devmiyax/yabause#214]
Left Picture : Yabause Devmiyax 05.05.2016 (OpenGL)
Right Picture : Yabause 05.05.2016 (Software)

![dracula](https://cloud.githubusercontent.com/assets/12481242/15069148/f9a54144-137b-11e6-9407-240ad2f1da6d.JPG)

**Comment by BenjaminSiskoo** [comment]
UoYabause 0.4.1 : same problem

**Comment by BenjaminSiskoo** [comment]
UoYabause 0.5.2 : same problem

**Comment by BenjaminSiskoo** [comment]
UoYabause 0.5.2 commit 4106 :  same problem

**Comment by BenjaminSiskoo** [comment]
Same problem with Yaba Sanshiro 1.3.0 RC

**Comment by BenjaminSiskoo** [comment]
Yaba Sanshiro 1.7.0 : same problem.

**Comment by BenjaminSiskoo** [comment]
Same problem with Yaba Sanshiro 2.3.1

**Comment by devmiyax** [comment]
dupe with #172
