### ISSUE TITLE
[Alone In The Dark 2 (E)] GFX problem...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [devmiyax/yabause#215]
Left Picture :  Yabause Devmiyax 05.05.2016 (OpenGL)
Right Picture :  Yabause Devmiyax 05.05.2016 (Software)

![alone in the dark2](https://cloud.githubusercontent.com/assets/12481242/15069454/f70b6d6c-137d-11e6-98e5-56a57f4aaa45.JPG)

**Comment by devmiyax** [comment]
When back up memory is cleared, this message is not shown.
It seems that OpenGL version is right.
![image](https://cloud.githubusercontent.com/assets/1174152/15086357/1f26ff80-141b-11e6-989d-3e0834fb7988.png)

**Comment by BenjaminSiskoo** [comment]
Ok, thanks to the quick answer. It seems to work. So is it a bug with backup memory ?
