### ISSUE TITLE
[Astal] Shadow problem...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [devmiyax/yabause#216]
Left picture : Yabause Devmiyax 05.05.2016 (OpenGL)
 Right picture : Yabause 05.05.2016 (Software)

![astalopengl](https://cloud.githubusercontent.com/assets/12481242/15069668/8dfeaeea-137f-11e6-9f7c-f983b3b615e1.JPG)

**Comment by devmiyax** [comment]
MSB Shadow seems fixed alpha value.

![image](https://cloud.githubusercontent.com/assets/1174152/15096689/3e29d734-153f-11e6-8ecd-8bb17bc8b80b.png)

**Comment by BenjaminSiskoo** [comment]
Seems nice, keep up the good work.
