### ISSUE TITLE
Fatal Fury 3 [wrong palette and freezes]

### ISSUE THREAD

**Issue by paul-met** [devmiyax/yabause#217]
After loading screen the game displays wrong palette. Then the game freezes on loading screen before a battle match.
![01](https://cloud.githubusercontent.com/assets/13948032/15090983/5b1645ce-1442-11e6-9eef-c0c97f7c3613.png)

**Comment by devmiyax** [comment]
![image](https://user-images.githubusercontent.com/1174152/65364576-9dd3b280-dc4d-11e9-9356-4574b58bc889.png)
