### ISSUE TITLE
Megaman X4 Controller Disconnects

### ISSUE THREAD

**Issue by fivefeet8** [devmiyax/yabause#22]
When running Megaman X4, the control pad will disconnect reconnect over and over and the game will warn about it ingame.  The game is unplayable because of this, but otherwise looks pretty well rendered.

**Comment by BenjaminSiskoo** [comment]
There is a fix from the Yabause Original https://github.com/Yabause/yabause/pull/135. Is it possible to add this on the devmiyax branch ?

**Comment by devmiyax** [comment]
I merge this commit and confirm this issue is fixed! 
https://github.com/devmiyax/yabause/commit/9f79ab71d4e5578cbf28afb13641c0065750c2ad
