### ISSUE TITLE
Game interruption due to ads restarts game

### ISSUE THREAD

**Issue by tuillip** [devmiyax/yabause#228]
When I have been playing for around a half an hour (not sure of the exact mechanism, but I think it is related to ads), the screen goes blank or at least loads the uoyabause support screen.  Since my android device cannot show the whole message on this screen (I am using an lg leon which has a 480x854 pixel resolution), I'm not sure how to get past this advertisement section to get back to the game without progress being lost.  Even if I wanted to pay to disable ads, the screen resolution is too small to show the whole message allowing me to select this option and do away with the interruptions.  One other thing - when I choose to check a different app going on in the background, most of the time navigating away from uoyabause also causes the player to go back to the homescreen, so in case I'm missing a way to get back to the game, it seems like this way also a lot of gameplay can be lost.  This happened in particular when I went to respond to a text I was notified of, and switching between the apps allowed this issue to happen.  So, it would be nice if this issue could be resolved, or there are clearer instructions for how to resume the game and avoid potential issues these things may cause.

**Comment by devmiyax** [comment]
Just crashed.
