### ISSUE TITLE
FXAA Filter problem...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [devmiyax/yabause#234]
Right Picture : UoYabause 06.12.2016 (OpenGL)
Left Picture : UoYabause 04.10.2016 (OpenGL)

With the windows release, FXAA filter doesn't seems to work. Here 2 pictures with the same video settings. with the previous release, filter works, and not with the new one.

![filter_problem_2](https://cloud.githubusercontent.com/assets/12481242/16074961/2a92defc-32ed-11e6-91d9-cf64b7733abf.JPG)

**Comment by devmiyax** [comment]
It's strange :)  In my environment it works fine. 
![image](https://cloud.githubusercontent.com/assets/1174152/16093665/c9d94ef8-3377-11e6-938e-64bf843d05b3.png)

What video card do you use?

**Comment by BenjaminSiskoo** [comment]
AMD Radeon R9 200 Series. With the last driver 16.6.1. I can see your FPS counter on your pic, it doesn't works with OpenGL to me. Or are you set the Software renderer ?

**Comment by devmiyax** [comment]
Choose nanovg OSD Interface

![image](https://cloud.githubusercontent.com/assets/1174152/16097024/9b073522-3386-11e6-96ef-1fb3f138f81a.png)

**Comment by BenjaminSiskoo** [comment]
Very nice :) Whait is nanovg exactly ?

**Comment by devmiyax** [comment]
https://github.com/memononen/nanovg

it's very small and fast.

**Comment by BenjaminSiskoo** [comment]
Ok, thanks for the info :)

**Comment by BenjaminSiskoo** [comment]
Finally I found the problem. In the ini file, there is a problem with Geometry/general. 

filter work with this line (I don't know how I get this line working) : 
General\Geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x2\0\0\0\0\x2\0\0\0\0\x94\0\0\x5\x46\0\0\x3\t\0\0\x2\b\0\0\0\xb3\0\0\x5>\0\0\x3\x1\0\0\0\0\0\0\0\0\x6\x90)

filter is not working with this one : 
General\Geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x2\0\0\0\0\x2\0\0\0\0\xea\0\0\x4\x8f\0\0\x2\xf0\0\0\x2\b\0\0\x1\t\0\0\x4\x87\0\0\x2\xe8\0\0\0\0\0\0\0\0\x6\x90)

With the working line, no more problem with FXAA filter and Scanline Filter

**Comment by paul-met** [comment]
FXAA just worsens the image. xBR filters will be more useful.

**Comment by devmiyax** [comment]
FXAA works fine 2.7.5
