### ISSUE TITLE
Vandal Hearts issue

### ISSUE THREAD

**Issue by paul-met** [devmiyax/yabause#237]
In this game does not displays rectangular cursor. In addition, in opengl mode, there are problems with transparency.
![vh](https://cloud.githubusercontent.com/assets/13948032/16178235/2041434c-364b-11e6-8e51-9b7a8dab326f.png)

**Comment by paul-met** [comment]
The same situation on Yaba Sanshiro 2.6.8.

**Comment by devmiyax** [comment]
no cursor
![image](https://user-images.githubusercontent.com/1174152/65364836-4e8e8180-dc4f-11e9-8c73-db799c2b5fd8.png)

**Comment by paul-met** [comment]
The bug with  no cursor still present on version 3.1.3 (win).

**Comment by devmiyax** [comment]
fixed by 1.9.0
![image](https://user-images.githubusercontent.com/1174152/174464328-011d791f-3027-4a6b-bb70-855a7308aab4.png)
