### ISSUE TITLE
[Grandia] RBG0 

### ISSUE THREAD

**Issue by devmiyax** [devmiyax/yabause#238]
![image](https://cloud.githubusercontent.com/assets/1174152/16179576/c7b250ae-36a4-11e6-8284-c3a937270172.png)

**Comment by devmiyax** [comment]
![image](https://cloud.githubusercontent.com/assets/1174152/16179697/befd1bde-36a8-11e6-86eb-9ab2bd0759bb.png)

**Comment by devmiyax** [comment]
Xst: -75.225586, Yst: -115.592773, Zst: 0.000000, deltaXst: 0.000000 deltaYst: 0.849609 deltaX: 0.426758
deltaY: 0.000000 A: 0.704102 B: 0.708984 C: 0.000000 D: -0.709961 E: 0.704102 F: 0.000000 Px: 0.000000 Py: 0.000000 Pz: 0.000000
Cx: 0.000000 Cy: 0.000000 Cz: 0.000000 Mx: 1454.290039 My: 991.762695 kx: 1.000000 ky: 1.000000 KAst: 45056.000000
deltaKAst: 1.000000 deltaKAx: 0.000000 kadr 00036000

Xst: -112.000000, Yst: 869.265625, Zst: 0.000000, deltaXst: 0.000000 deltaYst: 1.000000 deltaX: 1.000000
deltaY: 0.000000 A: 1.000000 B: 0.000000 C: 0.000000 D: 0.000000 E: 1.000000 F: 0.000000 Px: 0.000000 Py: 0.000000 Pz: 0.000000
Cx: 0.000000 Cy: 0.000000 Cz: 0.000000 Mx: 1024.000000 My: 1024.000000 kx: 1.000000 ky: 1.000000 KAst: 0.000000
deltaKAst: 0.000000 deltaKAx: 0.000000 kadr 00000000

**Comment by devmiyax** [comment]
![image](https://cloud.githubusercontent.com/assets/1174152/16179822/c4ea1bba-36ac-11e6-974a-6d91d5c4093c.png)

**Comment by paul-met** [comment]
A lot of bugs in the battle mode:
![01](https://user-images.githubusercontent.com/13948032/35191374-5d913a00-fe8a-11e7-838d-e0c9215011c5.png)

**Comment by devmiyax** [comment]
works fine on 2.7.5
