### ISSUE TITLE
Games fail to load on the Nexus Player.

### ISSUE THREAD

**Issue by LinkofHyrule89** [devmiyax/yabause#24]
When I try and load any game the screen flashes and it goes back to the gui of the app without starting.

**Comment by devmiyax** [comment]
Could you give me the result of 'adb logcat ' when the problem is happend?

**Comment by LinkofHyrule89** [comment]
Certainly I can do that. Interestingly enough a similar problem occurs in another project I am helping with so if they are caused by the same issue maybe we can fix it on both. https://paste.ee/p/AmQss

**Comment by LinkofHyrule89** [comment]
This issue may be related to a problem with the NDK https://code.google.com/p/android/issues/detail?id=179410

**Comment by devmiyax** [comment]
it not supported
