### ISSUE TITLE
iOS Version Of Yabause

### ISSUE THREAD

**Issue by mk8itra1n** [devmiyax/yabause#240]
Saw your video on YouTube of uoYabause running on the iPhone 6 Plus which I own as well. Wanted to know if the app is out to beta test. It seems to run quite well since it's running off the iPhone GPU at about 50 to 60FPS. Just want to know if you plan to release it in Cydia soon? Looking forward to hearing more about this from you soon bro👍

**Comment by devmiyax** [comment]
It's already pushed.

https://github.com/devmiyax/yabause/tree/extui/yabause/src/ios

**Comment by mk8itra1n** [comment]
Yep I saw. Thx for the help!
