### ISSUE TITLE
Redump rips .cue not supported

### ISSUE THREAD

**Issue by Catarax** [devmiyax/yabause#241]
Hello,
When I try to launch a .cue from a redump rip, I have the message "can't initialize yabause".
I can play from a bin or I have to mount the disc to play on uoYabause else.

I can share the redump rip files if necessary. 
It would be great to have a support of this since .cue format seems supported by the fork here.

Thanks!

**Comment by devmiyax** [comment]
Please attach your .cue file

**Comment by Catarax** [comment]
**Dragon Ball Z - Shinbutouden (Japan).cue :**
https://mega.nz/#!TQZ3DDCT!-Shrx-X2mWJllXE5X7zCfbYT6ZknFVJCMlRtiaSAKEY

**Comment by devmiyax** [comment]
Multiple iso image  is not supported 

FILE "Dragon Ball Z - Shinbutouden (Japan) (Track 01).bin" BINARY
  TRACK 01 MODE1/2352
    INDEX 01 00:00:00
FILE "Dragon Ball Z - Shinbutouden (Japan) (Track 02).bin" BINARY
  TRACK 02 AUDIO
    INDEX 00 00:00:00
    INDEX 01 00:02:00

This should be like this

FILE "Dragon Ball Z - Shinbutouden (Japan) .bin" BINARY
  TRACK 01 MODE1/2352
    INDEX 01 00:00:00
  TRACK 02 AUDIO
    PREGAP 00:02:00
    INDEX 01 09:47:07
  TRACK 03 AUDIO
    INDEX 00 11:58:08
    INDEX 01 12:00:08
  TRACK 04 AUDIO
    INDEX 00 12:05:11
    INDEX 01 12:07:11
  TRACK 05 AUDIO
    INDEX 00 12:17:43
    INDEX 01 12:19:43

You can use [CD Manipulator](http://www.storeroom.info/cdm/) to generate this kind of cue file.

**Comment by Catarax** [comment]
Thanks, i'll try to generate a new CD like this.
I've asked some time ago if Yabause original developpers were going to support the format and they will never. 

Wondering if you could add support to it, since some emulators like ePSXe added support to it last year. Thanks.

**Comment by devmiyax** [comment]
multi file is supported by https://github.com/devmiyax/yabause/commit/2bfe62a1c8fccafc1e398aba3951c65a97aebf2a

**Comment by barolo** [comment]
> multi file is supported by [2bfe62a](https://github.com/devmiyax/yabause/commit/2bfe62a1c8fccafc1e398aba3951c65a97aebf2a)

Does it mean that games like Panzer Dragon Saga  [ 4 discs ] can be played now?
