### ISSUE TITLE
Menu on GPD XD issue

### ISSUE THREAD

**Issue by aydinseven** [devmiyax/yabause#242]
I installed the Legacy ROM from here http://boards.dingoonity.org/gpd-devices/(rom)-legacyrom-kitkat-for-gpd-xd to get the GPD XD on 1,8GHz. uoYabause now runs smoothly, but the menu is faulty. See this image:
http://www.pic-upload.de/view-31069263/DSC_0232.jpg.html
Could you take a look at this?

Thanks a lot for your hard work. Very appreciated!

**Comment by devmiyax** [comment]
Android 4.x is not supported now
