### ISSUE TITLE
GOLDEN AXE DUEL bad graphics in 0.30 version

### ISSUE THREAD

**Issue by skelton** [devmiyax/yabause#244]
In 0.30 characters are not displayed in scenearios. Tested in three system

Redmi note 2 with power VR GC6 series

GPD XD with mali 760

Shield tablet k1.

In all three devices happen the same.

**Comment by devmiyax** [comment]
works fine v2.7.5

![image](https://user-images.githubusercontent.com/1174152/65364881-c0ff6180-dc4f-11e9-8450-31b951958c37.png)
