### ISSUE TITLE
Windows compiling problem...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [devmiyax/yabause#247]
There is a windows (32 bits) compiling problem with your last sources

![compiling problem](https://cloud.githubusercontent.com/assets/12481242/16899499/bd1223dc-4c06-11e6-909c-022a5757f2b5.JPG)

**Comment by BenjaminSiskoo** [comment]
![compiling problem 2](https://cloud.githubusercontent.com/assets/12481242/16899509/0f7c6f9c-4c07-11e6-9595-e341cc7dd875.JPG)

**Comment by devmiyax** [comment]
I'm sorry. my local code for debug is remained. 
Now it's fixed with 1b56d6880ef7693098b4042d765c9486562f83dd

**Comment by BenjaminSiskoo** [comment]
No problem.) You don't have to be sorry :)

Now it works. I try to compile with directsound and I've got another compiling problem : 

DxErr.lib(dxerra.obj) : error LNK2019: symbole externe non résolu __vsnprintf référencé dans la fonction "long __stdcall StringVPrintfWorkerA(char *,unsigned int,unsigned int *,char const *,char *)" (?StringVPrintfWorkerA@@YGJPADIPAIPBD0@Z)
5>C:\...\Desktop\Yabause Devmiyax\src\qt\Release\yabause.exe : fatal error LNK1120: 1 externes non résolus

Could you help me with that ?

**Comment by devmiyax** [comment]
You'd better user VS2013
http://stackoverflow.com/questions/31053670/unresolved-external-symbol-vsnprintf-in-dxerr-lib

**Comment by BenjaminSiskoo** [comment]
I saw this topic; I'll check it later, thanks
