### ISSUE TITLE
[Riglord Saga 2] No boot, black screen after pushing start...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [devmiyax/yabause#252]
UoYabause 0.3.2 (OpenGL)

There is a black screen after the "Now Loading" screen (push start on the main screen).

**Comment by BenjaminSiskoo** [comment]
UoYabause 0.3.8 - same problem

**Comment by BenjaminSiskoo** [comment]
UoYabause 0.4.1 : same problem

**Comment by BenjaminSiskoo** [comment]
UoYabause 0.4.6 : same problem

**Comment by BenjaminSiskoo** [comment]
UoYabause 0.5.2 commit 4106 :  same problem

**Comment by BenjaminSiskoo** [comment]
UoYabause 0.5.6 : same problem.

**Comment by BenjaminSiskoo** [comment]
Same problem with Yaba Sanshiro 1.3.0 RC

**Comment by BenjaminSiskoo** [comment]
Same problem with Yaba Sanshiro 1.3.1

**Comment by BenjaminSiskoo** [comment]
Yaba Sanshiro 1.7.0 : same problem.

**Comment by BenjaminSiskoo** [comment]
Same problem with Yaba Sanshiro 2.2.0.

**Comment by devmiyax** [comment]
!!!
![image](https://user-images.githubusercontent.com/1174152/52061537-df75f700-25b1-11e9-82af-a288bcb4f9e3.png)

**Comment by BenjaminSiskoo** [comment]
Windows or Android ? 

Maybe my iso is wrong.
