### ISSUE TITLE
Emulator does not seem to keep saves made to ram or internal storage

### ISSUE THREAD

**Issue by delongeone** [devmiyax/yabause#26]
When I try to save inside panzer dragoon saga I get confirmation that the save has been completed but when I close the game and open it up again and try to load the save I made, it says there is none there. I know you can save states externally with the emulator, I'm mainly concerned beçause of the need to have an internal save to start the next disk of a multi disk game like panzer dragoon saga.

**Comment by fivefeet8** [comment]
Yeah, I reported this issue in the Google+ community.  In game saves don't quite work right. I was playing Shining Force 3 and noticed it there as well.

**Comment by devmiyax** [comment]
it seems that Deinit is not called when the process is killed

  if (BupRam)
   {
      if (T123Save(BupRam, 0x10000, 1, bupfilename) != 0)
         YabSetError(YAB_ERR_FILEWRITE, (void *)bupfilename);

      T1MemoryDeInit(BupRam);
   }
   BupRam = NULL;

void CartDeInit(void)
{
   if (CartridgeArea)
   {
      if (CartridgeArea->carttype == CART_PAR)
      {
         if (CartridgeArea->rom)
         {
            if (T123Save(CartridgeArea->rom, 0x40000, 2, CartridgeArea->filename) != 0)
               YabSetError(YAB_ERR_FILEWRITE, (void *)CartridgeArea->filename);
            T2MemoryDeInit(CartridgeArea->rom);
         }
      }
      else
      {
         if (CartridgeArea->rom)
            T1MemoryDeInit(CartridgeArea->rom);
      }

**Comment by devmiyax** [comment]
Panzer dragoon saga has another problem. I treat it as another issue.
