### ISSUE TITLE
[SD Gundam G Century S] No boot...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [devmiyax/yabause#260]
UoYabause 0.3.2 (OpenGL)

Black screen at the start, It doesn't boot.

**Comment by BenjaminSiskoo** [comment]
UoYabause 0.4.6 : same problem

**Comment by BenjaminSiskoo** [comment]
UoYabause 0.5.6 :  same problem

**Comment by devmiyax** [comment]
v2.8.2: same problem

**Comment by BenjaminSiskoo** [comment]
Same problem with Yaba 3.2 b2

**Comment by BenjaminSiskoo** [comment]
Same problem with Yaba 3.2.4

**Comment by BenjaminSiskoo** [comment]
Same problem Yaba 3.4.2

**Comment by devmiyax** [comment]
fixed by 1.9.0
