### ISSUE TITLE
[Garou Densetsu 3 - Harukanaru Tatakai] No boot...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [devmiyax/yabause#261]
UoYabause 0.3.2 (OpenGL)

Black screen at the start. No boot.

**Comment by BenjaminSiskoo** [comment]
UoYabause 0.3.8 - same problem

**Comment by BenjaminSiskoo** [comment]
UoYabause 0.4.6 - same problem

**Comment by devmiyax** [comment]
Infinity loop

'''
0x0603BB54: mov.b @r0, r2  ; R0=0600208D
0x0603BB56: tst r2, r2
0x0603BB58: bf 0x0603BB54

0x0603BB5A: mov.l @(0x020, pc), r0 ; 0x0603BB78
0x0603BB5C: mov.w @r0, r0  ; @R0=25F80004
0x0603BB5E: tst #0x0C, r0
0x0603BB60: bf 0x0603BB5A
'''

**Comment by devmiyax** [comment]
```
0x0603BB62: mov.l @(0x010, pc), r2 ; 0x0603BB70
0x0603BB64: mov.w @r2, r0  ; r2= 25CBFFF0 vfd1 framebuffer
0x0603BB66: cmp/eq r0, r5
0x0603BB68: bf 0x0603BB4E
```

**Comment by devmiyax** [comment]
r5 should be 0x1 @ 0603BB4E

**Comment by devmiyax** [comment]
Progressed.

![image](https://user-images.githubusercontent.com/1174152/27985116-dcd5c1ce-641f-11e7-9ac7-d65935637c1f.png)

**Comment by BenjaminSiskoo** [comment]
Nice :)

**Comment by BenjaminSiskoo** [comment]
Fixed
