### ISSUE TITLE
[Gotha - Ismailia Seneki (J)] Master SH2 invalid opcode....

### ISSUE THREAD

**Issue by BenjaminSiskoo** [devmiyax/yabause#263]
UoYabause 0.3.2 (OpenGL)
Yabause 0.9.15 (OpenGL)

The game works with OpenGL and Software with Yabause 0.9.15 (public release). UoYabause, the game crash on this error message.

Master SH2 invalid opcode

R0 =  FFFFFFEC  R12 =  060706EC
R1 =  0607161C  R13 =  060706F0
R2 =  00000000  R14 =  00000000
R3 =  060B0000  R15 =  060FFFB4
R4 =  00000002  SR =   00000001
R5 =  060A5354  GBR =  00000000
R6 =  00000BC1  VBR =  06000000
R7 =  00000003  MACH = 00000000
R8 =  06071236  MACL = 00000000
R9 =  0601CC04  PR =   0601075C
R10 = 06045E20  PC =   060B0000
R11 = 060B0000

**Comment by BenjaminSiskoo** [comment]
UoYabause 0.3.6 - same problem

**Comment by BenjaminSiskoo** [comment]
UoYabause 0.4.6 - same problem

**Comment by BenjaminSiskoo** [comment]
UoYabause 0.5.6 : back to the bios.

**Comment by BenjaminSiskoo** [comment]
Yaba Sanshiro 2.2.0 : same problem

**Comment by devmiyax** [comment]
on 2.7.5 works fine

![image](https://user-images.githubusercontent.com/1174152/65156682-77a1ed00-da6a-11e9-8a58-1d28725c2089.png)
