### ISSUE TITLE
[Tomb Raider] Massive GFX problem in game...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [devmiyax/yabause#268]
Left picture : SSF Test version (last release)
Right picture : UoYabause 0.3.2 (OpenGl)

![tombraideruoyabause](https://cloud.githubusercontent.com/assets/12481242/19346303/f94a6a2c-9142-11e6-960a-f641ef375780.JPG)

**Comment by fivefeet8** [comment]
Would be nice to get this game rendering correctly and possibly some Bilinear filtering for the pixels.  :)

**Comment by devmiyax** [comment]
![image](https://cloud.githubusercontent.com/assets/1174152/25560978/a9a30050-2d9c-11e7-9567-f1e15d01258f.png)
