### ISSUE TITLE
Iron Storm (Daisenryaku) series control input problem (0.9.15)

### ISSUE THREAD

**Issue by DaisenryakuFan** [devmiyax/yabause#270]
Control inputs with the Daisenryaku (Japan) / Iron Storm (US) series of games has been fiddly with Yabause for a while. The latest 0.9.15 version fixed most of the issues, but some still remain.

SETTINGS:
BIOS: US BIOS SEGA_100.BIN
Video Core: Software Video Interface
OSD Core: Software OSD Interface
Fixed Aspect Ratio 4:3
1280 x 1024
Video Format NTSC

SDL Sound Interface

32 MBIT Backup RAM Cart

Input:
SDL Joystick Interface

Port 1 #1, Pad.

Region: Auto Detect
SH2 Interpreter
Musashi Interface
SH2 Interpreter

Here's the problem.

I use a Microsoft SIDEWINDER USB Gamepad, and when I map the keys for a standard saturn gamepad to my Sidewinder; the following issues happen:

UP/DOWN/LEFT/RIGHT keys do not work, but all other keys on gamepad (X/Y/Z A/B/C / START / LEFT SHOULDER / RIGHT SHOULDER) work correctly.

Currently my hackaround fix is to remap the  UP/DOWN/LEFT/RIGHT keys to my physical PC keyboard, which works.

**Comment by devmiyax** [comment]
SIDEWINDER USB Gamepad is too old.
