### ISSUE TITLE
Bad Color calculation in Doukoku Soshite at Name Selection Screen 

### ISSUE THREAD

**Issue by devmiyax** [devmiyax/yabause#274]
uoyabause
![name](https://cloud.githubusercontent.com/assets/1174152/20459001/b980b1f4-aef6-11e6-8b0c-1cfeaf268977.png)

SSF
![ssf](https://cloud.githubusercontent.com/assets/1174152/20459005/d71a3c1c-aef6-11e6-8090-cfca8635ea5b.png)

**Comment by devmiyax** [comment]
WCTLD = 0x8F00 = 1000 1111 0000 0000

CCLOG  Color Logic enable
CCW1E  W1 Eanble
CCW1A  Out side of W1
CCW0E  W0 Eanble
CCW0A  Outside of W0

**Comment by devmiyax** [comment]
related to #104

**Comment by devmiyax** [comment]
![fix](https://cloud.githubusercontent.com/assets/1174152/20460658/e9e6b564-af2d-11e6-9d10-0827d2185b35.png)

**Comment by devmiyax** [comment]
SSF
![2](https://cloud.githubusercontent.com/assets/1174152/20460697/d42a799e-af2e-11e6-99b9-f93c46ebb5e3.png)

**Comment by devmiyax** [comment]
![image](https://cloud.githubusercontent.com/assets/1174152/20461308/153a2494-af3d-11e6-9e25-82297974dfd1.png)

**Comment by BenjaminSiskoo** [comment]
Nice to see some fixing emulation problem :) Keep up the good work...
