### ISSUE TITLE
Game execution using Intents

### ISSUE THREAD

**Issue by zevektor** [devmiyax/yabause#28]
Hello, 

will you consider supporting game execution through intents, so that 3rd-party applications can launch games using your emulator? (i.e. Gamesome/Nostalgia/Hyperspin)

**Comment by devmiyax** [comment]
You can use this Intent for start game.

Target: org.uoyabause.android/org.uoyabause.android.Yabause
Key: org.uoyabause.android.FileNameEx
Type: String
Value: absolute file path for a game CD-ROM ISO imag
