### ISSUE TITLE
[Arcana Strike] Missing FMVs

### ISSUE THREAD

**Issue by BenjaminSiskoo** [devmiyax/yabause#286]
UoYabause 0.3.8 

Missing FMVs (Black screen)

**Comment by BenjaminSiskoo** [comment]
UoYabause 0.4.6 : same problem

**Comment by devmiyax** [comment]
works 2.7.5
![image](https://user-images.githubusercontent.com/1174152/65367785-2401f000-dc72-11e9-9a97-60fd7d5a4d81.png)
