### ISSUE TITLE
[GUNGRIFFON] Black screen when game start

### ISSUE THREAD

**Issue by devmiyax** [devmiyax/yabause#288]

**Comment by devmiyax** [comment]
Infinity loop on Main CPU

0x0603DF10: mov.l @r1(0x2678FA8), r0
0x0603DF12: cmp/eq #0x01, R0
0x0603DF14: bf 0x0603DF10

**Comment by devmiyax** [comment]
Infinity loop on Slave CPU

0x0603E2B8: mov.l @r2(0x26078FA4), r0
0x0603E2BA: cmp/eq #0x02, r0
0x0603E2Bc: bt 0x0603E2B8

**Comment by devmiyax** [comment]
Before infinity loop, command for Slave CPU is requested.

```
0x0603DF0E: mov.l @(0x07C, pc), ((r1)0xFFFFFF81) ; 0x0603DF88
0x0603DF0C: mov.b ((r1)0xFFFFFF81), @((r12)0xFFFFFE10)
0x0603DF0A: mov #0x81, ((r1)0x00000001)
0x0603DF08: mov.l @(0x074, pc), ((r12)0xFFFFFE10) ; 0x0603DF7C
0x0603DEFA: bt 0x0603DF08
0x0603DEF8: cmp/eq #0xFF, r0
0x0603DEF6: mov.w @((r13)0x0607353A)+, ((r0)0xFFFFFFFF)
0x0603DEF4: mov.l @((r14)0x06073510), ((r13)0x0607353A)
0x0603DEF2: mov.l @(0x070, pc), ((r14)0x00000000) ; 0x0603DF60
```

**Comment by devmiyax** [comment]
Slave input capture interrupt PC is 0x06040fdc.

**Comment by devmiyax** [comment]
for to proceed by writing @26078FA8 to 1

![gd01](https://cloud.githubusercontent.com/assets/1174152/21515031/5fab0260-cd0f-11e6-839d-b2305df4c556.png)

**Comment by devmiyax** [comment]
write 0x64 @ Master VCRC and 0x0F IPRB on startup


![gd1](https://cloud.githubusercontent.com/assets/1174152/21520039/bbf71bd8-cd34-11e6-9af7-405c1bf86917.png)

**Comment by devmiyax** [comment]
RGB0 is still have problem..

![gd2](https://cloud.githubusercontent.com/assets/1174152/21520141/916de3aa-cd35-11e6-96f0-963bef88e0fa.png)

**Comment by BenjaminSiskoo** [comment]
Quick progress. I guess you fixed the Master SH2 invalid opcode ?

**Comment by devmiyax** [comment]
No. This problem was caused by miss-communication between Master cpu and Slave cpu.

**Comment by BenjaminSiskoo** [comment]
ok :)

**Comment by devmiyax** [comment]
refrence
![Uploading image.png…]()

**Comment by devmiyax** [comment]
![image](https://cloud.githubusercontent.com/assets/1174152/21520792/a2d2d2ea-cd3a-11e6-9789-b30c1adbde6e.png)

**Comment by devmiyax** [comment]
kaisuu table @ Final Fight Revenge

'''
0x0D0C1440  5f 00 80 00  _...
0x0D0C1444  5f 00 7f 80  _...
0x0D0C1448  5e 00 7f 01  ^...
0x0D0C144C  5e 00 7e 84  ^.~・
0x0D0C1450  5e 00 7e 07  ^.~.
0x0D0C1454  5e 00 7d 8c  ^.}・
0x0D0C1458  5e 00 7d 11  ^.}.
0x0D0C145C  5e 00 7c 97  ^.|・
0x0D0C1460  5e 00 7c 1f  ^.|.
0x0D0C1464  5e 00 7b a7  ^.{ｧ
0x0D0C1468  5d 00 7b 30  ].{0
0x0D0C146C  5d 00 7a ba  ].zｺ
0x0D0C1470  5d 00 7a 44  ].zD
0x0D0C1474  5d 00 79 d0  ].yﾐ
0x0D0C1478  5d 00 79 5c  ].y\
0x0D0C147C  5d 00 78 ea  ].x・
0x0D0C1480  5d 00 78 78  ].xx
0x0D0C1484  5d 00 78 07  ].x.
0x0D0C1488  5c 00 77 97  \.w・
0x0D0C148C  5c 00 77 28  \.w(
0x0D0C1490  5c 00 76 b9  \.vｹ
0x0D0C1494  5c 00 76 4b  \.vK
0x0D0C1498  5c 00 75 de  \.uﾞ
0x0D0C149C  5c 00 75 72  \.ur
0x0D0C14A0  5c 00 75 07  \.u.
0x0D0C14A4  5c 00 74 9c  \.t・
0x0D0C14A8  5b 00 74 32  [.t2
0x0D0C14AC  5b 00 73 c9  [.sﾉ
0x0D0C14B0  5b 00 73 61  [.sa
0x0D0C14B4  5b 00 72 f9  [.r・
0x0D0C14B8  5b 00 72 92  [.r・
0x0D0C14BC  5b 00 72 2c  [.r,
'''

**Comment by devmiyax** [comment]
keisuu table @ GUNGRIFFON

Bad address or Bad Value???

```
0x0C4C9C68  00 00 40 88  ..@・
0x0C4C9C6C  00 00 40 89  ..@・
0x0C4C9C70  00 00 80 8a  ...・
0x0C4C9C74  00 00 80 8b  ...・
0x0C4C9C78  00 00 80 8c  ...・
0x0C4C9C7C  00 00 c0 8e  ..ﾀ・
0x0C4C9C80  00 00 00 90  ...・
0x0C4C9C84  00 00 40 91  ..@・
0x0C4C9C88  00 00 40 92  ..@・
0x0C4C9C8C  00 00 80 93  ...・
0x0C4C9C90  00 00 00 96  ...・
0x0C4C9C94  00 00 40 97  ..@・
0x0C4C9C98  00 00 c0 98  ..ﾀ・
0x0C4C9C9C  00 00 00 9a  ...・
0x0C4C9CA0  00 00 40 9b  ..@・
0x0C4C9CA4  00 00 c0 9c  ..ﾀ・
0x0C4C9CA8  00 00 80 9f  ...・
0x0C4C9CAC  00 00 00 a1  ...｡
0x0C4C9CB0  00 00 40 a2  ..@｢
0x0C4C9CB4  00 00 c0 a3  ..ﾀ｣
0x0C4C9CB8  00 00 40 a5  ..@･
0x0C4C9CBC  00 00 00 a7  ...ｧ
0x0C4C9CC0  00 00 00 aa  ...ｪ
0x0C4C9CC4  00 00 c0 ab  ..ﾀｫ
0x0C4C9CC8  00 00 80 ad  ...ｭ
0x0C4C9CCC  00 00 00 af  ...ｯ
0x0C4C9CD0  00 00 c0 b0  ..ﾀｰ
0x0C4C9CD4  00 00 80 b4  ...ｴ
0x0C4C9CD8  00 00 40 b6  ..@ｶ
0x0C4C9CDC  00 00 40 b8  ..@ｸ
0x0C4C9CE0  00 00 00 ba  ...ｺ
0x0C4C9CE4  00 00 00 bc  ...ｼ
0x0C4C9CE8  00 00 00 be  ...ｾ
```

**Comment by devmiyax** [comment]
improved!

![image](https://cloud.githubusercontent.com/assets/1174152/21535003/b45e580e-cdb2-11e6-8881-4de6c7554eff.png)

**Comment by devmiyax** [comment]
![image](https://cloud.githubusercontent.com/assets/1174152/21536769/6bc696ac-cdca-11e6-80c6-a6c51caaee9f.png)

**Comment by devmiyax** [comment]
```
0,-20,351,-12,351,83,0,75
0,76,351,84,351,85,0,77
0,76,351,84,351,85,0,77
0,78,351,86,351,87,0,79
0,80,351,88,351,88,0,80
0,80,351,88,351,88,0,80
0,81,351,89,351,91,0,83
0,84,351,92,351,94,0,86
0,84,351,92,351,94,0,86
0,87,351,95,351,98,0,90
0,91,351,99,351,104,0,96
0,91,351,99,351,104,0,96
0,97,351,105,351,113,0,105
0,106,351,114,351,128,0,120
0,106,351,114,351,128,0,120
0,121,351,129,351,158,0,150
0,151,351,159,351,244,0,236
0,151,351,159,351,244,0,236
’’’

**Comment by devmiyax** [comment]
GUNGRIFFON 2 is also ok, if you have BIOS
![image](https://cloud.githubusercontent.com/assets/1174152/21542839/42ceca6e-ce04-11e6-8163-8a261e589c1b.png)

**Comment by BenjaminSiskoo** [comment]
So it works with the built in bios and a real bios ?

**Comment by devmiyax** [comment]
For GUNGRIFFON 2, a real bios is needed...

**Comment by BenjaminSiskoo** [comment]
ok
