### ISSUE TITLE
Grandia red screen

### ISSUE THREAD

**Issue by fivefeet8** [devmiyax/yabause#29]
When you launch Grandia, the game loads fine but gets stuck at a red screen after the GameArts logo animation.

**Comment by devmiyax** [comment]
![image](https://cloud.githubusercontent.com/assets/1174152/16176251/843f60e2-3644-11e6-9764-9f0f431c9254.png)

![image](https://cloud.githubusercontent.com/assets/1174152/16176253/8d8f77cc-3644-11e6-8ca0-c25f8f55bacb.png)
