### ISSUE TITLE
PANDEMONIUM                                                                                                     

### ISSUE THREAD

**Issue by devmiyax** [devmiyax/yabause#293]
version:0.3.9
device:SHIELD Android TV
cpu_type:2
video_type:1

![screenshot](http://www.uoyabause.org//system/reports/screenshots/000/002/091/original/_storage_emulated_0_yabause_screenshots_T-15914H_2016_12_30_00_11_12.png?1483085514)

**Comment by fivefeet8** [comment]
Seems to be fixed in 4.0 RC.

**Comment by devmiyax** [comment]
Now playable!

![image](https://user-images.githubusercontent.com/1174152/67688572-63dc9580-f9dd-11e9-88c2-3d1ebaa09805.png)

**Comment by corvusd** [comment]
Yet in 2.9.0 or your Dev local?

**Comment by devmiyax** [comment]
dev local yet.
it is still have a bug and not enough to be released

**Comment by devmiyax** [comment]
fixed in 1.8.0
