### ISSUE TITLE
[MegamanX 4] Yellow laser are only transparent with sprite screen. Patch proposed

### ISSUE THREAD

**Issue by FCare** [devmiyax/yabause#295]
On the first stage, yellow laser lights are only transparent with other sprite.

It seems blending shall be enabled, no only for sprite but for all other screens.

Here is a patch I tried, it seems to fix it. I do not think there might be so much of side effects.

[0001-Fix-MegamanX4-yellow-laser-transparency.patch.zip](https://github.com/devmiyax/yabause/files/699367/0001-Fix-MegamanX4-yellow-laser-transparency.patch.zip)

![mx4 current](https://cloud.githubusercontent.com/assets/14252808/21864412/fb40ce20-d841-11e6-9169-02f384ce3e6c.png)
![mx4 with patch](https://cloud.githubusercontent.com/assets/14252808/21864413/fb54571a-d841-11e6-9637-6e31cd4d4746.png)

**Comment by BenjaminSiskoo** [comment]
Tested. Improved shadows in these 2 games : Dead or Alive and Crows - The Battle Action. It seems there are no regressions.

**Comment by devmiyax** [comment]
(Vdp2Regs->CCCTL & 0x40) is the flag for transparent. I think this flag is needed. but I don't know why the light is not transparent... I'll investigate it

**Comment by FCare** [comment]
(Vdp2Regs->CCCTL & 0x40)  is the color calculation eable bit for the sprite layer, you are right. But the issue is that the way Mesh sprites are implemented in the openGL port implies that the full sprite surface is considered as opaque. On the original saturn, a mesh sprite is a mix of transparent color and opaque color. As a result, on the original saturn, we can see below screens. For openGL, it means that we always have to enable the alpha blending since the information of the mesh sprite in included in the alpha value and not in the color value (opaque/transparent). So that patch is not following the vdp2 spec due to the different mesh sprite implementation.

**Comment by FCare** [comment]
Fixed with latest patches.
