### ISSUE TITLE
[GUNGRIFFON] many flickers

### ISSUE THREAD

**Issue by devmiyax** [devmiyax/yabause#297]
![image](https://cloud.githubusercontent.com/assets/1174152/21955706/bf179068-dab3-11e6-8a20-bfcae76d918d.png)

**Comment by BenjaminSiskoo** [comment]
It seems several games has the same problem. Dead Or Alive, Virtua Fighter, etc... You can see some flickering. With UoYabause 0.2.8 no problem. With UoYabause 0.3.0, flickering appears...

**Comment by devmiyax** [comment]
I have rewritten entire rendering routine. 
http://www.youtube.com/watch?v=WVyIBiwFUMs

**Comment by BenjaminSiskoo** [comment]
Nice maybe it will fix Dead or Alive too :)
