### ISSUE TITLE
Resident Evil Rendering issues

### ISSUE THREAD

**Issue by fivefeet8** [devmiyax/yabause#3]
The scene transitions when a character moves to another point on the scene sometimes shows static or objects over backgrounds.  Polygon characters are not aligned correctly on the joints and some polygons are missing from the characters.  Most noticeable with Jill's head.  Here is a youtube video:

https://www.youtube.com/watch?v=ppgdcAGMTlg

**Comment by fivefeet8** [comment]
Update to the issue.  The missing polygons are rendering with the latest 0.1.14 revision.  Only the problem now is that the polygons are rendering weird.  They don't render correctly making some strange looking body parts and faces.  


![uoyabause_20150916_102728](https://cloud.githubusercontent.com/assets/12039585/9912810/462b8008-5c5e-11e5-81b7-763cef465111.jpg)

**Comment by devmiyax** [comment]
polygons are rendering weird
