### ISSUE TITLE
[Thunder Force V] Frame rate drops  down while shooting.

### ISSUE THREAD

**Issue by devmiyax** [devmiyax/yabause#301]
Normally it runs 60fps. But when you shoot, the frame rate drops down to 30fps.

**Comment by devmiyax** [comment]
![fb uml](https://cloud.githubusercontent.com/assets/1174152/22177715/2be3aa7a-e067-11e6-8562-da256017224a.png)

**Comment by devmiyax** [comment]
![vlcsnap-2017-01-22-05h38m07s145](https://cloud.githubusercontent.com/assets/1174152/22177734/b54ba8ee-e067-11e6-9663-b92a4437eb92.png)

**Comment by BenjaminSiskoo** [comment]
You made this schema  (CPU,VDP, VDP2) ? Good to have this kind of info :)

**Comment by devmiyax** [comment]
No frame drop on 2.7.5 with sound sync to cpu mode
![Uploading image.png…]()

**Comment by devmiyax** [comment]
![image](https://user-images.githubusercontent.com/1174152/65050632-aa80ae00-d9a2-11e9-8f59-8a359c34952b.png)
