### ISSUE TITLE
NiGHTS Into Dreams: Can't play because of donation prompt

### ISSUE THREAD

**Issue by MODUSMusic** [devmiyax/yabause#306]
Hello there,
I downloaded uoYabause and NiGHTS Into Dreams to be able to play this game on the go.
Every time I start the game, it boots, press Start, fine. Until I select my game file.
When I push A to select it, the app suddenly prompts me to donate to support the project. When I hit "No, thank you" the game stops running and the app goes back to the game selection menu, thus rendering me unable to play.

Is this an issue that only happens with NiGHTS? I've played games smaller in size, like Shining Wisdom, and I've had no problem so far.

Thanks in advance,
Paul

**Comment by devmiyax** [comment]
Hi,

It's just a crash. Please send bug report to Google play. I'll investigate
it.

2017年1月22日(日) 3:45 Paul <notifications@github.com>:
