### ISSUE TITLE
RADIANT S.G                                                                                                     

### ISSUE THREAD

**Issue by devmiyax** [devmiyax/yabause#307]
version:0.4.0beta
device:SHIELD Android TV
cpu_type:2
video_type:1

![screenshot](http://www.uoyabause.org//system/reports/screenshots/000/002/174/original/_storage_emulated_0_yabause_screenshots_T-32902G_2017_01_21_19_01_33.png?1485054182)

**Comment by fivefeet8** [comment]
Fixed with the latest 4.0 RC.
