### ISSUE TITLE
[UI] On screen keypad improvements

### ISSUE THREAD

**Issue by felclef** [devmiyax/yabause#314]
The following topics would improve the experience on every game:
 - alpha to make the on screen controls less intrusive to text and the game itself (e.g. games like Shining Force 3)
 - maybe another alpha config for "inactive input for X time" (i.e. if you don't input a touch, the alpha becomes even stronger... would help a lot on cut scenes)
 - possibility to set scale and position for each button group (i.e. D-pad, ABC, XYZ - L and R separated, for touch screen it seems to be much more viable to use them side-by-side on some games)

if someone with frontend (??) experience on android and the project give me a introduction on the matter, I can try to code a PR, but I lack experience on Android development :/

Thanks, the project is awesome!

**Comment by felclef** [comment]
Saw the alpha/opaque was implemented, yay!!

Another good improvement: stickiness on the d-pad. Sometimes, you get your finger out of the d-pad draw area. Some games keep the last input, i.e. if you were up-right and slide out, but keep the finger down, touching the screen, it still inputs up-right until touch release.

It would help a lot on games like Saturn Bomberman.

**Comment by devmiyax** [comment]
implemented
