### ISSUE TITLE
[Commits from FCare] Possible merge !!!

### ISSUE THREAD

**Issue by BenjaminSiskoo** [devmiyax/yabause#326]
Hi Devmiyax, 

https://github.com/FCare/piYabause/tree/master François made several fixes. Is it possible to merge with your fork ? No regression, just improvements :) 

Albert Odyssey : Fix transparencies problem : https://github.com/FCare/piYabause/issues/2
Detana Twinbee Yahho : Fix transparencies problem : https://github.com/FCare/piYabause/issues/18
Die Hard Arcade : Fix shadow problem : https://github.com/FCare/piYabause/issues/19
Space Harrier / Outrun : fix vertical lines : https://github.com/FCare/piYabause/issues/36
The Story Of Thor : fix dark intro : https://github.com/FCare/piYabause/issues/48
The Story Of Thor : fix shadow problem : https://github.com/FCare/piYabause/issues/49
The Story Of Thor : fix transparencies problem : https://github.com/FCare/piYabause/issues/50

Thansk by advance.

**Comment by devmiyax** [comment]
Oh, it seems good. I'll test.

**Comment by devmiyax** [comment]
I found a regression on sega logo screen. Hummm..

![image](https://cloud.githubusercontent.com/assets/1174152/22851825/f8fabd6e-f070-11e6-9cee-8a99413d268e.png)

**Comment by devmiyax** [comment]
Burning rangers no transparent effect.
![image](https://cloud.githubusercontent.com/assets/1174152/22851847/cb1c995c-f071-11e6-8112-778baecfb378.png)

**Comment by devmiyax** [comment]
I've merged piYabause to uoYabause. I do not so much test these changes though.

**Comment by BenjaminSiskoo** [comment]
Thanks, I will check.

**Comment by dankcushions** [comment]
**pi**Yabause... had me thinking it had raspberry pi GL support :) but looking through the commits I don't think so.

**Comment by FCare** [comment]
I started a port in OpenGLES2 to target RPi3. Mostly VDP1 is working but still,on Rpi, I can only get 10fps in Sega Rally. So I am evaluating now something more powerful and able to support OGLES3, like the Odroid XU4. I am developping and testing on Ubuntu right now, directly with glfw3, no qt.

Anyway, I am glad that you took my patches. I will realign on my side and check for regressions.

**Comment by dankcushions** [comment]
@FCare great work! 10fps in sega rally is a 10x improvement on Yabause software mode on an RPI3 :) maybe 2d games (saturn bomberman, etc) are playable?

If it's still possible to build the gles2 version i'd love to test!

**Comment by hooby3dfx** [comment]
@Fcare, would you consider working on a port of uoYabause to libretro (targeting the XU4)?
BTW they are on sale right now! ($59 USD) Amazing board.

**Comment by FCare** [comment]
I have one odroid xu4 already. It is a bit more expansive than 59 euros in France but you are right it is really powerful. Your request is a double one, first port yabause on odroid and then port yabause to libretto. The first one is one of my goals for the next months. The second one is a bit out of my scope. I would say, it is at low priority.
