### ISSUE TITLE
Possibility of adding a cheat code function ?

### ISSUE THREAD

**Issue by magearden** [devmiyax/yabause#328]
I admire all the work that has been put in to make this a great Sega Saturn emulator however it's missing one thing, I know that the Sega Saturn had a pro action replay for it, is it possible to add that cheat function to the emulator (I'm talking about UoYabause for Android of course) or does it already have it, if so how do I use it, also I asked this on the Yabause forums awhile back, but got no response :/ thanks.

**Comment by fivefeet8** [comment]
The latest versions have a cheat function now.

**Comment by devmiyax** [comment]
implemented
