### ISSUE TITLE
Compilation problem

### ISSUE THREAD

**Issue by BenjaminSiskoo** [devmiyax/yabause#33]
Hello, 

I can't compile Yabause, here the link with errors messages : http://pastebin.com/wur4hJyz

Keep up the good work

**Comment by BenjaminSiskoo** [comment]
Sorry all is ok. You can close it.

**Comment by devmiyax** [comment]
Nice to see you again!
This problems missmatch of qt version and the version of visual c++.

And I want to say thank you for your bug reports.
These are very helpful.
