### ISSUE TITLE
[Sonic 3D Blast] 68000 Core problem...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [devmiyax/yabause#330]
A weird bug occurs with 68000 core.

- Launch Yabause.
- Choose c68k core
- Launch Sonic 3D Blast, the game is working.
- Choose now Musashi interface.
- Close Yabause.
- Launch again Yabause.
- Launch Sonic 3D Blast and you'll get Yabause freezes after pushing start to the intro video.

Invalid opcode fault's  ?

**Comment by FCare** [comment]
Some findings: In the interpreterExec function (sh2int.c file), if you comment the usage of sh2idle function, this error does not anymore and the console is outputing an invalid opcode trace. Maybe the sh2idle function is not friendly with invalid opcode.... The global question is what is the benifit of such an idle loop detection code like this...
