### ISSUE TITLE
[Regression] 0.3.9 --> 0.4.2

### ISSUE THREAD

**Issue by BenjaminSiskoo** [devmiyax/yabause#332]
Left Picture : UoYabause 0.4.2
Right Picture : UoYabause 0.3.9

Black screen, no boot.

![aloneinthedark](https://cloud.githubusercontent.com/assets/12481242/23016017/4b79baf0-f435-11e6-9241-f0c50b74d066.JPG)

**Comment by BenjaminSiskoo** [comment]
Seifuku Densetsu fighter. Missing shadow with 0.4.2.

[T-15001G_000.zip](https://github.com/devmiyax/yabause/files/982966/T-15001G_000.zip)

**Comment by FCare** [comment]
I am working on this regression. I have seen in yabause.c file that managemenet of HBLANK VBLANK is a bit buggy. I have a local patch that I still need to test on many games and I will document it, then I will share. On the first games I tried like Alone In the Dark 1, the games are booting well. It seems also to fix some bad ghost screens like the one we can see in Sega Rally. Hopefully, I will push the patch tonight.

**Comment by BenjaminSiskoo** [comment]
Great :)
