### ISSUE TITLE
[Contra - Legacy Of War] Missing screen...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [devmiyax/yabause#333]
![contra-ecranmanquant](https://cloud.githubusercontent.com/assets/12481242/23017527/ed7c4746-f43a-11e6-98bd-2a7ab865cce0.JPG)

**Comment by BenjaminSiskoo** [comment]
UoYabause 0.5.2 commit 4106 :  same problem

**Comment by BenjaminSiskoo** [comment]
Same problem with Yaba Sanshiro 1.3.0 RC

**Comment by BenjaminSiskoo** [comment]
Same problem with Yaba Sanshiro 2.3.1

**Comment by BenjaminSiskoo** [comment]
Same problem with Yaba 3.2 b2

**Comment by BenjaminSiskoo** [comment]
Same problem with Yaba 3.2.4

**Comment by devmiyax** [comment]
sprite

**Comment by devmiyax** [comment]
![image](https://user-images.githubusercontent.com/1174152/172001289-3a4faecd-1531-48c9-87e2-bca0d3b5d967.png)

**Comment by BenjaminSiskoo** [comment]
Fixed Yaba 1.9.0

**Comment by fafling** [comment]
It's in fact an issue with erase/write being done outside of the coordinates registers EWLR end EWRR, see [https://github.com/FCare/Kronos/issues/90#issuecomment-1159453127](https://github.com/FCare/Kronos/issues/90#issuecomment-1159453127) (explanation in french).
