### ISSUE TITLE
Shield TV: yellow striped screen on boot

### ISSUE THREAD

**Issue by Roet-Ivar** [devmiyax/yabause#338]
I'm using the Nvidia Shield TV and the latest Yabause libretro-core for android.
All I ever see when trying to boot anything on the emulator is a frozen yellow striped screen.
The core information shows BIOS present.

Any idea what's going on?

EDIT: Maybe this question should be asked on libretro repo?

**Comment by fivefeet8** [comment]
You probably should.  This is not the Libretro port.  This version of Android Yabause has an OpenGL ES3 render path.

**Comment by devmiyax** [comment]
Ask libretoro guys
