### ISSUE TITLE
[Shining the Holy Hark] Some Issues on android version

### ISSUE THREAD

**Issue by Loontz** [devmiyax/yabause#34]
Hi ! First of all, thank you for your wonderful emulator (and sorry for my bad english in advance) This version works fine, awesome FPS make it great ^^ But there's some graphic issues in Shining the Holy Ark RPG :

- Whole texts appears to be black. It's managable, but a little bit disturbing.
- Map is fully black. It seems to be the same issues as the text, but it looks like it's "transparent". You simply can't read it.

I hope those informations will allow you to fix it. ^^

Thanks again for your work, your emulator is really refreshing :-)

Regards !

**Comment by Loontz** [comment]
For the records, I played the EUR version of the game in an HTC M8 and an Nvidia Shield Tablet (lollipop version). Even if it's differents devices, same bugs appears. Hope it could help.

**Comment by devmiyax** [comment]
![image](https://cloud.githubusercontent.com/assets/1174152/12011905/439d7c8e-ad25-11e5-8c74-14fee62b3620.png)

**Comment by devmiyax** [comment]
![image](https://cloud.githubusercontent.com/assets/1174152/12012163/3a211164-ad2c-11e5-80fa-18c9b3c8c1d7.png)

**Comment by devmiyax** [comment]
![image](https://cloud.githubusercontent.com/assets/1174152/12012250/f689049e-ad2f-11e5-971f-17327968d212.png)

**Comment by devmiyax** [comment]
![image](https://cloud.githubusercontent.com/assets/1174152/12012271/638569fc-ad30-11e5-909d-796ac98de0dc.png)

**Comment by devmiyax** [comment]
![image](https://cloud.githubusercontent.com/assets/1174152/12012315/f3469358-ad31-11e5-9c3b-f89422ceef04.png)

magic color is white.

**Comment by devmiyax** [comment]
![image](https://cloud.githubusercontent.com/assets/1174152/12012392/3cebacca-ad35-11e5-94fc-1baffe333cd2.png)

**Comment by BenjaminSiskoo** [comment]
Nice progress...
