### ISSUE TITLE
Games do not boot

### ISSUE THREAD

**Issue by GITEMUFAN11** [devmiyax/yabause#340]
I have a Samsung Galaxy S5 on marshmallow 6.0.1 and since 0.4.0 to the current 0.4.3 as of now Games like Sonic R do not boot at all i just get a blank screen i tried to submit error report but the emulator freezes when i go to submit. It boots when using software renderer instead of open gl but then the game is very slow and unplayable

**Comment by mhaze618** [comment]
Same here

**Comment by devmiyax** [comment]
@GITEMUFAN11  Still happend? can I close this issue?

**Comment by devmiyax** [comment]
no respond
