### ISSUE TITLE
Shining Force 3 Spell Effects

### ISSUE THREAD

**Issue by fivefeet8** [devmiyax/yabause#342]
The spell effects do not render correctly later in the game.  When I load my earlier save files, the spells render fine, but now that I'm near the end of Scenario 1, all the spell effects are not rendering correctly.

![_storage_emulated_0_yabause_screenshots_mk-81383_2017_03_15_00_23_49](https://cloud.githubusercontent.com/assets/12039585/23937667/e1982ffe-0915-11e7-9d9e-4ad4873c1fb8.png)

**Comment by fivefeet8** [comment]
Update:  It seems this issue is popping up on the battle outside Aspia later in the game.  Once I passed on to the next town, the spell effects are good again.  Strange.

**Comment by fivefeet8** [comment]
Update:  The same rendering issue pops back up again in the cave battle afterwards.

**Comment by VictorianTech** [comment]
Did you ever find a fix for this? I'm getting a similar issue in Scenario 1. I first fixed it by changing version of Yabause emulator to an earlier one. Now it's happening again.

**Comment by devmiyax** [comment]
![image](https://user-images.githubusercontent.com/1174152/162560287-50a6c62a-5c12-4cfa-9592-519f995727a9.png)
![image](https://user-images.githubusercontent.com/1174152/162560299-eabf188a-4389-4292-b74d-b77896268c2c.png)
no issue in 1.8.0
