### ISSUE TITLE
Dracula X Background

### ISSUE THREAD

**Issue by fivefeet8** [devmiyax/yabause#343]
There are lines on the background images in this scene.  That was the only weird thing I noticed so far.  The rest of the game runs and looks amazing.

![_storage_emulated_0_yabause_screenshots_t-9527g_2017_03_18_12_46_24](https://cloud.githubusercontent.com/assets/12039585/24075712/9fab9700-0bdd-11e7-9ad3-4f01dda6ece9.png)

**Comment by fivefeet8** [comment]
Same issue on 0.5.3a

**Comment by devmiyax** [comment]
@fivefeet8 Can you check this issue still be happened? 
I think it may be fixed by another commit.

**Comment by fivefeet8** [comment]
Seems to be fixed.  I'm not sure with rev though.
