### ISSUE TITLE
Astal 

### ISSUE THREAD

**Issue by fivefeet8** [devmiyax/yabause#344]
You can only see the moving background on stage 2 level 2.  All foreground elements including the character are hidden behind.  The game runs great otherwise, but you can't get past this stage.  You can hear Astal, but you can't see him.

![_storage_emulated_0_yabause_screenshots_mk-81019_2017_03_18_14_56_00](https://cloud.githubusercontent.com/assets/12039585/24076355/640e8fa0-0beb-11e7-89b5-315367e5f556.png)

**Comment by fivefeet8** [comment]
Same issue on 0.5.3a

**Comment by devmiyax** [comment]
works fine on 2.7.5
![image](https://user-images.githubusercontent.com/1174152/65366026-d37e9880-dc59-11e9-8ed6-f517d9b7bbd9.png)
![image](https://user-images.githubusercontent.com/1174152/65366032-de392d80-dc59-11e9-8dce-8fe9c3b17411.png)
