### ISSUE TITLE
DRAGON BALL Z LA GRANDE LEGENDE DES BOULES DE CRISTAL                                                           

### ISSUE THREAD

**Issue by devmiyax** [devmiyax/yabause#345]
version:0.4.4
device:SM-G900V
cpu_type:2
video_type:1
I greatly appreciate your efforts and what you have done. This game is mostly playable, however in the main menu you can see that the game mode selection isn't highlighted. It is impossible to see what you are choosing. Game: Dragon Ball Z The Legend (French/Euro). Device: Samsung Galaxy S5
Thank you!
![screenshot](http://www.uoyabause.org//system/reports/screenshots/000/002/486/original/_storage_emulated_0_yabause_screenshots_T-13301H_2017_03_18_11_35_22.png?1489851323)

**Comment by FCare** [comment]
Normally, this is fixed now. This issue shall be closed.

**Comment by devmiyax** [comment]
works fine
![image](https://user-images.githubusercontent.com/1174152/65367816-83f89680-dc72-11e9-8c24-324325cfe198.png)
