### ISSUE TITLE
OUTRUN                                                                                                          

### ISSUE THREAD

**Issue by devmiyax** [devmiyax/yabause#350]
version:0.4.4
device:SHIELD Tablet
cpu_type:0
video_type:1
running a a good speed but  missing some roadside graphics and no sound.

![screenshot](http://www.uoyabause.org//system/reports/screenshots/000/002/529/original/_storage_emulated_0_yabause_screenshots_GS-9110_2017_03_30_21_49_18.png?1490907001)

**Comment by FCare** [comment]
From what I've seen in my past research on this topic is that the game is using the second screen for priority calculation. But I did not dig more into details here.

**Comment by devmiyax** [comment]
Runs perfectly on 2.7.5

![image](https://user-images.githubusercontent.com/1174152/65050101-d2234680-d9a1-11e9-9d2f-e442fb7d1176.png)
