### ISSUE TITLE
Sound problem with games.

### ISSUE THREAD

**Issue by BenjaminSiskoo** [devmiyax/yabause#352]
Burning Rangers - volume is low.
Deep Fear - missing SFX.
Die Hard Arcade - missing music in game.
Savaki - music working. Sound problem with voices of the audience.
Space Harrier - missing sound when you push start button on the main menu.

**Comment by BenjaminSiskoo** [comment]
Pro Yakyuu Greatest Nine '96 - music and sound are not good.

**Comment by BenjaminSiskoo** [comment]
3D Baseball - In game, problem with voices (crackles)

**Comment by BenjaminSiskoo** [comment]
Blam Machinehead, sound it too high

**Comment by BenjaminSiskoo** [comment]
Blazing Dragon - Sound is messy in game.

**Comment by BenjaminSiskoo** [comment]
Burning rangers - sound problem in the menu

**Comment by BenjaminSiskoo** [comment]
Kuro No Danshou - The Literary Fragment - sound problem

**Comment by BenjaminSiskoo** [comment]
Mortal Kombat : sound problem between each new round.

**Comment by acidmanifesto** [comment]
Guardian Heroes: Constant cracking ticking sound
