### ISSUE TITLE
[Tomb Raider (E)] Polygons problems and black band....

### ISSUE THREAD

**Issue by BenjaminSiskoo** [devmiyax/yabause#356]
UoYabause 0.4.6 

There are some polygons with the face of Lara and her breast. Black band on the left of the screen.

![tombraider](https://cloud.githubusercontent.com/assets/12481242/25575592/1dba418a-2e59-11e7-8fd8-bf1ed8551078.JPG)

**Comment by paul-met** [comment]
The black bar on the left is not an emulation bug. The strip can only be removed with the help of a special hack.
![capture_001_04052017_232730](https://cloud.githubusercontent.com/assets/13948032/25723592/4e2c3858-3121-11e7-9dc1-940adfc0c9ad.png)

**Comment by devmiyax** [comment]
Before
![image](https://user-images.githubusercontent.com/1174152/28245712-ffef1cae-6a47-11e7-92ca-2a866d6045db.png)

After
![image](https://user-images.githubusercontent.com/1174152/28245707-e936d376-6a47-11e7-8c2d-f76b8fd66647.png)

**Comment by devmiyax** [comment]
regression since
8a80de298ee030bedd511e115c1dca3c3b77c5bd

**Comment by BenjaminSiskoo** [comment]
Fixed UoYabause 0.5.2
