### ISSUE TITLE
Opengles 2.0 support

### ISSUE THREAD

**Issue by objectchris** [devmiyax/yabause#36]
Hi! Is it possible to include opengles 2.0 support for older android devices? eg, the Ouya. Thanks :)

**Comment by devmiyax** [comment]
I've been try it for a few years.. But I couldn't find a way to emulate the 'per pixel priority' function which is essential of the Sega Saturn GPU emulation using OpenGL ES 2.0. OpenGL ES 3.0 can read and write gl_FragDepth which make it possible to emulate 'per pixel priority'.

**Comment by dankcushions** [comment]
it looks like there's an extension gl_ext_frag_depth that might work as an alternative on a few GLES 2.0 devices but none that I wanted :P http://delphigl.de/glcapsviewer/gles_listreports.php?extension=GL_EXT_frag_depth

Oh well, thanks so much for trying anyway!

**Comment by devmiyax** [comment]
Sorry I can't
