### ISSUE TITLE
Xmen Vs SF Crashes to CD player

### ISSUE THREAD

**Issue by fivefeet8** [devmiyax/yabause#360]
Launching the game will get past the Capcom logo, then crash to the cd player menu.

Ver. 0.4.6
Shield TV 5.0.1 
Android 7

**Comment by devmiyax** [comment]
50% of boot success rate

![image](https://user-images.githubusercontent.com/1174152/44952839-91ef4400-aec4-11e8-81e0-61b41553506f.png)
![image](https://user-images.githubusercontent.com/1174152/44952842-a0d5f680-aec4-11e8-96f5-379b77e58461.png)

**Comment by devmiyax** [comment]
Bad color in game 
![image](https://user-images.githubusercontent.com/1174152/44952918-01b1fe80-aec6-11e8-9fe8-ef529b11ed56.png)

**Comment by devmiyax** [comment]
![image](https://user-images.githubusercontent.com/1174152/44955556-28852a80-aef0-11e8-9951-17dc1f1a2695.png)

**Comment by devmiyax** [comment]
Freezes

![image](https://user-images.githubusercontent.com/1174152/44955689-6c792f00-aef2-11e8-96a2-9262cd8870ca.png)

**Comment by devmiyax** [comment]
Master CPU Infinity loop

```
0x06023FF0: mov.l @r14, r0  (r14= 0x0600A820)
0x06023FF2: tst r0,r0
0x06023FF4: bt 0x0602400E
0x06023FF6: ldc r1, sr
0x06023FF8: nop
0x06023FFA: ldc r2, sr
0x06023FFC: nop
0x06023FFE: nop
0x06024000: bra 0x06023FF0
```

**Comment by devmiyax** [comment]
Slave CPU Infinity loop

```
0x060163CC: mov.b @r1, r0
0x060163CE: tst r0, r0
0x060163D0: bf 0x060163CC
```

**Comment by devmiyax** [comment]
ScuRegs->IMS = 0xfffff037

**Comment by FCare** [comment]
Devmiyax, this seems so promising :-) Can you please share all your findings on a dev branch? It can help to understand what was working bad and to test which games are improved now :-)

**Comment by devmiyax** [comment]
Please wait I'm fixing some regressions.

**Comment by FCare** [comment]
Ok, thanks for update. If you need help, do not hesitate :-)

**Comment by devmiyax** [comment]
The terrible thing has happened in my prefecture in the last weekend. there was no power supply for the whole weekend.

https://edition.cnn.com/2018/09/09/asia/japan-earthquake-death-toll/index.html

**Comment by FCare** [comment]
Oh! Yes, I saw this in news... I was not aware you are living in north of japan. I often travel to Tokyo area, it is always a risk we have in mind when going to Japan. Hopefully, you are safe. I hope all your familly and friends are safe too...
