### ISSUE TITLE
Marvel Super Heroes vs SF crashes to CD player

### ISSUE THREAD

**Issue by fivefeet8** [devmiyax/yabause#361]
The game would load to ingame albeit with rendering issues before.  Now after the character license screen, it crashes to the Saturn CD player.  

Ver.  0.4.6
Shield TV 5.0.1
Android 7

**Comment by devmiyax** [comment]
Can boot 1/2
![image](https://user-images.githubusercontent.com/1174152/67146427-fc7c6280-f2c5-11e9-9b39-05337a0a3e80.png)

**Comment by devmiyax** [comment]
Sound is broken while playing
![image](https://user-images.githubusercontent.com/1174152/67146503-a4922b80-f2c6-11e9-9fc0-f67e405121e7.png)

**Comment by devmiyax** [comment]
fixed at 1.8.0
