### ISSUE TITLE
[Tsuukai !! Slot Shooting ] Transparencies problem...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [devmiyax/yabause#368]
![tsukai](https://cloud.githubusercontent.com/assets/12481242/26713742/777fd378-476e-11e7-902a-45f148253786.jpg)

**Comment by BenjaminSiskoo** [comment]
Same problem with Yaba Sanshiro 2.3.1

**Comment by BenjaminSiskoo** [comment]
Same problem with Yaba 3.2 b2

**Comment by BenjaminSiskoo** [comment]
Same problem with Yaba 3.2.4

**Comment by devmiyax** [comment]
![image](https://user-images.githubusercontent.com/1174152/162562715-bdd8690b-de94-4641-ab1d-32b83303c461.png)
no issue in 1.8.0
