### ISSUE TITLE
[Die Hard Trilogy (E)] Game freeze in Sega licence screen

### ISSUE THREAD

**Issue by corvusd** [devmiyax/yabause#369]
I do not have how add information to improve in this bug.
Check in uoyabause 0.4.6 Windows version.

**Comment by devmiyax** [comment]
![Screenshot_20190918-073022](https://user-images.githubusercontent.com/1174152/65086919-92368080-d9ee-11e9-9a84-5e8c25f2f074.png)
works on 2.7.5

**Comment by corvusd** [comment]
For me not work. What config are used? BIOS? SH2 Interpreter?

**Comment by BenjaminSiskoo** [comment]
Same for windows, just a black screen at the start

**Comment by corvusd** [comment]
Some new @devmiyax how can run it in yabashanshiro?

**Comment by metallic77** [comment]
Hangs on Yabasanshiro standalone (Windows).
