### ISSUE TITLE
[Athlete Kings] Green shadow...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [devmiyax/yabause#383]
UoYabause 0.5.0.

Green shadow on the long jump.

![athlete kings shadow](https://user-images.githubusercontent.com/12481242/27583821-01405620-5b36-11e7-84d1-0df25015cb67.JPG)

**Comment by BenjaminSiskoo** [comment]
UoYabause 0.5.2 : same problem

**Comment by BenjaminSiskoo** [comment]
After UoYabause 0.5.2 , this game doesn't boot.

**Comment by devmiyax** [comment]
fixed on 2.7.5
![image](https://user-images.githubusercontent.com/1174152/65155534-7079df80-da68-11e9-9af8-1d4476ce4683.png)
