### ISSUE TITLE
[M (emu) Kimo Wo Tsutaete] Missing background...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [devmiyax/yabause#391]
UoYabause 0.5.0
![m_emu](https://user-images.githubusercontent.com/12481242/27760826-d6672410-5e50-11e7-9bc1-1c11d9b4fd89.JPG)

**Comment by BenjaminSiskoo** [comment]
UoYabause 0.5.2 : same problem

**Comment by BenjaminSiskoo** [comment]
UoYabause 0.5.2 commit 4105 : same problem

**Comment by devmiyax** [comment]
Vdp1Regs->EWDR	0x8000	unsigned short
The frame buffer is cleared by black color.

**Comment by devmiyax** [comment]
Sprite Window is enabled.
0x8000 should be transparent.

**Comment by devmiyax** [comment]
![image](https://user-images.githubusercontent.com/1174152/28998962-9e702208-7a72-11e7-8557-c5301c282947.png)
