### ISSUE TITLE
[Tomb Raider] Missing background (Start menu)...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [devmiyax/yabause#398]
![tombraider](https://user-images.githubusercontent.com/12481242/28307320-d2568b22-6ba2-11e7-9e8c-1297feb56e71.JPG)

**Comment by paul-met** [comment]
What is the regional version of Tomb raider? USA version of the game does not want to run at all on uoYabause 0.5.2 - the emulator crashes for me.

**Comment by BenjaminSiskoo** [comment]
I tried U version and it worked. Do you have a bin+cue game ? 

Try this : 

Delete all UoYabause/Yabause folder/directories from your computer.
don't forget this folder : C:\Users\yournameuser\AppData\Local\yabause.
Download UoYabause 0.5.2, unzip it, setting up and try again Tomb Raider :)

**Comment by paul-met** [comment]
Yes, deleting the settings file helped, thanks.

**Comment by BenjaminSiskoo** [comment]
Good to hear that. Since several builds, Yabause.ini seems touchy :)
