### ISSUE TITLE
Bilinear Filtering for 3d games

### ISSUE THREAD

**Issue by fivefeet8** [devmiyax/yabause#400]
This is more a feature request than a bug report.  Is it possible to include Bilinear Filtering for 3d games?  Or is there some technical issue with using this for the Saturn's Quad rendering?

**Comment by Merlkir** [comment]
Isn't it there already? At least for non native rendering resolutions I think I can turn it on.

**Comment by fivefeet8** [comment]
Currently, the filtering doesn't hit 3d polygons like what you see on psx emulators like epsxe.

**Comment by devmiyax** [comment]
FXAA and Tessellation is implemented.
