### ISSUE TITLE
Sound Cuts Out

### ISSUE THREAD

**Issue by DarkSki** [devmiyax/yabause#401]
Seems to be loosing sound when saving or loading a save game.

This happens with pretty much all the games I have tried on this.

This is one of the main reasons I don't game on this all the time.

Please take a look and see what your magic coding skills can accomplish !!!

**Comment by DarkSki** [comment]
Does anyone else encounter this issue?

It seems to happen almost every time you save and is one of few actual issues left with this great fork of yabause.

I will donate again if we can get this fixed somehow !

**Comment by fivefeet8** [comment]
I don't have issues with saving with the ingame saving options per the game, but I do have sound going out when I bring up the ingame menu for anything.  Using savestates, loading savestates, enabling/disable cheats, etc.... will mute the sound.

**Comment by DarkSki** [comment]
That is much better explained and exactly the issue I experienced with all my devices.

Most of the time you save your game and that's all it takes. This also occurs with both sound engines as well.

Does anyone know what causes this , I haven't noticed this issue with Saturn.emu.

**Comment by fivefeet8** [comment]
It's most likely a bug with recent code changes to the CPU dynarec and audio sync.

**Comment by DarkSki** [comment]
This has actually been happening for a very long time.
I can see the update come out today for a fix with this.
I have already thrown a donation your way, I'll test this out and let you know the results but so far so good.

**Comment by devmiyax** [comment]
Sorry for my late reply. I have been busy in July.

**Comment by fivefeet8** [comment]
Seems to be fixed in the latest release.
