### ISSUE TITLE
[Asuka 100%] Missing background...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [devmiyax/yabause#408]
UoYabause 0.5.2 commit 4105.

![asuka](https://user-images.githubusercontent.com/12481242/28995455-c1862ad2-79e9-11e7-8d4f-a7187c445d4c.JPG)

**Comment by devmiyax** [comment]
fix confrim and redression check

![image](https://user-images.githubusercontent.com/1174152/28995725-ca83f596-7a2b-11e7-81fb-cc80bb16ce7d.png)
![image](https://user-images.githubusercontent.com/1174152/28995731-ee0ba6f8-7a2b-11e7-9e6a-4eb15dec9b7d.png)
![image](https://user-images.githubusercontent.com/1174152/28995735-025898e6-7a2c-11e7-8053-96ae42a1ba28.png)
