### ISSUE TITLE
[Breakpoint Tennis] Missing background...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [devmiyax/yabause#409]
UoYabause 0.5.2 commit 4105 : 

![breakpointtennis](https://user-images.githubusercontent.com/12481242/28995486-b468bd82-79ea-11e7-96f4-a0b336903e72.JPG)

**Comment by devmiyax** [comment]
![image](https://user-images.githubusercontent.com/1174152/28995769-e1d0d3a8-7a2c-11e7-9a6b-512eb3154099.png)

fixed by eaa21bb9968f995b93191d71ea186a47ead7a49d
