### ISSUE TITLE
[Digital Pinball] Small regression.

### ISSUE THREAD

**Issue by BenjaminSiskoo** [devmiyax/yabause#41]
Left Picture : Yabause 08.02.2015
Right Picture : Yabause 08.15.2015

Black square on the the ball.

![digital_pinball_devmiyax_08 0 15 2015](https://cloud.githubusercontent.com/assets/12481242/9288556/a1217f7e-434c-11e5-8e7c-379a99bf9fe6.PNG)

**Comment by BenjaminSiskoo** [comment]
Problem stills exists with Yabause 2015.11.22

**Comment by BenjaminSiskoo** [comment]
Regression with rev 2959-2960

![truepinball](https://cloud.githubusercontent.com/assets/12481242/11766646/f024b106-a191-11e5-9612-a01f7b52d023.PNG)

**Comment by BenjaminSiskoo** [comment]
Slight improvement on the menu between Yabause Devmiyax 12.25.2015 and Yabause Devmiyax 12.29.2015.
![digital_pinball_menu](https://cloud.githubusercontent.com/assets/12481242/12035043/bebde96c-ae38-11e5-9e0b-1ec8956c4351.PNG)

**Comment by devmiyax** [comment]
![image](https://cloud.githubusercontent.com/assets/1174152/12046301/f8af1378-aef9-11e5-98c8-98c5e976d105.png)

**Comment by BenjaminSiskoo** [comment]
Perfect, the menu still perfect now too :) Thank you
