### ISSUE TITLE
Increase Internal Memory Card

### ISSUE THREAD

**Issue by fivefeet8** [devmiyax/yabause#411]
This is more a feature request, but there is also an issue related with it.  

It seems that the external memcard gets erased or needs to be reformatted when a new version of the emulator gets released.  I've lost hours of gameplay because of this.  However, the internal memcard contents seem to be ok on new releases. 

Can the emulated internal memory card space be increased substantially?  That way we can get more save games onto it without needing to use the external card.

**Comment by devmiyax** [comment]
There is no fact that a new version crashes external card data. Just a emulation bug destroy save data. I wish you report the detail how and when save data is destroyed.

Anyway, SSF has this this feature. I think I can imitate it.

**Comment by fivefeet8** [comment]
The saves I had didn't get erased after the last minor update, but they did get erased when going from 0.4.x to 0.5.x.  Normally the first game I run after an erase will require me to format the external card before using it again.  I'll post a new ticket for the issue when the next update also erases my saves.

**Comment by fivefeet8** [comment]
My external card saves just got deleted on 0.5.3a  After I changed the Dynarec CPU to Interpreter, then loaded a save state, my external card needed to be reformatted again.  I had also changed my bios from Japan 1.01 to EUR 1.00.  Fortunately, I had no important game saves on it.

**Comment by devmiyax** [comment]
Thank you for your detail information.
I found that internal backup data is included in the state save data. I think that's the cause of this problem. 
I gonna fix it.

**Comment by devmiyax** [comment]
Now internal memory 8MByte!

![image](https://user-images.githubusercontent.com/1174152/29486675-b7fb9d88-8526-11e7-80d3-3cb1df70c062.png)

**Comment by BenjaminSiskoo** [comment]
No problem with savetates ?

**Comment by fivefeet8** [comment]
Awesome!!!

**Comment by devmiyax** [comment]
it seems it works fine.
401(block) * 80(byte per block) * 25= 802,000

![image](https://user-images.githubusercontent.com/1174152/29492280-bef02dee-85b1-11e7-934a-f505f58cc5e7.png)

But I found several existing bugs like #412 #413 and now I'm fixing. if you know any other existing bugs, please let me know.

**Comment by derklk** [comment]
Awesome!!!
