### ISSUE TITLE
[Cyberbots Full Metal Madness] Can't read save data

### ISSUE THREAD

**Issue by devmiyax** [devmiyax/yabause#413]
When Cartridge  is None.

![image](https://user-images.githubusercontent.com/1174152/29491872-4dd532c4-85a4-11e7-8950-9c98189280b1.png)

**Comment by BenjaminSiskoo** [comment]
After removing DRAM 32 Bits, these games have a message : 

Dungeons & Dragons +  Vampire Savior

![dungeons](https://user-images.githubusercontent.com/12481242/29493230-d3849ce6-8592-11e7-842f-1179ce351a04.JPG)

Metal Slug : 

![metalslug](https://user-images.githubusercontent.com/12481242/29493229-d381a14e-8592-11e7-8be4-a4d62ccf4a65.JPG)

**Comment by devmiyax** [comment]
works fine on 2.7.5

![image](https://user-images.githubusercontent.com/1174152/65368016-582ae000-dc75-11e9-91de-913366d31f4a.png)
