### ISSUE TITLE
Dragon Force 2 opcode Error

### ISSUE THREAD

**Issue by fivefeet8** [devmiyax/yabause#415]
Dragon Force 2 will throw an Opcode Error but continue running.  When you enter a battle the screen will remain black, but music will continue to play.  This is on the new Dynarec CPU and Interpreter.

**Comment by devmiyax** [comment]
works fine v2.7.5

![image](https://user-images.githubusercontent.com/1174152/65366346-a3d18f80-dc5d-11e9-9e3d-21e1245ecc93.png)
