### ISSUE TITLE
uoYabause (V116_0.5.5_170827_R) crash on NVidia Shield TV 2017 (SW Version 5.2)

### ISSUE THREAD

**Issue by yaymuffins** [devmiyax/yabause#419]
Hello

The app seem to crash once sideloaded from the apk on the site (http://www.uoyabause.org/static_pages/download)

As Google Play removed the download, I can't try installing from it.

Here the logcat: https://pastebin.com/raw/f8j2kJVf

**Comment by devmiyax** [comment]
my shield TV works fine now
