### ISSUE TITLE
Shining Force 3 Scenario 2 MASTER SH2 INVALID OPCODE

### ISSUE THREAD

**Issue by hmsq82** [devmiyax/yabause#422]
![yaba sanshiro_20170910_191717](https://user-images.githubusercontent.com/14012410/30251829-6e16a448-965f-11e7-8eae-332ad0ad671c.png)

Getting this error on the image I have not sure if it is the image I've source from the Japanese game.

**Comment by devmiyax** [comment]
@hmsq82  let me know the step for this issue.

**Comment by devmiyax** [comment]
can not reproduce

**Comment by Joedloutre** [comment]
Hello, I have the same problem. 

:( 
![error](https://github.com/devmiyax/yabause/assets/158306841/332980f2-432d-4362-a421-a63f78018e01)
