### ISSUE TITLE
EARTHWORM JIM 2                                 EARTHWORM JIM 2                                                 

### ISSUE THREAD

**Issue by devmiyax** [devmiyax/yabause#437]
version:1.0.3
device:SHIELD Android TV
cpu_type:3
video_type:1
comment:flickering graphics
[state file](http://www.uoyabause.org//system/reports/state_files/000/003/148/original/T-13203H_2017_10_08_21_49_28.zip)
![screenshot](http://www.uoyabause.org//system/reports/screenshots/000/003/148/original/screenshot.png?1507524574)

**Comment by Aethyrion** [comment]
version:2.5.Alpha-c2b09d
Windows 10
US version of Earthworm Jim 2

Sprites are still flickering using OpenGL renderer (not with software renderer).

**Comment by devmiyax** [comment]
dupe #308
