### ISSUE TITLE
SHINING FORCE 3 SCENARIO 1      OHTO NO KYOSHIN for PAL ver.                                                    

### ISSUE THREAD

**Issue by devmiyax** [devmiyax/yabause#439]
version:1.0.3a
device:SHIELD Android TV
cpu_type:3
video_type:1
comment:spell graphics 
[state file](http://www.uoyabause.org//system/reports/state_files/000/003/157/original/MK-81383_2017_10_10_00_00_34.zip)
![screenshot](http://www.uoyabause.org//system/reports/screenshots/000/003/157/original/screenshot.png?1507618843)

**Comment by devmiyax** [comment]
Anyone who has reference?

**Comment by fivefeet8** [comment]
I can get a better image from my Shield TV if it isn't good enough.  This is the heal spell.

**Comment by devmiyax** [comment]
it works fine on windows version, but not on Android version. 

![image](https://user-images.githubusercontent.com/1174152/31844080-97e4b4f8-b631-11e7-855f-3a4f49466216.png)

**Comment by devmiyax** [comment]
scu	: DSP executing: PC = FC

DSP DMA03 read addr=0601FD60 cnt= 243 add = 2

DSP DMA03 read addr=0605E82C cnt= 4 add = 2

DSP DMA03 read addr=0605E7FC cnt= 4 add = 2

DSP DMA03 read addr=0605E7FC cnt= 4 add = 2

DSP DMA03 read addr=0605E80C cnt= 4 add = 2

DSP DMA03 read addr=0605E81C cnt= 4 add = 2

DSP DMA03 read addr=0605E83C cnt= 4 add = 2

DSP DMA04 write addr=0605E7FC cnt= 4 add = 2 sel=1

DSP DMA03 read addr=0605E82C cnt= 4 add = 2

DSP DMA03 read addr=0605E84C cnt= 4 add = 2

DSP DMA04 write addr=0605E80C cnt= 4 add = 2 sel=1

DSP DMA03 read addr=0605E85C cnt= 4 add = 2

DSP DMA04 write addr=0605E81C cnt= 4 add = 2 sel=1

DSP DMA03 read addr=0605E86C cnt= 4 add = 2

DSP DMA04 write addr=0605E82C cnt= 4 add = 2 sel=1

Memory accesses on SCU DSP

scu	: wrote 000080FC to DSP Program Control Port
scu	: DSP set pc = FC
scu	: wrote 000080FC to DSP Program Control Port
scu	: DSP set pc = FC
scu	: wrote 00010000 to DSP Program Control Port
scu	: DSP executing: PC = FC
DSP DMA03 read addr=0602012C cnt= 256 add = 2
DSP DMA01 read addr=0605E6FC cnt= 64 add = 2
DSP DMA03 read addr=0605E7FC cnt= 4 add = 2
DSP DMA03 read addr=0605E80C cnt= 4 add = 2
DSP DMA02 write addr=25C58800 cnt= 48 add = 1
DSP DMA02 write addr=25C588C0 cnt= 48 add = 1
DSP DMA03 read addr=0605E81C cnt= 4 add = 2
DSP DMA02 write addr=25C58980 cnt= 48 add = 1
DSP DMA02 write addr=25C58A40 cnt= 48 add = 1
DSP DMA02 write addr=25C58B00 cnt= 48 add = 1
DSP DMA03 read addr=0605E82C cnt= 4 add = 2
DSP DMA02 write addr=25C58BC0 cnt= 48 add = 1
DSP DMA02 write addr=25C58C80 cnt= 48 add = 1
DSP DMA02 write addr=25C58D40 cnt= 48 add = 1
DSP DMA03 read addr=0605E7FC cnt= 4 add = 2
DSP DMA02 write addr=25C58E00 cnt= 48 add = 1
DSP DMA02 write addr=25C58EC0 cnt= 48 add = 1
DSP DMA04 write addr=25C58F80 cnt= 32 add = 1 sel=0
dsp has ended

**Comment by devmiyax** [comment]
DSP does not start on Android

**Comment by devmiyax** [comment]
scu	: wrote 000080FC to DSP Program Control Port
scu	: DSP set pc = FC
Scu read 00000080
scu	: wrote 000080FC to DSP Program Control Port
scu	: DSP set pc = FC
scu	: wrote 00010000 to DSP Program Control Port
scu	: DSP executing: PC = FC
DSP DMA03 read addr=0602012C cnt= 256 add = 2
read from 0602012C to P[0] val 00050000
read from 06020130 to P[1] val 00050000
read from 06020134 to P[2] val 00050000
read from 06020138 to P[3] val 00050000
read from 0602013C to P[4] val 00050000
read from 06020140 to P[5] val 00050000
read from 06020144 to P[6] val 00050000
read from 06020148 to P[7] val 00050000
read from 0602014C to P[8] val 00050000
read from 06020150 to P[9] val 00050000
read from 06020154 to P[10] val 00050000
read from 06020158 to P[11] val 00050000
read from 0602015C to P[12] val 00050000
read from 06020160 to P[13] val 00050000
read from 06020164 to P[14] val 00050000
read from 06020168 to P[15] val 00050000
read from 0602016C to P[16] val 00050000
read from 06020170 to P[17] val 00050000
read from 06020174 to P[18] val 00050000
read from 06020178 to P[19] val 00050000
read from 0602017C to P[20] val 00050000
read from 06020180 to P[21] val 00050000
read from 06020184 to P[22] val 00050000
read from 06020188 to P[23] val 00050000
read from 0602018C to P[24] val 00050000
read from 06020190 to P[25] val 00050000
read from 06020194 to P[26] val 00050000
read from 06020198 to P[27] val 00050000
read from 0602019C to P[28] val 00050000
read from 060201A0 to P[29] val 00050000
read from 060201A4 to P[30] val 00050000
read from 060201A8 to P[31] val 00050000
read from 060201AC to P[32] val 00050000
read from 060201B0 to P[33] val 00050000
read from 060201B4 to P[34] val 00050000
read from 060201B8 to P[35] val 00050000
read from 060201BC to P[36] val 00050000
read from 060201C0 to P[37] val 00050000
read from 060201C4 to P[38] val 00050000
read from 060201C8 to P[39] val 00050000
read from 060201CC to P[40] val 00050000
read from 060201D0 to P[41] val 00050000
read from 060201D4 to P[42] val 00050000
read from 060201D8 to P[43] val 00050000
read from 060201DC to P[44] val 00050000
read from 060201E0 to P[45] val 00050000
read from 060201E4 to P[46] val 00050000
read from 060201E8 to P[47] val 00050000
read from 060201EC to P[48] val 00050000
read from 060201F0 to P[49] val 00050000
read from 060201F4 to P[50] val 00050000
read from 060201F8 to P[51] val 00050000
read from 060201FC to P[52] val 00050000
read from 06020200 to P[53] val 00050000
read from 06020204 to P[54] val 00050000
read from 06020208 to P[55] val 00050000
read from 0602020C to P[56] val 00050000
read from 06020210 to P[57] val 00050000
read from 06020214 to P[58] val 00050000
read from 06020218 to P[59] val 00050000
read from 0602021C to P[60] val 00050000
read from 06020220 to P[61] val 00050000
read from 06020224 to P[62] val 00050000
read from 06020228 to P[63] val 00050000
read from 0602022C to P[64] val 00050000
read from 06020230 to P[65] val 00050000
read from 06020234 to P[66] val 00050000
read from 06020238 to P[67] val 00050000
read from 0602023C to P[68] val 00050000
read from 06020240 to P[69] val 00050000
read from 06020244 to P[70] val 00050000
read from 06020248 to P[71] val 00050000
read from 0602024C to P[72] val 00050000
read from 06020250 to P[73] val 00050000
read from 06020254 to P[74] val 00050000
read from 06020258 to P[75] val 00050000
read from 0602025C to P[76] val 00050000
read from 06020260 to P[77] val 00050000
read from 06020264 to P[78] val 00050000
read from 06020268 to P[79] val 00050000
read from 0602026C to P[80] val 00050000
read from 06020270 to P[81] val 00050000
read from 06020274 to P[82] val 00050000
read from 06020278 to P[83] val 00050000
read from 0602027C to P[84] val 00050000
read from 06020280 to P[85] val 00050000
read from 06020284 to P[86] val 00050000
read from 06020288 to P[87] val 00050000
read from 0602028C to P[88] val 00050000
read from 06020290 to P[89] val 00050000
read from 06020294 to P[90] val 00050000
read from 06020298 to P[91] val 00050000
read from 0602029C to P[92] val 00050000
read from 060202A0 to P[93] val 00050000
read from 060202A4 to P[94] val 00050000
read from 060202A8 to P[95] val 00050000
read from 060202AC to P[96] val 00050000
read from 060202B0 to P[97] val 00050000
read from 060202B4 to P[98] val 00050000
read from 060202B8 to P[99] val 00050000
read from 060202BC to P[100] val 00050000
read from 060202C0 to P[101] val 00050000
read from 060202C4 to P[102] val 00050000
read from 060202C8 to P[103] val 00050000
read from 060202CC to P[104] val 00050000
read from 060202D0 to P[105] val 00050000
read from 060202D4 to P[106] val 00050000
read from 060202D8 to P[107] val 00050000
read from 060202DC to P[108] val 00050000
read from 060202E0 to P[109] val 00050000
read from 060202E4 to P[110] val 00050000
read from 060202E8 to P[111] val 00050000
read from 060202EC to P[112] val 00050000
read from 060202F0 to P[113] val 00050000
read from 060202F4 to P[114] val 00050000
read from 060202F8 to P[115] val 00050000
read from 060202FC to P[116] val 00050000
read from 06020300 to P[117] val 00050000
read from 06020304 to P[118] val 00050000
read from 06020308 to P[119] val 00050000
read from 0602030C to P[120] val 00050000
read from 06020310 to P[121] val 00050000
read from 06020314 to P[122] val 00050000
read from 06020318 to P[123] val 00050000
read from 0602031C to P[124] val 00050000
read from 06020320 to P[125] val 00050000
read from 06020324 to P[126] val 00050000
read from 06020328 to P[127] val 00050000
read from 0602032C to P[128] val 00050000
read from 06020330 to P[129] val 00050000
read from 06020334 to P[130] val 00050000
read from 06020338 to P[131] val 00050000
read from 0602033C to P[132] val 00050000
read from 06020340 to P[133] val 00050000
read from 06020344 to P[134] val 00050000
read from 06020348 to P[135] val 00050000
read from 0602034C to P[136] val 00050000
read from 06020350 to P[137] val 00050000
read from 06020354 to P[138] val 00050000
read from 06020358 to P[139] val 00050000
read from 0602035C to P[140] val 00050000
read from 06020360 to P[141] val 00050000
read from 06020364 to P[142] val 00050000
read from 06020368 to P[143] val 00050000
read from 0602036C to P[144] val 00050000
read from 06020370 to P[145] val 00050000
read from 06020374 to P[146] val 00050000
read from 06020378 to P[147] val 00050000
read from 0602037C to P[148] val 00050000
read from 06020380 to P[149] val 00050000
read from 06020384 to P[150] val 00050000
read from 06020388 to P[151] val 00050000
read from 0602038C to P[152] val 00050000
read from 06020390 to P[153] val 00050000
read from 06020394 to P[154] val 00050000
read from 06020398 to P[155] val 00050000
read from 0602039C to P[156] val 00050000
read from 060203A0 to P[157] val 00050000
read from 060203A4 to P[158] val 00050000
read from 060203A8 to P[159] val 00050000
read from 060203AC to P[160] val 00050000
read from 060203B0 to P[161] val 00050000
read from 060203B4 to P[162] val 00050000
read from 060203B8 to P[163] val 00050000
read from 060203BC to P[164] val 00050000
read from 060203C0 to P[165] val 00050000
read from 060203C4 to P[166] val 00050000
read from 060203C8 to P[167] val 00050000
read from 060203CC to P[168] val 00050000
read from 060203D0 to P[169] val 00050000
read from 060203D4 to P[170] val 00050000
read from 060203D8 to P[171] val 00050000
read from 060203DC to P[172] val 00050000
read from 060203E0 to P[173] val 00050000
read from 060203E4 to P[174] val 00050000
read from 060203E8 to P[175] val 00050000
read from 060203EC to P[176] val 00050000
read from 060203F0 to P[177] val 00050000
read from 060203F4 to P[178] val 00050000
read from 060203F8 to P[179] val 00050000
read from 060203FC to P[180] val 00050000
read from 06020400 to P[181] val 00050000
read from 06020404 to P[182] val 00050000
read from 06020408 to P[183] val 00050000
read from 0602040C to P[184] val 00050000
read from 06020410 to P[185] val 00050000
read from 06020414 to P[186] val 00050000
read from 06020418 to P[187] val 00050000
read from 0602041C to P[188] val 00050000
read from 06020420 to P[189] val 00050000
read from 06020424 to P[190] val 00050000
read from 06020428 to P[191] val 00050000
read from 0602042C to P[192] val 00050000
read from 06020430 to P[193] val 00050000
read from 06020434 to P[194] val 00050000
read from 06020438 to P[195] val 00050000
read from 0602043C to P[196] val 00050000
read from 06020440 to P[197] val 00050000
read from 06020444 to P[198] val 00050000
read from 06020448 to P[199] val 00050000
read from 0602044C to P[200] val 00050000
read from 06020450 to P[201] val 00050000
read from 06020454 to P[202] val 00050000
read from 06020458 to P[203] val 00050000
read from 0602045C to P[204] val 00050000
read from 06020460 to P[205] val 00050000
read from 06020464 to P[206] val 00050000
read from 06020468 to P[207] val 00050000
read from 0602046C to P[208] val 00050000
read from 06020470 to P[209] val 00050000
read from 06020474 to P[210] val 00050000
read from 06020478 to P[211] val 00050000
read from 0602047C to P[212] val 00050000
read from 06020480 to P[213] val 00050000
read from 06020484 to P[214] val 00050000
read from 06020488 to P[215] val 00050000
read from 0602048C to P[216] val 00050000
read from 06020490 to P[217] val 00050000
read from 06020494 to P[218] val 00050000
read from 06020498 to P[219] val 00050000
read from 0602049C to P[220] val 00050000
read from 060204A0 to P[221] val 00050000
read from 060204A4 to P[222] val 00050000
read from 060204A8 to P[223] val 00050000
read from 060204AC to P[224] val 00050000
read from 060204B0 to P[225] val 00050000
read from 060204B4 to P[226] val 00050000
read from 060204B8 to P[227] val 00050000
read from 060204BC to P[228] val 00050000
read from 060204C0 to P[229] val 00050000
read from 060204C4 to P[230] val 00050000
read from 060204C8 to P[231] val 00050000
read from 060204CC to P[232] val 00050000
read from 060204D0 to P[233] val 00050000
read from 060204D4 to P[234] val 00050000
read from 060204D8 to P[235] val 00050000
read from 060204DC to P[236] val 00050000
read from 060204E0 to P[237] val 00050000
read from 060204E4 to P[238] val 00050000
read from 060204E8 to P[239] val 00050000
read from 060204EC to P[240] val 00050000
read from 060204F0 to P[241] val 00050000
read from 060204F4 to P[242] val 00050000
read from 060204F8 to P[243] val 00050000
read from 060204FC to P[244] val 00050000
read from 06020500 to P[245] val 00050000
read from 06020504 to P[246] val 00050000
read from 06020508 to P[247] val 00050000
read from 0602050C to P[248] val 00050000
read from 06020510 to P[249] val 00050000
read from 06020514 to P[250] val 00050000
read from 06020518 to P[251] val 00050000
read from 0602051C to P[252] val 00050000
read from 06020520 to P[253] val 00050000
read from 06020524 to P[254] val 00050000
read from 06020528 to P[255] val 00050000
DSP DMA01 read addr=0604DED0 cnt= 64 add = 2

read from 0604DED0 to [3][0] val 00000101
read from 0604DED4 to [3][1] val 02020303
read from 0604DED8 to [3][2] val 04040505
read from 0604DEDC to [3][3] val 06060707
read from 0604DEE0 to [3][4] val 08080909
read from 0604DEE4 to [3][5] val 0A0A0B0B
read from 0604DEE8 to [3][6] val 0C0C0D0D
read from 0604DEEC to [3][7] val 0E0E0F0F
read from 0604DEF0 to [3][8] val 10101111
read from 0604DEF4 to [3][9] val 12121313
read from 0604DEF8 to [3][10] val 14141515
read from 0604DEFC to [3][11] val 16161717
read from 0604DF00 to [3][12] val 18181919
read from 0604DF04 to [3][13] val 1A1A1B1B
read from 0604DF08 to [3][14] val 1C1C1D1D
read from 0604DF0C to [3][15] val 1E1E1F1F
read from 0604DF10 to [3][16] val 20202121
read from 0604DF14 to [3][17] val 22222323
read from 0604DF18 to [3][18] val 24242525
read from 0604DF1C to [3][19] val 26262727
read from 0604DF20 to [3][20] val 28282929
read from 0604DF24 to [3][21] val 2A2A2B2B
read from 0604DF28 to [3][22] val 2C2C2D2D
read from 0604DF2C to [3][23] val 2E2E2F2F
read from 0604DF30 to [3][24] val 30303131
read from 0604DF34 to [3][25] val 32323333
read from 0604DF38 to [3][26] val 34343535
read from 0604DF3C to [3][27] val 36363737
read from 0604DF40 to [3][28] val 38383939
read from 0604DF44 to [3][29] val 3A3A3B3B
read from 0604DF48 to [3][30] val 3C3C3D3D
read from 0604DF4C to [3][31] val 3E3E0000
read from 0604DF50 to [3][32] val 00000000
read from 0604DF54 to [3][33] val 42424343
read from 0604DF58 to [3][34] val 44444545
read from 0604DF5C to [3][35] val 46464747
read from 0604DF60 to [3][36] val 48484949
read from 0604DF64 to [3][37] val 4A4A4B4B
read from 0604DF68 to [3][38] val 4C4C4D4D
read from 0604DF6C to [3][39] val 4E4E4F4F
read from 0604DF70 to [3][40] val 50505151
read from 0604DF74 to [3][41] val 52525353
read from 0604DF78 to [3][42] val 54545555
read from 0604DF7C to [3][43] val 56565757
read from 0604DF80 to [3][44] val 58585959
read from 0604DF84 to [3][45] val 5A5A5B5B
read from 0604DF88 to [3][46] val 5C5C5D5D
read from 0604DF8C to [3][47] val 5E5E5F5F
read from 0604DF90 to [3][48] val 60606161
read from 0604DF94 to [3][49] val 62626363
read from 0604DF98 to [3][50] val 64646565
read from 0604DF9C to [3][51] val 66666767
read from 0604DFA0 to [3][52] val 68686969
read from 0604DFA4 to [3][53] val 6A6A6B6B
read from 0604DFA8 to [3][54] val 6C6C6D6D
read from 0604DFAC to [3][55] val 6E6E6F6F
read from 0604DFB0 to [3][56] val 70707171
read from 0604DFB4 to [3][57] val 72727373
read from 0604DFB8 to [3][58] val 74747575
read from 0604DFBC to [3][59] val 76767777
read from 0604DFC0 to [3][60] val 78787979
read from 0604DFC4 to [3][61] val 7A7A7B7B
read from 0604DFC8 to [3][62] val 7C7C7D7D
read from 0604DFCC to [3][63] val 7E7E7F7F
DSP DMA03 read addr=0604DCF8 cnt= 4 add = 2
read from 0604DCF8 to [2][0] val 00000000
read from 0604DCFC to [2][1] val 01990000
read from 0604DD00 to [2][2] val 03330000
read from 0604DD04 to [2][3] val 00000000
DSP DMA03 read addr=0604DD08 cnt= 4 add = 2
read from 0604DD08 to [2][0] val 06660000
read from 0604DD0C to [2][1] val 19980000
read from 0604DD10 to [2][2] val 1FFF0000
read from 0604DD14 to [2][3] val 09990000
DSP DMA02 write addr=25C6D200 cnt= 48 add = 1
DSP DMA02 write addr=25C6D2C0 cnt= 48 add = 1
DSP DMA03 read addr=0604DD18 cnt= 4 add = 2
read from 0604DD18 to [2][0] val 06660000
read from 0604DD1C to [2][1] val 0CCC0000
read from 0604DD20 to [2][2] val 13320000
read from 0604DD24 to [2][3] val 09990000
DSP DMA02 write addr=25C6D380 cnt= 48 add = 1
DSP DMA02 write addr=25C6D440 cnt= 48 add = 1
DSP DMA02 write addr=25C6D500 cnt= 48 add = 1
DSP DMA03 read addr=0604DD28 cnt= 4 add = 2
read from 0604DD28 to [2][0] val 00000000
read from 0604DD2C to [2][1] val 0CCC0000
read from 0604DD30 to [2][2] val 09990000
read from 0604DD34 to [2][3] val 00000000
DSP DMA02 write addr=25C6D5C0 cnt= 48 add = 1
DSP DMA02 write addr=25C6D680 cnt= 48 add = 1
DSP DMA02 write addr=25C6D740 cnt= 48 add = 1
DSP DMA02 write addr=25C6D800 cnt= 48 add = 1
DSP DMA02 write addr=25C6D8C0 cnt= 48 add = 1
DSP DMA04 write addr=25C6D980 cnt= 32 add = 1 sel=0
dsp has ended
Scu read 00000080

**Comment by devmiyax** [comment]
```
scu: write 00000030:00000000 @ 06010434
scu: write 00000024:060C8000 @ 06010440
scu: write 0000002C:00000101 @ 06010442
scu: write 00000034:01000007 @ 06010444
scu: write 00000030:00000101 @ 0601045C
scu: read  0000007C @ 06017286
scu: write 00000000:0603D340 @ 0601729A
scu: write 00000004:25C64300 @ 0601729C
scu: write 00000008:00000300 @ 0601729E
scu: write 0000000C:00000101 @ 060172A0
scu: write 00000014:00000007 @ 060172A4
scu: write 00000010:00000101 @ 060172AC
scu: write 00000088:00000062 @ 06014E96
scu: write 0000008C:0181373E @ 06014EB4
scu: write 0000008C:018137B4 @ 06014EC8
scu: write 0000008C:00000000 @ 06014EE0
scu: write 0000008C:00000001 @ 06014EEA
scu: write 0000008C:00000004 @ 06014EF6
scu: write 0000008C:00000004 @ 06014F02
scu: write 0000008C:00000000 @ 06014F0C
scu: write 0000008C:00000000 @ 06014F16
scu: write 0000008C:00000004 @ 06014F20
scu: write 0000008C:00000004 @ 06014F2C
scu: write 0000008C:00000004 @ 06014F36
scu: write 0000008C:00000010 @ 06014F40
scu: write 0000008C:0971B480 @ 06014F54
scu: write 0000008C:00000400 @ 06014F5C
scu: write 0000008C:00001000 @ 06014F66
scu: write 00000088:0000003E @ 06014CF8
scu: write 0000008C:0180804B @ 06014CFE
scu: write 0000008C:00000100 @ 06014D00
scu: write 00000080:000080FC @ 06014CC6
scu: wrote 000080FC to DSP Program Control Port
scu: DSP set pc = FC
```

**Comment by devmiyax** [comment]
```
0x06015594: bt 0x060155CE
0x06015592: tst r1, r1
0x06015590: mov.l @(0x008, r2), r1  // <-- here/ fail when r1 = 3
0x0601558E: mov r9, r2
0x0601558C: mov.l @(0x0B4, pc), r9 ; 0x06015640
0x0601558A: mov #0x1F, r3
0x06015588: mov #0x00, r8
0x06015586: ldc r0, sr
0x06015584: or #0xF0, r0
0x06015582: stc sr, r0
0x06015580: sts.l pr, @-r15
0x0601557E: mov.l r9, @-r15
0x0601557C: mov.l r8, @-r15
```

**Comment by devmiyax** [comment]
```
scu: write 00000088:00000000 @ 06014D6A
scu: wrote 00000000 to DSP Data Ram Address Port 20
scu: write 0000008C:018179FF @ 06014D88
scu: wrote 018179FF to DSP Data Ram Data Port Page 0 offset 00
scu: write 0000008C:01817A0B @ 06014DA0
scu: wrote 01817A0B to DSP Data Ram Data Port Page 0 offset 01
scu: write 0000008C:018179FF @ 06014DB8
scu: wrote 018179FF to DSP Data Ram Data Port Page 0 offset 02
scu: write 0000008C:FFFFFFFF @ 06014DBC
scu: wrote FFFFFFFF to DSP Data Ram Data Port Page 0 offset 03
scu: write 0000008C:00000001 @ 06014DC6
scu: wrote 00000001 to DSP Data Ram Data Port Page 0 offset 04
scu: write 0000008C:01817A0F @ 06014DDA
scu: wrote 01817A0F to DSP Data Ram Data Port Page 0 offset 05
scu: write 0000008C:FFFFFFFF @ 06014DDE
scu: wrote FFFFFFFF to DSP Data Ram Data Port Page 0 offset 06
scu: write 0000008C:FFFFFFFF @ 06014DE2
scu: wrote FFFFFFFF to DSP Data Ram Data Port Page 0 offset 07
scu: write 0000008C:00000004 @ 06014DEC
scu: wrote 00000004 to DSP Data Ram Data Port Page 0 offset 08
scu: write 0000008C:00000004 @ 06014DF6
scu: wrote 00000004 to DSP Data Ram Data Port Page 0 offset 09
scu: write 00000088:0000003E @ 06014CF8
scu: wrote 0000003E to DSP Data Ram Address Port 20
scu: write 0000008C:01807F58 @ 06014CFE
scu: wrote 01807F58 to DSP Data Ram Data Port Page 0 offset 3E
scu: write 0000008C:000000F3 @ 06014D00
scu: wrote 000000F3 to DSP Data Ram Data Port Page 0 offset 3F
scu: write 00000080:000080FC @ 06014CC6
scu: wrote 000080FC to DSP Program Control Port
scu: DSP set pc = FC
scu: write 00000084:00001C3E @ 06014CD6
scu: wrote 00001C3E to DSP Program ram offset FC
scu: write 00000084:00003604 @ 06014CD6
scu: wrote 00003604 to DSP Program ram offset FD
scu: write 00000084:C0012400 @ 06014CD6
scu: wrote C0012400 to DSP Program ram offset FE
scu: write 00000084:B0000000 @ 06014CD6
scu: wrote B0000000 to DSP Program ram offset FF
scu: write 00000084:00021D23 @ 06014CD6
scu: wrote 00021D23 to DSP Program ram offset 00
scu: write 00000084:00803501 @ 06014CD6
scu: wrote 00803501 to DSP Program ram offset 01
scu: write 00000084:08000000 @ 06014CD6
scu: wrote 08000000 to DSP Program ram offset 02
scu: write 00000084:D30800CF @ 06014CD6
scu: wrote D30800CF to DSP Program ram offset 03
scu: write 00000084:00001D00 @ 06014CD6
scu: wrote 00001D00 to DSP Program ram offset 04
scu: write 00000084:00020000 @ 06014CD6
scu: wrote 00020000 to DSP Program ram offset 05
scu: write 00000084:94008420 @ 06014CD6
scu: wrote 94008420 to DSP Program ram offset 06
scu: write 00000084:08040000 @ 06014CD6
scu: wrote 08040000 to DSP Program ram offset 07
scu: write 00000084:3C040000 @ 06014CD6
scu: wrote 3C040000 to DSP Program ram offset 08
scu: write 00000084:3C040000 @ 06014CD6
scu: wrote 3C040000 to DSP Program ram offset 09
scu: write 00000084:08043109 @ 06014CD6
scu: wrote 08043109 to DSP Program ram offset 0A
scu: write 00000084:94010000 @ 06014CD6
scu: wrote 94010000 to DSP Program ram offset 0B
scu: read  00000080 @ 06010B64
scu: write 00000080:000080FC @ 06010B82
scu: wrote 000080FC to DSP Program Control Port
scu: DSP set pc = FC
scu: write 00000080:00010000 @ 06010B8C
scu: wrote 00010000 to DSP Program Control Port
scu: DSP executing: PC = FC
DSP DMA03 read addr=0601FD60 cnt= 243 add = 2
```

**Comment by devmiyax** [comment]
BAD

scu: DSP executing: PC = FC
mem: 06028048:00000003 @ 06015180(M)
scu: dsp 00001C3E @ 000000FC
scu: dsp 00003604 @ 000000FD
scu: dsp 00021D23 @ 00000000
scu: dsp 00803501 @ 00000001
scu: dsp 08000000 @ 00000002
scu: dsp D30800CF @ 00000003
scu: dsp 00001D00 @ 00000004
scu: dsp F0000000 @ 000000CF
dsp has ended

Good

scu: DSP executing: PC = FC
mem: 06028048:00000003 @ 06015180(M)
scu: dsp 00001C3E @ 000000FC
scu: dsp 00003604 @ 000000FD
scu: dsp C0012400 @ 000000FE
DSP DMA03 read addr=0601FD60 cnt= 243 add = 2
