### ISSUE TITLE
[Feature] FPS counter is not displayed.

### ISSUE THREAD

**Issue by BenjaminSiskoo** [devmiyax/yabause#45]
FPS counter is not working with OpenGL renderer.

**Comment by fivefeet8** [comment]
The FPS counter seems to render fine on my Shield Tablet and TV with OpenGL.  Is it not rendering or is the FPS counter not actually changing?  It seems to on my devices.

**Comment by BenjaminSiskoo** [comment]
The problem is from the Windows port. But thanks for your answer :)

**Comment by BenjaminSiskoo** [comment]
Work with nanovg OSD Interface. And not working with Software Interface.
