### ISSUE TITLE
Battle Arena Toshinden Remix                                                                                    

### ISSUE THREAD

**Issue by devmiyax** [devmiyax/yabause#454]
version:1.0.4
device:SHIELD Android TV
cpu_type:3
video_type:1
comment:transprent fighters in this stage
[state file](http://www.uoyabause.org//system/reports/state_files/000/003/184/original/MK-81029V1..000___2017_10_16_22_30_24.zip)
![screenshot](http://www.uoyabause.org//system/reports/screenshots/000/003/184/original/screenshot.png?1508185832)

**Comment by qingan1996** [comment]
@devmiyax 
Hey, pal!
I can't submit a localized Chinese string
Trouble you to extract it from my branch

**Comment by devmiyax** [comment]
no issue 1.8.0
![image](https://user-images.githubusercontent.com/1174152/162563152-2d650bc1-9c2e-4880-9d01-57cb11f04f76.png)
