### ISSUE TITLE
[Street Fighter Zero 3] puases game

### ISSUE THREAD

**Issue by devmiyax** [devmiyax/yabause#46]
![image](https://cloud.githubusercontent.com/assets/1174152/9430186/8f7b2c94-4a26-11e5-8b19-b0f7a7610d7e.png)

**Comment by devmiyax** [comment]
fixed by
https://github.com/devmiyax/yabause/commit/9f79ab71d4e5578cbf28afb13641c0065750c2ad

**Comment by fivefeet8** [comment]
Did this fix get released with 01.17c version?  I'd love to get this game and Megaman X4 running properly.
