### ISSUE TITLE
[Sword & Sorcery] Freeze on the loading screen...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [devmiyax/yabause#460]
UoYabause 0.5.6

**Comment by BenjaminSiskoo** [comment]
Fixed with Yaba Sanshiro 2.5 Alpha

**Comment by paul-met** [comment]
At last the game is playable. But there are errors in the priorities of the layers.
![x](https://user-images.githubusercontent.com/13948032/56920483-ff8f5680-6acb-11e9-9c7f-77b079b2ad4a.png)
