### ISSUE TITLE
[Langrisser 3] Missing character in game...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [devmiyax/yabause#462]
UoYabause 0.5.6 : 
 
![ss_langrisser3](https://user-images.githubusercontent.com/12481242/32222236-c009e6ba-be38-11e7-839d-e922ff0e04a6.JPG)

Mednaffen : 
![ss_langrisser3_ssf1](https://user-images.githubusercontent.com/12481242/32222239-c85d906e-be38-11e7-9f14-da9ab4a6a6b3.JPG)

**Comment by BenjaminSiskoo** [comment]
Yaba Sanshiro 1.7.0. Same problem.

**Comment by BenjaminSiskoo** [comment]
Same problem with Yaba Sanshiro 2.2.0

**Comment by devmiyax** [comment]
state file
[state.zip](https://github.com/devmiyax/yabause/files/3638376/state.zip)

**Comment by devmiyax** [comment]
???

![image](https://user-images.githubusercontent.com/1174152/65368806-9d084400-dc80-11e9-9952-8ffeedc60fa8.png)

**Comment by BenjaminSiskoo** [comment]
It works
