### ISSUE TITLE
DIGITAL MONSTER                                                                                                 

### ISSUE THREAD

**Issue by devmiyax** [devmiyax/yabause#466]
version:1.0.5
device:SM-G9350
cpu_type:3
video_type:2
comment:Some problems with the sound
[state file](http://www.uoyabause.org//system/reports/state_files/000/003/228/original/T-13331G_2017_10_28_23_29_33.zip)
![screenshot](http://www.uoyabause.org//system/reports/screenshots/000/003/228/original/screenshot.png?1509204587)

**Comment by Arekuxis** [comment]
Mine shows only a black screen and it won't start. Any workarounds needed?

**Comment by devmiyax** [comment]
works fine v 2.7.5

![image](https://user-images.githubusercontent.com/1174152/65368847-20299a00-dc81-11e9-98a8-53393928fbac.png)
