### ISSUE TITLE
[Sega Rally] Crash when second stage is started.

### ISSUE THREAD

**Issue by devmiyax** [devmiyax/yabause#47]
F/libc    ( 8777): Fatal signal 7 (SIGBUS), code 1, fault addr 0xf711f739 in tid 13195 (yabause.android)
I/DEBUG   (  220): **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* ***
I/DEBUG   (  220): Build fingerprint: 'NVIDIA/foster_e_hdd/foster:5.1/LMY47D/32494_566.2783:user/release-keys'
I/DEBUG   (  220): Revision: '0'
I/DEBUG   (  220): ABI: 'arm'
I/DEBUG   (  220): pid: 8777, tid: 13195, name: yabause.android  >>> org.uoyabause.android <<<
I/DEBUG   (  220): signal 7 (SIGBUS), code 1 (BUS_ADRALN), fault addr 0xf711f739
I/DEBUG   (  220):     r0 f77af77a  r1 f795f795  r2 0000003f  r3 00000001
I/DEBUG   (  220):     r4 f711f711  r5 7c7fb000  r6 7c400000  r7 f77af77b
I/DEBUG   (  220):     r8 424000c0  r9 407c1ad4  sl 0000000f  fp 00008000
I/DEBUG   (  220):     ip 00000000  sp 7b0fbb98  lr 4079ab39  pc 4078d57c  cpsr a0030030
I/DEBUG   (  220):
I/DEBUG   (  220): backtrace:
I/DEBUG   (  220):     #00 pc 0004257c  /system/lib/libc.so (je_arena_dalloc_bin_locked+399)
I/DEBUG   (  220):     #01 pc 0004fb35  /system/lib/libc.so (je_tcache_bin_flush_small+240)
I/DEBUG   (  220):     #02 pc 0004fd45  /system/lib/libc.so (je_tcache_event_hard+52)
I/DEBUG   (  220):     #03 pc 0004a485  /system/lib/libc.so (ifree+688)
I/DEBUG   (  220):     #04 pc 00012dc7  /system/lib/libc.so (free+10)
I/DEBUG   (  220):     #05 pc 000a585c  /data/app/org.uoyabause.android-1/lib/arm/libyabause_native.so (invalidate_page+88)
I/DEBUG   (  220):     #06 pc 000a5b24  /data/app/org.uoyabause.android-1/lib/arm/libyabause_native.so (invalidate_blocks+540)
I/DEBUG   (  220):     #07 pc 000a5e14  /data/app/org.uoyabause.android-1/lib/arm/libyabause_native.so (invalidate_addr+168)
I/DEBUG   (  220):     #08 pc 000c2d04  /data/app/org.uoyabause.android-1/lib/arm/libyabause_native.so (WriteInvalidateWord+40)

**Comment by BenjaminSiskoo** [comment]
It seems to work. No crash on the second race (Arcade mode)
