### ISSUE TITLE
Fix Linux build

### ISSUE THREAD

**Issue by raelgc** [devmiyax/yabause#470]
Sorry, I cannot create another Yabause fork (I'm helping to apply Yabause changes to libretro).

So, below are the changes to fix uoYabause compile process in Linux:

## 1. yprintf is not present on Unix too:

At `vidogl.c` line `48`, replace this:

```
#ifdef _WINDOWS
int yprintf(const char * fmt, ...)
{
  static FILE * dbugfp = NULL;
  if (dbugfp == NULL) {
    dbugfp = fopen("debug.txt", "w");
  }
  if (dbugfp) {
    va_list ap;
    va_start(ap, fmt);
    vfprintf(dbugfp, fmt, ap);
    va_end(ap);
    fflush(dbugfp);
  }
  return 0;
}

void OSDPushMessageDirect(char * msg) {
}

#endif
```

with this:

```
#ifndef ANDROID
int yprintf(const char * fmt, ...)
{
  static FILE * dbugfp = NULL;
  if (dbugfp == NULL) {
    dbugfp = fopen("debug.txt", "w");
  }
  if (dbugfp) {
    va_list ap;
    va_start(ap, fmt);
    vfprintf(dbugfp, fmt, ap);
    va_end(ap);
    fflush(dbugfp);
  }
  return 0;
}
#endif

#ifdef _WINDOWS
void OSDPushMessageDirect(char * msg) {
}
#endif
```

## 2. Remove duplicate getCpuId

In `thr-linux.c` line `356`, there are 2 `getCpuId` definitions (just remove one of them):

```
#include <sys/syscall.h>
//...
int getCpuId() {

    unsigned cpu;
    if (syscall(__NR_getcpu, &cpu, NULL, NULL) < 0) {
        return -1;
    } else {
        return (int) cpu;
    }
}

#include <sys/syscall.h>
//...
int getCpuId() {

    unsigned cpu;
    if (syscall(__NR_getcpu, &cpu, NULL, NULL) < 0) {
        return -1;
    } else {
        return (int) cpu;
    }
}
```

**Comment by FCare** [comment]
You can look at FCare/uoyabause. It is my fork targeting linux. It has the fixes from devmyiax.

**Comment by raelgc** [comment]
Yeap, it worked. I'm just pointing that with the 2 above fixes, this repo works too.

**Comment by raelgc** [comment]
@cyberconan Can you, please, create a PR with this?

**Comment by LeCharlatan** [comment]
Compiled on Antergos but kind of useless since openning options and clicking "Ok" button makes Yaba Sanchiro (Qt) crashes whatever you change settings or not :/

**Comment by devmiyax** [comment]
merged
