### ISSUE TITLE
[Blam Machinehead] 3 GFX problems...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [devmiyax/yabause#476]
Yaba Sanshiro 1.2.2

![1blam](https://user-images.githubusercontent.com/12481242/34340009-5fbb6062-e97c-11e7-8b19-f3ce373a3965.JPG)
![1scorcher2](https://user-images.githubusercontent.com/12481242/34340018-7aa6beee-e97c-11e7-9fe6-1777586655a3.JPG)

**Comment by BenjaminSiskoo** [comment]
![1scorcher1](https://user-images.githubusercontent.com/12481242/34340022-8a369af0-e97c-11e7-805e-0ca907bedc16.JPG)
![1sorcheryabtransition](https://user-images.githubusercontent.com/12481242/34340023-8a53feba-e97c-11e7-8677-951645cdbfe7.JPG)

**Comment by BenjaminSiskoo** [comment]
![1sorcheryabpause](https://user-images.githubusercontent.com/12481242/34340027-9f4c9052-e97c-11e7-9a38-25e0d01cfa72.JPG)

![1scorcher3](https://user-images.githubusercontent.com/12481242/34340026-9f21671a-e97c-11e7-9ee1-f06c3998f7a8.JPG)

**Comment by devmiyax** [comment]
![image](https://user-images.githubusercontent.com/1174152/35021145-e7c70b52-fb72-11e7-9b65-f4b235c34d8e.png)

**Comment by BenjaminSiskoo** [comment]
Yaba Sanshiro 1.30 RC 01.17.2018 (Windows port) : not fixed to me
