### ISSUE TITLE
Issue on capcom generation volume 3

### ISSUE THREAD

**Issue by FCare** [devmiyax/yabause#477]
Background screen has disappeared.
Issue was not present before color ram optimzation.

**Comment by BenjaminSiskoo** [comment]
Here a picture : 

![1capcomgeneration3](https://user-images.githubusercontent.com/12481242/34408804-2df864f2-ebc6-11e7-87d1-1d38243ce6d9.JPG)

**Comment by devmiyax** [comment]
fixed on 1.3.0
![image](https://user-images.githubusercontent.com/1174152/35020000-3bcb9868-fb6d-11e7-87ed-3330466b0a92.png)

**Comment by BenjaminSiskoo** [comment]
Fixed
