### ISSUE TITLE
[Dead or Alive] missing polygon

### ISSUE THREAD

**Issue by devmiyax** [devmiyax/yabause#48]
![image](https://cloud.githubusercontent.com/assets/1174152/9566000/ffd3e706-4f2b-11e5-9c19-fd4da43f6749.png)

**Comment by devmiyax** [comment]
Fixed

![image](https://cloud.githubusercontent.com/assets/1174152/9699097/7374aa0a-540f-11e5-901a-7464d8139b67.png)

**Comment by fivefeet8** [comment]
This change may have affected the missing polygon problem with Resident Evil as well.

https://github.com/devmiyax/yabause/issues/3
