### ISSUE TITLE
Yaba Sanshiro 1.2.2 --> Yaba Sanshiro 1.30 RC regression.

### ISSUE THREAD

**Issue by BenjaminSiskoo** [devmiyax/yabause#487]
Resident Evil : black screen at the start. It seems it doesn't boot.

**Comment by BenjaminSiskoo** [comment]
Blam machine head : 

![1blammachinehead](https://user-images.githubusercontent.com/12481242/34650497-01264452-f3ba-11e7-852f-98f7c16eb3d0.JPG)

**Comment by BenjaminSiskoo** [comment]
Astal : Black screen.

**Comment by BenjaminSiskoo** [comment]
Asuka 100% Burning Festival : 

![1asukaingame](https://user-images.githubusercontent.com/12481242/34650743-02349ca0-f3be-11e7-8f3e-1e5dfb48ff10.JPG)
![1asukastartscreen](https://user-images.githubusercontent.com/12481242/34650744-0269cf74-f3be-11e7-8681-9819246d4027.JPG)

**Comment by BenjaminSiskoo** [comment]
Athlete Kings : 

![1athletekingsingame](https://user-images.githubusercontent.com/12481242/34650801-98ca6a1e-f3be-11e7-88eb-f778de962ecf.JPG)

**Comment by BenjaminSiskoo** [comment]
Gex : black screen, no boot.

**Comment by BenjaminSiskoo** [comment]
Guargdian heros : 

![1guardian](https://user-images.githubusercontent.com/12481242/34650891-2530e2f2-f3c0-11e7-8dc6-177547d9a3c5.JPG)

**Comment by FCare** [comment]
@devmiyax : I have patched the Athlete kings game here:
https://github.com/FCare/yabause/commit/0b09c327d957c777a38983ddab4da056bae32d69
https://github.com/FCare/yabause/commit/3694f2e3d32ddfc4e95500c5a492f6476862b79c

It is implementing the color calculation with SPCCCS equal to 3 (MSB bit). It is mostly working, I still have a small issue with a shadoow but it is globally implemented.

**Comment by BenjaminSiskoo** [comment]
Fixed except Astal and GEX. I create a new bug report for these games.
