### ISSUE TITLE
[Real Bios] Astal and GEX no boot...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [devmiyax/yabause#491]
Yaba Sanshiro 1.30 RC 01.17.2018 (Windows port) : 

With the real bios Astal don't boot. With the built in bios no problem.
With the real bios. Gex boot and black screen after the intro video.

**Comment by BenjaminSiskoo** [comment]
Yaba Sanshiro 1.8.1. Same problem.

**Comment by BenjaminSiskoo** [comment]
Gex is ok now.

**Comment by devmiyax** [comment]
ASTAL is duped @ https://github.com/devmiyax/yabause/issues/176
