### ISSUE TITLE
LINKLE LIVER STORY                                                                                              

### ISSUE THREAD

**Issue by devmiyax** [devmiyax/yabause#492]
version:1.3.0
device:SHIELD Android TV
cpu_type:3
video_type:1
comment:
[state file](http://www.uoyabause.org//system/reports/state_files/000/003/415/original/GS-9055_2018_01_17_22_44_55.zip)
![screenshot](http://www.uoyabause.org//system/reports/screenshots/000/003/415/original/screenshot.png?1516257903)

**Comment by fivefeet8** [comment]
Same in 1.7.0

**Comment by fivefeet8** [comment]
Same in 1.8

**Comment by natelawrence** [comment]
Same in 2.5.0

**Comment by devmiyax** [comment]
![image](https://user-images.githubusercontent.com/1174152/65372639-b1166a80-dcad-11e9-9119-4f2cd3471b93.png)
[492.zip](https://github.com/devmiyax/yabause/files/3638618/492.zip)

**Comment by devmiyax** [comment]
Alpha value is "0x0C"

![image](https://user-images.githubusercontent.com/1174152/87225647-968eb880-c3c9-11ea-83e5-e41f749bbde6.png)

![image](https://user-images.githubusercontent.com/1174152/87225666-c211a300-c3c9-11ea-942c-de586079ee94.png)

**Comment by devmiyax** [comment]
RealMachine
![image](https://user-images.githubusercontent.com/1174152/87236837-ed77aa80-c428-11ea-9521-d0600e804667.png)

SPD falg should be ignored??

**Comment by devmiyax** [comment]
```c++
  case 4:
  {
    // 8 bpp(256 color) Bank mode
    u32 colorBank = cmd->CMDCOLR & 0xFF00;
    u16 i, j;

    for (i = 0; i < sprite->h; i++) {
      endcnt = 0;
      for (j = 0; j < sprite->w; j++) {
        dot = T1ReadByte(Vdp1Ram, charAddr & 0x7FFFF);
        charAddr++;
        if (endcnt >= 2) {
          *texture->textdata = 0x0;
        }else if ((dot == 0) /*&& !SPD*/) { // ???????????????????
          *texture->textdata = 0x00;
        } else if ((dot == 0xFF) && !END) {
          *texture->textdata = 0x0;
          endcnt++;
        } else if (MSB_SHADOW) {
          *texture->textdata = VDP1COLOR(1, 0, priority, 1, 0);
        }
        else if ((dot | colorBank) == nromal_shadow) {
          *texture->textdata = VDP1COLOR(1, 0, priority, 1, 0);
        } else {
          const int colorindex = (dot | colorBank);
          if ((colorindex & 0x8000) && (fixVdp2Regs->SPCTL & 0x20)) {
            *texture->textdata = VDP1COLOR(0, colorcl, priority, 0, VDP1COLOR16TO24(colorindex));
          } else {
            Vdp1MaskSpritePixel(fixVdp2Regs->SPCTL & 0xF, &colorindex, &colorcl);
            *texture->textdata = VDP1COLOR(1, colorcl, priority, 0, colorindex);
          }
        }
        *texture->textdata++;
      }
      texture->textdata += texture->w;
    }
    break;
  }
```

**Comment by devmiyax** [comment]
SPR_ATTR test_attr = SPR_ATTRIBUTE(1,0,No_Gouraud,CL256Bnk|ECdis|SPdis,sprNoflip);
SPR_ATTR test_attr2 = SPR_ATTRIBUTE(2,0,No_Gouraud,CL256Bnk|ECdis|SPenb,sprNoflip);
slDispSprite((FIXED *)testobj, &test_attr, DEGtoANG(0) );
slDispSprite((FIXED *)testobj, &test_attr2, DEGtoANG(0) );


![image](https://user-images.githubusercontent.com/1174152/87239580-e3b36e80-c44b-11ea-8664-c806f1231d91.png)

**Comment by devmiyax** [comment]
SPR_ATTR test_attr = SPR_ATTRIBUTE(1,0,No_Gouraud,CL256Bnk|ECdis|SPdis,sprNoflip);
SPR_ATTR test_attr2 = SPR_ATTRIBUTE(2,0,No_Gouraud,CL256Bnk|ECdis|SPdis,sprNoflip);
slDispSprite((FIXED *)testobj, &test_attr, DEGtoANG(0) );
slDispSprite((FIXED *)testobj, &test_attr2, DEGtoANG(0) );

![image](https://user-images.githubusercontent.com/1174152/87239620-26754680-c44c-11ea-9a2d-4e9878f91554.png)

SPD falg works

**Comment by devmiyax** [comment]
```
Distorted Sprite
x1 = 151, y1 = 29, x2 = 109, y2 = 6
x3 = 85, y3 = 53, x4 = 127, y4 = 71
Texture address = 0002D4E0
Texture width = 32, height = 32
Texture read direction: Normal
High Speed Shrink Enabled
Pre-clipping Enabled
Transparent Pixel Enabled
Color mode: 8 BPP(256 color bank)
Color bank: 00001800
Color Calc. mode: Replace
```

**Comment by devmiyax** [comment]
Texture cache key is not enough, need to include CMDPMOD

``before
  tmp = cmd.CMDSRCA;
  tmp <<= 16;
  tmp |= cmd.CMDCOLR;
  tmp <<= 16;
  tmp |= cmd.CMDSIZE;
```

```after
  tmp = cmd.CMDSRCA;
  tmp <<= 16;
  tmp |= cmd.CMDCOLR;
  tmp <<= 16;
  tmp |= cmd.CMDSIZE;
  tmp <<= 16;
  tmp |= cmd.CMDPMOD;
```

![Screenshot from 2020-07-12 23-57-52](https://user-images.githubusercontent.com/1174152/87249718-c0181480-c49b-11ea-879b-424d33ce24b5.png)

Now fixed
