### ISSUE TITLE
VDP1COLOR can not work with non indexed color

### ISSUE THREAD

**Issue by FCare** [devmiyax/yabause#495]
If we look at this code:
static INLINE u32 VDP1COLOR(u32 C, u32 A, u32 P, u32 shadow, u32 color) {
  if (shadow != 0) {
    int a = 0;
  }
  return 0x80000000 | (C << 30) | (A << 27) | (P << 24) | (shadow << 23) | color;
}

static INLINE u32 VDP1COLOR16TO24(u16 temp) {
  return (((u32)temp & 0x1F) << 3 | ((u32)temp & 0x3E0) << 6 | ((u32)temp & 0x7C00) << 9);
}

Using VDP1COLOR16TO24 as color parameter of VDP1COLOR might modify the MSB. In order to fix, the 16bits to 24 bits conversion shall be done in the shader. It will also save some bits for extra information useable in the shader....

**Comment by devmiyax** [comment]
I agree that if  16bits to 24 bits conversion is done in the shader, we can use more bits on CPU.
But Look VDP2 User Manual Chapter 9. Only index color data have Shadow bit.
So 8bits are enough for direct color.

**Comment by FCare** [comment]
I saw, but the function is not safe and in case it can not never be the case that a non indexed color use a shadow bit, then it should be better to modify the VDP1COLOR function to avoid to introduce bad colors in case of a bad call...

**Comment by FCare** [comment]
something like this:
INLINE u32 VDP1COLOR(u32 C, u32 A, u32 P, u32 shadow, u32 color) {
  if (shadow != 0) {
    int a = 0;
  }
  return 0x80000000 | (C << 30) | (A << 27) | (P << 24) | (((!C)?0:shadow) << 23) | color;
}

**Comment by devmiyax** [comment]
Yeah, your suggestion makes our code more safety. but we have bigger issues than code safety. For example speed and accuracy.

**Comment by FCare** [comment]
If you want to improve accuracy, the way yabause is handling the FBCR register is false.
In vdp2.c, this line makes the manual change to also erase the vdp1 buffer, which is wrong.
// VBlank Erase
  if (Vdp1External.vbalnk_erase ||  // VBlank Erace (VBE1) 
    ((Vdp1Regs->FBCR & 2) == 0)){  // One cycle mode
    VIDCore->Vdp1EraseWrite();
  }

I fixed this behvior on my tree and it shows other bugs in the openGL stacks, for example, during the erasewrite, we have to go back to the default_fbo framebuffer... But there are some other bugs not so easy to catch.
If you are interested, look at onecyclemode, manualchange and manualerase variable usage here:
https://github.com/FCare/yabause/blob/extui-align/yabause/src/vdp2.c

**Comment by FCare** [comment]
This behavior is fixing the display of cross icons when Alone in the Dark game is loading.
