### ISSUE TITLE
Bug Too! Texture Corruption

### ISSUE THREAD

**Issue by fivefeet8** [devmiyax/yabause#5]
When playing the levels, the background texture and some foreground objects will become corrupted.  The textures will get multi-colored blits.  Below is a video showing the bug.

https://www.youtube.com/watch?v=lzz9w6tlMzk

**Comment by devmiyax** [comment]
![image](https://cloud.githubusercontent.com/assets/1174152/12012458/117506a6-ad38-11e5-89f7-67e4d889858e.png)

it seems OK.
