### ISSUE TITLE
Shining Force 3 - Crash upon battle transition

### ISSUE THREAD

**Issue by DarkSki** [devmiyax/yabause#50]
Crashes upon first battle transition.
I tired using different ram carts with no change.
Unsure if this was reported before /known.
Running LG G3 5.0.2 Lollipop.

**Comment by fivefeet8** [comment]
I'm able to play fine through the battles.  I'm already outside the first town.  There are rendering issues when you're character battles though.

https://www.youtube.com/watch?v=YjGo39AhYqw

**Comment by DarkSki** [comment]
I will try to rip again dont know what I could possibly have done wrong

**Comment by fivefeet8** [comment]
What's happened when you re-ripped the game?  Did it fix the issue you were having?

**Comment by DarkSki** [comment]
Same issue with me on the LG G3 so it much be something with the Snapdragon 801 im getting a new phone soon so im going to see how the Snapdragon 810 fares.

**Comment by DarkSki** [comment]
I'm going to close this issue as it may have been an issue with the custom rom that was installed
