### ISSUE TITLE
Space Harrier or Outrun background are broken

### ISSUE THREAD

**Issue by FCare** [devmiyax/yabause#502]
You should apply:
https://github.com/FCare/yabause/commit/a07d7eb15d51d0000e4ddfa0783188531770db29

**Comment by devmiyax** [comment]
Nice. I understand what you want to do. But I think your implementation is  too expensive  when one color mode is select.

**Comment by devmiyax** [comment]
![image](https://user-images.githubusercontent.com/1174152/36338887-239971a4-13fd-11e8-8592-e5fad4990497.png)
