### ISSUE TITLE
[AfterBurner] No background while loading

### ISSUE THREAD

**Issue by devmiyax** [devmiyax/yabause#503]
![image](https://user-images.githubusercontent.com/1174152/36338477-713484bc-13f3-11e8-94aa-5bb115d492c0.png)

**Comment by FCare** [comment]
Devmiyax, I have implemented the read and write framebuffer. I think it is fixing this and all the Sega ages loading screens. It is also fixing missing screens in blam machinehead. You can look on my kronos repository. All code is available on github

**Comment by devmiyax** [comment]
![image](https://user-images.githubusercontent.com/1174152/64992408-d05c7300-d90e-11e9-8a80-07bc924c04ac.png)

**Comment by natelawrence** [comment]
@FCare @devmiyax Do you know if this fix also addresses the missing loading screen background images for Lobotomy Software games such as: 
- Powerslave // Exhumed // 西暦１９９９　ファラオの復活
- Duke Nukem 3D
- Quake
?
