### ISSUE TITLE
[AfterBurner] Ground is rotated 45 degree when player is on the flat position.

### ISSUE THREAD

**Issue by devmiyax** [devmiyax/yabause#505]
![image](https://user-images.githubusercontent.com/1174152/36338498-08496b10-13f4-11e8-9c78-d5bbe9c7fc56.png)

**Comment by devmiyax** [comment]
Line scroll table address 0x0609649c

**Comment by devmiyax** [comment]
(0x66 - 0xE0)  * 0x0010000  = 0x007A0000
(0xA0 * 0x00) = 0
 0x007A0000 + 0 = 0x007A0000
0x01000000 - 0x007A0000 = 0x00860000

```
0x0607D84E: bt 0x0607D854
0x0607D84C: cmp/pz r0
0x0607D84A: mov r12, r2
0x0607D848: mov r1, r0
0x0607D846: mov.l @(0x058, pc), r7 ; 0x0607D89C
0x0607D844: mov.l @(0x054, pc), r6 ; 0x0607D898
0x0607D842: mov.w @(0x03A, pc), r5 ; 0x0607D87C
0x0607D840: mov.l @(0x004, r13), r4
0x0607D83E: mov.l @(0x000, r13), r3
0x0607D83C: mov.l @(0x058, pc), r14 ; 0x0607D894
0x0607D83A: sub r2, r1
0x0607D838: mov.l @(0x058, pc), r1 ; 0x0607D890
0x0607D836: add r1, r2
0x0607D834: sts macl, r2
0x0607D832: mul.l r0, r2
0x0607D830: mov.l @(0x000, r13), r0
0x0607D82E: mov r10, r2
0x0607D82C: sts macl, r1
0x0607D82A: mul.l r0, r1
0x0607D828: mov.l @(0x004, r13), r0
0x0607D826: sub r0, r1
0x0607D824: mov.w @(0x056, pc), r1 ; 0x0607D87A
0x0607D822: mov r9, r0
0x0607D820: add r0, r13
0x0607D81E: shll r0
0x0607D81C: shll2 r0
0x0607D81A: extu.b r0, r0
```

**Comment by devmiyax** [comment]
(0xE0 - 0x54 ) * 0xFFFF01ED = 0xFF750D9C
0x9C * 0x00001F56 = 0x00131868
0x00131868 + 0xFF750D9C = 0xFF882604
0x01000000 - 0xFF882604 = 0x0177D9FC

![image](https://user-images.githubusercontent.com/1174152/36340162-3d90f1dc-141a-11e8-9756-302db66f6797.png)

**Comment by devmiyax** [comment]
(0xE0 - 0x54) * 0xFF4E = 0x008B9EA8
0xA1 * 0x000012D5 = 0x000BD7F5
0x000BD7F5 + 0x008B9EA8 = 0x0097769D
0x01000000 - 0x0097769D = 0x00688963

![image](https://user-images.githubusercontent.com/1174152/36340196-3ea902a2-141b-11e8-98dd-974ef8c660ba.png)

**Comment by devmiyax** [comment]
0x0607D830: mov.l @(0x000, r13), r0
@R13( 0x0607D994) = 0 !? bad 
@R13( 0x0607e164) = 0x000012D5  good
@R13( 0x0607D9A4) = 0x00000648  good

**Comment by devmiyax** [comment]
It seems that's bad

```C
      if (info->lineinfo[lineindex].CoordinateIncH == 0) {
       info->lineinfo[lineindex].CoordinateIncH = 0x0100;
      }
```

**Comment by devmiyax** [comment]
nice

![image](https://user-images.githubusercontent.com/1174152/36340663-c9061250-1425-11e8-9d8d-d5b4ed9ecce0.png)

**Comment by BenjaminSiskoo** [comment]
Nice
