### ISSUE TITLE
[Panzer Dragoon zwei] RBG line color insersion is not correct.

### ISSUE THREAD

**Issue by devmiyax** [devmiyax/yabause#515]
Reference
![image](https://user-images.githubusercontent.com/1174152/36930845-60ad8544-1eed-11e8-8bc9-e9e219f81337.png)

Yaba Sanshiro
![image](https://user-images.githubusercontent.com/1174152/36930855-8dfe9880-1eed-11e8-9d27-c0eb403927c5.png)

**Comment by devmiyax** [comment]
fixed

![image](https://user-images.githubusercontent.com/1174152/36931621-3ce5213e-1efd-11e8-9f2a-cf26bade46a5.png)

**Comment by elcorsico** [comment]
Cool
Nice fix
continue amélioration
