### ISSUE TITLE
[Space Harrier] Shadow is not transparent

### ISSUE THREAD

**Issue by devmiyax** [devmiyax/yabause#516]
![image](https://user-images.githubusercontent.com/1174152/36939916-6fd35762-1f7c-11e8-89eb-f46254e30e8a.png)

**Comment by devmiyax** [comment]
fixed
![image](https://user-images.githubusercontent.com/1174152/36940839-34c9d56a-1f90-11e8-96d6-26b55cd40067.png)

**Comment by FCare** [comment]
Ok I ve just seen this fix now... nice work!

**Comment by LeCharlatan** [comment]
Nice work Devmiyax :) 
Can't wait for a Linux working version of this yabause's fork !
