### ISSUE TITLE
[OutRun] Shadow is not drawn

### ISSUE THREAD

**Issue by devmiyax** [devmiyax/yabause#517]
Refernce
![image](https://user-images.githubusercontent.com/1174152/36940822-8788dd06-1f8f-11e8-9550-6fa647cb79f7.png)

Yaba sanshiro 1.6.1
![image](https://user-images.githubusercontent.com/1174152/36940817-70d3204e-1f8f-11e8-9b63-96aa810aa2c2.png)

**Comment by devmiyax** [comment]
fixed

![image](https://user-images.githubusercontent.com/1174152/36940824-a2166148-1f8f-11e8-9579-7a2631de18c4.png)

**Comment by BenjaminSiskoo** [comment]
Great :)

**Comment by FCare** [comment]
Really nice. Did you see also on space harrier that shadows are black instead of grey? Maybe your patch fixed this also...
