### ISSUE TITLE
[Advanced Variable Geo] Freeze on the character selection menu

### ISSUE THREAD

**Issue by BenjaminSiskoo** [devmiyax/yabause#518]
Yaba Sanshiro 1.6.4.

The game freeze on the character selection menu since Yaba Sanshiro 1.3.0.

**Comment by BenjaminSiskoo** [comment]
Yaba Sanshiro 1.7.0. Same problem.

**Comment by BenjaminSiskoo** [comment]
Yab a Sanshiro 1.8.1 : same problem.

**Comment by kamugin** [comment]
the game came back freeze in normal mode after defeat the JUN.
Windows version 1.16.5 ( Its fixed in a v.1.16.3 )

**Comment by kamugin** [comment]
Game freeze in normal mode after defeat the AYAKO.
Windows version 1.16.3 30th Anniversary Edition
