### ISSUE TITLE
Crashing with real bios

### ISSUE THREAD

**Issue by fivefeet8** [devmiyax/yabause#520]
Device:  Shield TV
Emu Version:  1.6.4-1.6.5

Issue:
After selecting the HLE bios to run Astal, the emulator crashes all the time when loading any game with a Real Bios.  Bug report sent through Play Store.

**Comment by FCare** [comment]
Hi, did you tried many bios files? Some bios files have been hacked and are buggy.
Can you share the place where you downloaded this bios file or maybe share the bio file itself?

**Comment by fivefeet8** [comment]
These are the same Bios files I've used for previous versions of the emulator.  And they work fine on other Saturn emulators.  Before I loaded the HLE bios, the emulator worked fine.

**Comment by fivefeet8** [comment]
Seems to be fixed in 1.7.0
