### ISSUE TITLE
[Scorcher (E)] GFX problem with the trees in the background...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [devmiyax/yabause#529]
Kronos 1.7.0 : 

![1scorcher](https://user-images.githubusercontent.com/12481242/39082352-3fd4ed60-4541-11e8-942d-b3c41a5d45d3.JPG)

**Comment by devmiyax** [comment]
It does not happened on my device ...

![image](https://user-images.githubusercontent.com/1174152/39091899-ee081f3a-4639-11e8-883a-f4ad2d278223.png)

**Comment by BenjaminSiskoo** [comment]
Android or Windows ? If you launch some games before Scorcher, the bug is not displayed. Just launch Yaba Sanshiro 1.7.0 then Scorcher.

**Comment by BenjaminSiskoo** [comment]
Still the same problem with Yaba Sanshiro 1.8

**Comment by BenjaminSiskoo** [comment]
Seems ok now :) \o/
