### ISSUE TITLE
[Battle Arena Toshinden Remix] GFX problems

### ISSUE THREAD

**Issue by BenjaminSiskoo** [devmiyax/yabause#53]
Left picture : Yabause Devmiyax 09.05.2015
Right picture : Yabause Devmiyax 09.18.2015

![battlearena_mainscreen](https://cloud.githubusercontent.com/assets/12481242/9966306/6b49d346-5e3c-11e5-8e00-90a97ee28b9a.PNG)

![battlearena_intro](https://cloud.githubusercontent.com/assets/12481242/9966311/71ab2096-5e3c-11e5-8790-7ecb131a6bd8.PNG)

![battlearena_ingame](https://cloud.githubusercontent.com/assets/12481242/9966312/748bbcee-5e3c-11e5-84e6-e0ba769a7519.PNG)

**Comment by BenjaminSiskoo** [comment]
Left picture : Yabause 02.21.2016 (Software) 
 Right picture : Yabause Devmiyax 01.02.2016 (OpenGL)

Ring problem.

![batr_ingame](https://cloud.githubusercontent.com/assets/12481242/13202284/42994fde-d895-11e5-8bea-5507c5c9e6c8.JPG)

**Comment by devmiyax** [comment]
![Uploading image.png…]()

**Comment by BenjaminSiskoo** [comment]
Last remainging issue with this game. Missing background in the character selection menu.

![toshinden](https://cloud.githubusercontent.com/assets/12481242/13722656/75caf5e8-e84d-11e5-9ebb-729009caeed7.JPG)

**Comment by devmiyax** [comment]
OK, I'll investigate

**Comment by devmiyax** [comment]
Tested on real Saturn. When Gradation is enabled, color calculation value is ignored.

![slgradationon_slcolratenbg1 clrate0_32](https://cloud.githubusercontent.com/assets/1174152/14170992/84f8321a-f76b-11e5-9cda-f82610dfbf39.png)

![slcolratenbg1 clrate0_32](https://cloud.githubusercontent.com/assets/1174152/14170998/919aacdc-f76b-11e5-9757-7cb24510f2d0.png)

**Comment by devmiyax** [comment]
12.13 Blur function is implemented.

![image](https://cloud.githubusercontent.com/assets/1174152/14177743/b02d0f10-f792-11e5-92ec-06f039e45016.png)

**Comment by BenjaminSiskoo** [comment]
Great Job... Seems better with Yabause than SSF now.

**Comment by BenjaminSiskoo** [comment]
Seems perfect. Fixed
