### ISSUE TITLE
Panzer Dragoon Zwei Texture Issues

### ISSUE THREAD

**Issue by fivefeet8** [devmiyax/yabause#533]
On 1.8
Shield TV

![screenshot 1](https://user-images.githubusercontent.com/12039585/39393030-02e8a26e-4a75-11e8-928b-d595b93e367f.png)

**Comment by devmiyax** [comment]
fixed by e089000
![image](https://user-images.githubusercontent.com/1174152/39666929-b809f2ca-50e6-11e8-9323-e1597bab9ded.png)
