### ISSUE TITLE
[Slam & Jam '96] Writing issue and score issue...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [devmiyax/yabause#535]
Yaba Sanshiro 1.8.0 : 

![1slam](https://user-images.githubusercontent.com/12481242/39394270-a1c75f2a-4abf-11e8-9a44-f47a3faab33c.JPG)
![1slam1](https://user-images.githubusercontent.com/12481242/39394271-a1e80bb2-4abf-11e8-9f76-ff7efef6e27b.JPG)

**Comment by corvusd** [comment]
Sorry for the Off-topic: 
Khronos?? Another fork of the fork?? Really... please... I a big big fan of the SEGA an SS... and Yabause still need more work to grow up, to be a great useful application for develop (great debbuger and whit more way to improve) new software. All your great work put it together in one branch is the need it this great community! Thank for your efforts :)

**Comment by BenjaminSiskoo** [comment]
Fixed Yaba Sanshiro 1.8.1
