### ISSUE TITLE
[Contra - Legacy Of War] Regression Yaba 1.7.0 to 1.8.0 (Shadow)...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [devmiyax/yabause#536]
Yaba Sanshiro 1.8 : 

![1contrasghadow](https://user-images.githubusercontent.com/12481242/39394571-ed239f58-4ac2-11e8-81d7-8c06d2a16994.JPG)

**Comment by devmiyax** [comment]
Fixed
![image](https://user-images.githubusercontent.com/1174152/39655781-85292750-5036-11e8-8829-7abdf02a0915.png)

**Comment by BenjaminSiskoo** [comment]
nice :)
