### ISSUE TITLE
[Blam Machinehead] Red screen.

### ISSUE THREAD

**Issue by BenjaminSiskoo** [devmiyax/yabause#54]
Left Picture : Yabause Devmiyax 05.05.2016 (OpenGL)
 Right Picture : Yabause Devmiyax 05.05.2016 (Software)

![blam machinehead](https://cloud.githubusercontent.com/assets/12481242/11761383/d6e335c2-a0c0-11e5-984c-ca9853e1f14f.PNG)

**Comment by devmiyax** [comment]
![image](https://cloud.githubusercontent.com/assets/1174152/12046638/bd322438-aeff-11e5-9a86-00d3f659f598.png)

reference

**Comment by BenjaminSiskoo** [comment]
Text are not properly dispalyed (kind of blur).

![blammachinheheadopengl](https://cloud.githubusercontent.com/assets/12481242/15070370/1ebc40ec-1384-11e6-8340-af92e456a95e.JPG)

**Comment by devmiyax** [comment]
Actually Blur is enabled.
![image](https://cloud.githubusercontent.com/assets/1174152/15085831/98997356-1417-11e6-8b3a-0293e96340f3.png)

**Comment by BenjaminSiskoo** [comment]
Is it a normal behaviour ?

**Comment by BenjaminSiskoo** [comment]
UoYabause 0.4.6

Polygons problems. But now the color seems good. Background problem (mountains)

![blam machinehead](https://cloud.githubusercontent.com/assets/12481242/25575748/3f296a84-2e5a-11e7-9960-66c47dc930b9.JPG)

**Comment by BenjaminSiskoo** [comment]
Left Picture : UoYabause 0.5.2 
Right Picture : Medgui 

![blam](https://user-images.githubusercontent.com/12481242/28307612-b9427d16-6ba3-11e7-8807-f2fd8686c1b9.JPG)
![blamingame](https://user-images.githubusercontent.com/12481242/28307613-b94924c2-6ba3-11e7-824a-86337763d76b.JPG)
![blammissingscreen](https://user-images.githubusercontent.com/12481242/28307615-b9669034-6ba3-11e7-869c-33ea07cfab39.JPG)

**Comment by BenjaminSiskoo** [comment]
UoYabause 0.5.2 commit 4106 fixed, just transition screen is missing.

**Comment by BenjaminSiskoo** [comment]
UoYabause 0.5.5 Transition screen is missing (loading screen).

**Comment by BenjaminSiskoo** [comment]
Regression with your last commits (12.24.2017)

![1blam](https://user-images.githubusercontent.com/12481242/34325750-74091b90-e89b-11e7-9592-556a6514e6a7.JPG)
