### ISSUE TITLE
Assault Suit Leynos 2 crashes Yaba Sanshiro.

### ISSUE THREAD

**Issue by blackman91** [devmiyax/yabause#543]
The games crashes yaba sanshiro after the bios. Unbootable.

Original game name: Juusoukihei leynos 2

Latest yaba Sanshiro from the playstore.

**Comment by blackman91** [comment]
Log:
![screenshot_20180524-051230](https://user-images.githubusercontent.com/6578180/40883539-18dd0ae4-66c5-11e8-9f2c-8bd29b1b915a.png)

**Comment by devmiyax** [comment]
dupe #56
