### ISSUE TITLE
[Panzer Dragoon Saga / Azel Panzer Dragoon RPG][Windows] - fully playable and finishable - YabaSanshiro 1.8.1

### ISSUE THREAD

**Issue by Aris-t2** [devmiyax/yabause#545]
Emulator version: 1.8.1
OS: Windows 7x64
Audio settings: default
Video settings:
![settings](https://user-images.githubusercontent.com/6013569/40552790-0fd30762-6041-11e8-8982-cf4283911637.png)

I'm wondering why the compatibility list http://www.uoyabause.org/games does not mention this game at all.

It runs great and is fully finishable. Only of few minor visual glitches occur here and there and the background music "hangs" for 2 sec in very rare cases (happened like 5 times in an 18 hours playthrough).

Finished with European and US versions of the game. The Japanese works too and savegames are also loadable.

Near end screenshot:
![near_end](https://user-images.githubusercontent.com/6013569/40552539-46a29678-6040-11e8-841a-47eaa7aee31e.png)

Results (not as good as my 100% runs on the Sega Saturn in 1998, but still OK):
![result](https://user-images.githubusercontent.com/6013569/40552570-60b685d8-6040-11e8-8aa8-8e3c9228a4ff.png)

**Comment by devmiyax** [comment]
great!
