### ISSUE TITLE
Shining Force 3 Scenario 2 Game Freezes After 1 on 1 Skirmishes

### ISSUE THREAD

**Issue by kaiserwongze** [devmiyax/yabause#547]
Since the final battle of Chapter 1, the game or emulator will freeze after the 1on1 skirmish.  There is about an 80% chance it will happen.

Have to cut around the issue by saving state right before each skirmish and reloading.  After reloading it will happen again 80% of the time.

**Comment by kaiserwongze** [comment]
Also, I'm using the latest windows version of Yaba Sanshiro 1.8.1

**Comment by devmiyax** [comment]
@kaiserwongze Can you share state save data?

**Comment by devmiyax** [comment]
no response
