### ISSUE TITLE
Snapdragon 810 Open GL Render

### ISSUE THREAD

**Issue by DarkSki** [devmiyax/yabause#55]
So I got my new phone stoked to play some classics but its running terribly

Trying Shining Force 3 I get about 10 - 15 fps with the open GL Render and about 20 to 30 fps with the software renderer.

I presume this has something to do with the jump to 64 bit cpu

Let me know if there are any quick fixes or if you have an idea as to what's wrong.

I can confirm that it's not an issue with the phone as all other games I have on here run way batter than on my old Snapdragon 801.

**Comment by fivefeet8** [comment]
I'm using the emulator on my Shield ATV(64bit CPU) and it's running with no hint of slowdown.  What phone do you have?  If it's slower with the Opengl renderer, then it's your GPu on your phone that is not being sped up for performance modes.  Check the developer menu and enable GPu performance display.

**Comment by DarkSki** [comment]
Hmm I can't seem to find this option unless it's called something else
I'm running an Letv Max

**Comment by fivefeet8** [comment]
Normally, Android devices can enable a Developer Menu by clicking on the "Build number" within the "About" menu 10 times.

**Comment by DarkSki** [comment]
The only comparable setting in the developer options is Force Gpu rendering. II have messed with it but there was no change.

The LG G3 has the 2k resolution just like this new phone.

Reicast and dolphin run way better on this device than on the LG G3.

**Comment by DarkSki** [comment]
I ran Geekbench to make sure the device is performing properly and got 1347 Single and 3902 Multi.

Running 5.02 Android 

uoyabause runs slowly even in the menus and trying the pull up the ingame menu lags the phone.

Sometimes while playing a game it says that uoyabause has stopped responding and gives me the option to wait or close it.

You did some amazing work and my old phone was able to play some games smoothly so I hope you can figure it out.

If you need anything from me to help then please let me know.

**Comment by fivefeet8** [comment]
On my HTC One M8, under the developer menu in the Advanced options, I get a "Profile GPU Rendering" option.  Do you not have that either?

**Comment by DarkSki** [comment]
Hello_


Okay I do see that setting.

What should I change in there ?


Appreciate the help.


Thank you,


Sent by Outlook for Android





On Thu, Sep 24, 2015 at 7:14 AM -0700, "fivefeet8" <notifications@github.com> wrote:
On my HTC One M8, under the developer menu in the Advanced options, I get a "Profile GPU Rendering" option.  Do you not have that either?

---

**Comment by fivefeet8** [comment]
Here's a video showing some thermal throttling issues with the S810 running Dolphin.  Maybe that's what you're getting with it running in Yabause?  

https://www.youtube.com/watch?v=dDy3NXoNTRs&feature=youtu.be

**Comment by DarkSki** [comment]
It is definitely not a throttling issue as it occurs immediately.

The device does throttle but you can visually see it when it does.

It usually takes about 40 minutes of gaming with Dolphin to see it slideshow but it doesn't stay throttled for long just a few minutes and then it returns to its previous speed.

Everyone seems to think that the Snapdragon 810 is absolute garbage but even once it's completely throttled - 2 hours of continual Dolphin emulation - the benchmarks still give me around 55000 in Antutu which is still better than the Snapdragon 805.

**Comment by DarkSki** [comment]
So I ran a test with Trepn Profiler which is made by Qualcomm.

It looks like the Gpu runs at 40% load at 300mhz instead of 650mhz which it can run at.

Another thing I noticed is that the CPU's never switch to the big cores but always stay on the LITTLE cores when a game is being played through uoyabause.

**Comment by DarkSki** [comment]
I upgraded this phone last week and it seems you were correct. Your emulator pushes the big cores to the max and overheats them almost immediately. I don't know why dolphin ran okay on it but I can assume it just runs everything on the LITTLE cores.
