### ISSUE TITLE
8bit flashback here: Testing Mr Bones for Sega Saturn on ORA image for Odroid XU4

### ISSUE THREAD

**Issue by nnotfilc** [devmiyax/yabause#551]
When trying to load Mr bones it goes to black screen after intro fmv scene and round 1 never loads.

**Comment by devmiyax** [comment]
After 

```
cs2	: Command: playDisc 0bc4 1080 5192 0080 481a
```

Should be

```
Get Sector Number; Source=0x00 --- HIRQ=0x0fc4, HIRQ_Mask=0x0000
Calculate Actual Size; Source=0x00[0x0000], Count=0x02 --- HIRQ=0x0f84, HIRQ_Mask=0x0000
Get CD Status --- HIRQ=0x0bc4, HIRQ_Mask=0x0000
Get Actual Size --- HIRQ=0x0bc4, HIRQ_Mask=0x0000
Get Sector Data; Source=0x00[0x0000], Count=0x0002 --- HIRQ=0x0b44, HIRQ_Mask=0x0000
```

**Comment by devmiyax** [comment]
```
0x00257890: mov.l @r2, r1
0x00257892: tst r1,r1
0x00257894: bt 0x00257890
```
r2 = 202FFF0C

**Comment by devmiyax** [comment]
The strict timing of Master CPU and Slave CPU communication

Read FTCR=80
After FTCR=0 VAL=0 PC=00269CDE
Input Capture from master cpu!
Read FTCR=80
After FTCR=0 VAL=0 PC=00256D20

**Comment by nnotfilc** [comment]
So level started then froze again?

**Comment by FCare** [comment]
@devmiyax : can you share more details about the issue and how you achieve this screen?

**Comment by devmiyax** [comment]
It seems playable, but priority function between VDP1 and VDP2 is not enough.

![image](https://user-images.githubusercontent.com/1174152/44727097-344da700-ab14-11e8-9e56-7c388e81e684.png)

**Comment by FCare** [comment]
And how did you fixed the booting issue? If you can share your ptch, maybe I can help for priority stuff

**Comment by devmiyax** [comment]
works perfectlly.
![image](https://user-images.githubusercontent.com/1174152/44819624-7ff17500-ac28-11e8-8f06-5e673c32c628.png)

**Comment by FCare** [comment]
Great! Can't wait to see the patch :-) Hopefully, it will also fix some other games not booting :-)

**Comment by nnotfilc** [comment]
Fantastic is there anything I can do to make it work for the xu4 ??? now that you have it working for you. Script patch/update etc?

**Comment by BenjaminSiskoo** [comment]
:o it should be interesting, some games should be playable now. @devmiyax San, I'm really curious to test it.

**Comment by nnotfilc** [comment]
@devmiyax  will this updated to work on ORA beta v2? I just updated from source and no luck with mr bones yet. Thank you

**Comment by FCare** [comment]
@devmiyax: no update on github this weekend? Regarding doom, i did a lot of fixes to improve. The texture manager has to be splitted between vdp1 abd vdp2 since on doom, vdp1dracommands is executed many times on the same frame and the vdp1 frame is not swapped at the same time of vdp2. It fixes the ingame blinking. I am also working on bgon that changes during the same frame, this is used in f1 challenge. It fixes bad drawing or missing drawings in some games... hope you will be able to share some patches today...

**Comment by devmiyax** [comment]
merged to master
