### ISSUE TITLE
[Bug] Start not working on Batsugan

### ISSUE THREAD

**Issue by wstevens0n** [devmiyax/yabause#553]
Start button does not map for game

**Comment by tapperp** [comment]
Works for me. Using v2.2.0 Windows. Converted DW release to single bin.

**Comment by devmiyax** [comment]
This is issues is reproduced on Windows , Bios emulation

**Comment by devmiyax** [comment]
no issue on 1.8.0
![image](https://user-images.githubusercontent.com/1174152/162563659-57bc67e0-1f11-40c1-9356-45ce9d95be75.png)
