### ISSUE TITLE
8bit flash back here: Screen tear issues on odroid xu4-ORA beta v2 possible fixes?

### ISSUE THREAD

**Issue by nnotfilc** [devmiyax/yabause#555]
Looking for some ideas on how to battle the screen tear thats happening on most of the games.  Thank you

**Comment by FCare** [comment]
Tearing might come from EGL setInterval if it has been set to 0 (It has to be at least 1 to sync on V-Sync).
It can also come from the xu4 linux display driver.

**Comment by 6alileo** [comment]
8bit - tearing isn't an issue on ORA 1.1 and I was told they are using same exact drivers, only difference is the kernel so there seems to be an issue with the kernel being used in v2 beta and the fix is dependent on HardKernel.

**Comment by devmiyax** [comment]
I think it's graphics driver problem.
