### ISSUE TITLE
8bit Flashback here: How to enable/emulate cartridge 4mb/1mb ram to play certain games like MSH vs Streetfighter. 

### ISSUE THREAD

**Issue by nnotfilc** [devmiyax/yabause#558]
How to enable/emulate the 4mb ram to play certain games like MSH vs Streetfighter. Certain games will not play without the extra ram feature. Testing on Odroid Xu4 ORA retropie beta. If there is a way to add this to menu options that would be great.

**Comment by devmiyax** [comment]
4MByte ram is enabled.

https://github.com/devmiyax/yabause/blob/master/yabause/src/retro_arena/main.cpp#L218
