### ISSUE TITLE
Assault Suit Leynos 2

### ISSUE THREAD

**Issue by ADormant** [devmiyax/yabause#56]
It just gets a black screen.

**Comment by BenjaminSiskoo** [comment]
Yabause Devmiyax 12.13.2015 (OpenGL)

Built in bios : black screen.
Real bios : Yabause crash.

**Comment by BenjaminSiskoo** [comment]
UoYabause 06.20.2016 (OpenGL)

Built in bios : black screen.
Real bios : Yabause crash.

**Comment by blisstik** [comment]
@BenjaminSiskoo - this is now resolved, please close

**Comment by BenjaminSiskoo** [comment]
@blisstik I can't close, It's not my bug report. @devmiyax or Adormant can close this.

**Comment by devmiyax** [comment]
![image](https://user-images.githubusercontent.com/1174152/162559486-56c253a3-e4bd-4cc5-8596-62827f6cd2a8.png)
playable in 1.8.0
