### ISSUE TITLE
Alone In The Dark : the game reboot. Yaba's regressions 1.8.1 --> 2.6.3

### ISSUE THREAD

**Issue by BenjaminSiskoo** [devmiyax/yabause#560]
Alone In The Dark  : on the press start screen, after pushing start, the game reboot.

**Comment by ivanmestre** [comment]
Yaba Sanshiro is crashing on start on an Nvidia Optimus laptop when using the Nvidia GPU, might have to do with the updated Qt libraries. 1.8.1 is running fine.

**Comment by tapperp** [comment]
Shinobi Legends no longer runs. 

Capcom 2D fighters like SFA3 and Vampire Savior freeze at "Now Loading" screen.

**Comment by BenjaminSiskoo** [comment]
Same with 2.7.4
