### ISSUE TITLE
Keep pixel aspect ratio

### ISSUE THREAD

**Issue by paul-met** [devmiyax/yabause#562]
Since the appearance of the branch from the main project Yabause (I mean UoYabause or YabaSanshiro for Windows), appeared the problem of correctly displaying the pixel aspect ratio of the picture. In the original Yabause, there was a "Fit to Window" option for this, which does not want to work correctly in YabaSanshiro. After activating this option, the picture is cropped from the top of the screen. I ask, finally, to solve this problem. In view of the fact that many games for Saturn came out with a different pixel aspect ratio from 4:3 aspect, I want to see a geometrically correct picture without distortion. Thanks.
![yabasanshiro](https://user-images.githubusercontent.com/13948032/45598083-7c0e7280-b9de-11e8-9ba5-97b245079ed3.png)
![yabause](https://user-images.githubusercontent.com/13948032/45598084-7c0e7280-b9de-11e8-9098-91e9ce3a0379.png)

**Comment by devmiyax** [comment]
This issue is happned when state save menu is selected.
![image](https://user-images.githubusercontent.com/1174152/64990721-4d85e900-d90b-11e9-80e9-9a75c51c028e.png)

![image](https://user-images.githubusercontent.com/1174152/64990736-5bd40500-d90b-11e9-9303-c2fe0be52b4d.png)

**Comment by paul-met** [comment]
Now it's working correct in v2.10.0. Thank you.
