### ISSUE TITLE
Controller initialization issues on Windows 10

### ISSUE THREAD

**Issue by tapperp** [devmiyax/yabause#563]
Version used: Yaba Sanshiro 2.2.0 for Windows

On some devices, using xinput, controllers are not initialized at start even though they are plugged in and ready at runtime. The user must force recognition/initialization by entering settings (i.e. press ctrl-S) and then exiting to game. This works, but is annoying to have to enter settings every time to run a game.

Device used: GPD Win 2 (Windows 10 handheld with built-in Xb360 type controller).

Please note: every other game and emulator recognizes and inits the controls so I'm reasonably sure the issue is with Yaba Sanshiro.

**Comment by skelton** [comment]
Use SDL interface, run the emulator with xipunt switch and should work fine, it does for me at least on win 2.

**Comment by devmiyax** [comment]
@tapperp Does SDL interface fix your issue?

**Comment by devmiyax** [comment]
no response

**Comment by tapperp** [comment]
I apologize for lack of response. Had hand surgery last week and haven't been playing any videogames.
