### ISSUE TITLE
Xbox360 wireless controller not work on Odroid XU4 ORA RetroPie 1.5.1

### ISSUE THREAD

**Issue by dewenhsu** [devmiyax/yabause#564]
I can press select buttom and map to Xbox360 wireless controller, but the buttom no response. I can map to USB keyboard and it works.
Thank you.
input config file /home/pigaming/.yabasanshiro/keymapv2.jason
https://www.dropbox.com/s/y8agy2fq4dtujco/keymapv2.json?dl=0

**Comment by devmiyax** [comment]
fixed by
https://github.com/devmiyax/yabause/commit/fa9f9f47c5c3a2863939a1ec00624c19b4457152
