### ISSUE TITLE
End error compile yabause-minimum_linux branch

### ISSUE THREAD

**Issue by corvusd** [devmiyax/yabause#565]
/usr/bin/ld: ../libyabause.a(osdcore.c.o): referencia sin definir al símbolo 'glVertex2i'
//usr/lib/nvidia-396/libGL.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
src/qt/CMakeFiles/yabause-qt.dir/build.make:2519: fallo en las instrucciones para el objetivo 'src/qt/yabasanshiro'
make[2]: *** [src/qt/yabasanshiro] Error 1
CMakeFiles/Makefile2:217: fallo en las instrucciones para el objetivo 'src/qt/CMakeFiles/yabause-qt.dir/all'
make[1]: *** [src/qt/CMakeFiles/yabause-qt.dir/all] Error 2
Makefile:149: fallo en las instrucciones para el objetivo 'all'
make: *** [all] Error 2

**Comment by devmiyax** [comment]
fxied with https://github.com/devmiyax/yabause/commit/d4ee12331a4b94495df247cc15870ae14da51bae

**Comment by corvusd** [comment]
I tried the current master and not work:

**Comment by corvusd** [comment]
Workaround here fix the problem:
https://github.com/devmiyax/yabause/issues/601
Greetings!

**Comment by devmiyax** [comment]
This branch has been mergred into master and need to be deleted.
