### ISSUE TITLE
[Stellar Assault SS] Not start

### ISSUE THREAD

**Issue by corvusd** [devmiyax/yabause#566]
This game not start with any configuration. Real BIOS or Emulated BIOS. SH2 Interpreter or Dynamic Recompiler.

Is a curious game. Because have a special option for interleaved. And we don’t know if is for a Hi-Res mode vertical(even horizontal) resolution. Or for 30 or 60FPS.

Thanks for your awesome work! :)

**Comment by devmiyax** [comment]
Inifinity loop at 0x0600C144 - 0x0600C152

@ 0600C14C mov.b @r5, r0
r5 = 0x2605a968

**Comment by devmiyax** [comment]
0x0600ED2C: mov r15, r14
0x0600ED2A: bt/s 0x0600ED32  <== wrong jump
0x0600ED28: tst r1, r1
0x0600ED26: exts.b r1, r1
0x0600ED24: mov.b @r1, r1
0x0600ED22: or r2, r1
0x0600ED20: mov.l @(0x03C, pc), r2 ; 0x0600ED5C
0x0600ED1E: mov.l @(0x03C, pc), r1 ; 0x0600ED58
0x0600ED1C: mov.l r14, @-r15

**Comment by devmiyax** [comment]
DrawEnd(4d) at frame 498:45
scu	: IMS = FFFFFF7C PC=6000918 frame=498:46
[CPU WRITE] 2607C966, 00000000 PC = 0600E87A
[CPU WRITE] 2607C967, 00000000 PC = 0600E87E
scu	: IMS = FFFFD77C PC=6000942 frame=498:46

**Comment by devmiyax** [comment]
Starting. VDP1 need to keep running until fetch end code.
![image](https://user-images.githubusercontent.com/1174152/66716742-54215680-ee0c-11e9-8256-7553a92ddbee.png)

**Comment by devmiyax** [comment]
seems fully playable.
![Uploading image.png…]()

**Comment by devmiyax** [comment]
![image](https://user-images.githubusercontent.com/1174152/66716803-0527f100-ee0d-11e9-8641-adcb2d0d7fa4.png)
