### ISSUE TITLE
Sonic 3D: Flickies' Island: Special stage won't work

### ISSUE THREAD

**Issue by turboboy215** [devmiyax/yabause#567]
On both Windows and Android, Yaba Sanshiro crashes while attempting to load a special stage in Sonic 3D: Flickies' Island (to reproduce this, get 50 or more rings in the first leve and then find Tails and contact him). What I mean by "crashes" is that the application just gives up and closes, with no warning on Windows and "Yaba Sanshiro has stopped" on Android. RetroArch's beetle-Saturn core doesn't have this problem, so I don't have a bad image. Can you please fix this?

**Comment by natelawrence** [comment]
I placed [a $50 bounty](https://www.bountysource.com/issues/65732627-sonic-3d-flickies-island-special-stage-won-t-work) on this issue this morning over at BountySource. 

If anyone else would like to add an amount of their choosing to sweeten the deal for capable programmers, just follow the link.

**Comment by natelawrence** [comment]
I did notice yesterday while searching for videos of Saturn Sonic 3D Special Stages on YouTube to share the link to Bounty Source to that nearly 7 years ago Yabause did have these special stages working. Saturn Memories also pointed this out to me on Twitter. 

Here are two videos demonstrating: 
https://www.youtube.com/watch?v=1QAvuJpXN3g&t=2m55s

https://www.youtube.com/watch?v=VmMmfqBud8g&t=2m52s

**Comment by nicolas-charrier** [comment]
Special stages were working until uoyabause 0.5.2. They crash in uoyabause 0.5.5.
Same behaviour with real and emulated bios.
Tested with a japanese CD.

For any dev wanting to look into this, special stages are working in Kronos, a fork of uoyabause :
![Capture_sonic3D_special_stage_emeraude](https://user-images.githubusercontent.com/7624262/62330424-f346db00-b4b8-11e9-8ee5-756a9ddf36bc.PNG)

**Comment by nicolas-charrier** [comment]
In uoyabause 0.5.2 WIP dated 06/08/2017, several graphic problems appear, but special stages don't crash yet (sprites layer is no longer displayed however). So the crash was likely introduced between this version and 0.5.5 dated 27/08/2017.

Special stages are not crashing Kronos as early as the first version dated 21/02/2018.

**Comment by devmiyax** [comment]
Fixed
https://youtu.be/_jgHJGnUGmw

**Comment by nicolas-charrier** [comment]
In Windows v2.10.0, with emulated or real bios, the special stages are crashing Yaba Sanshiro.
