### ISSUE TITLE
[Request] CHD Support

### ISSUE THREAD

**Issue by ToppestOfDogs** [devmiyax/yabause#568]
Are there any plans to add CHD support? They're my preferred format because I like to have just one file per game, and the compression is nice.

**Comment by thatman84** [comment]
I would like this also, i am part a a few retro gaming enthusiast groups with many people that would love to see CHD support.

A comment from the developers either for or against would be awesome.

**Comment by farmerbb** [comment]
I'd also love to see CHD support added to Yaba Sanshiro 🙂

**Comment by devmiyax** [comment]
Done.
https://github.com/devmiyax/yabause/commit/fc2ece5a0b3e3ac75aec19dd5fb514035d405b29
