### ISSUE TITLE
[Grandia] bad sea graphics

### ISSUE THREAD

**Issue by devmiyax** [devmiyax/yabause#569]
![image](https://user-images.githubusercontent.com/1174152/50051723-a21ced80-015a-11e9-8934-164094d5add8.png)

**Comment by devmiyax** [comment]
![image](https://user-images.githubusercontent.com/1174152/50051891-0f7e4d80-015e-11e9-9e11-6c1635150089.png)

**Comment by devmiyax** [comment]
![image](https://user-images.githubusercontent.com/1174152/50051928-f4f8a400-015e-11e9-90ad-9fc303ee3cf7.png)

**Comment by devmiyax** [comment]
regression check
![image](https://user-images.githubusercontent.com/1174152/50052238-5ff8a980-0164-11e9-899b-f7d693db6c57.png)

**Comment by BenjaminSiskoo** [comment]
What is the name of this game ?!?

**Comment by devmiyax** [comment]
This game is called GRANDIA. the most beautiful RPG game, I think.

**Comment by BenjaminSiskoo** [comment]
The picture (regression check) come from Grandia !!! Never played

**Comment by devmiyax** [comment]
Nope, The picture for regression check is 'PowerDrift'

**Comment by BenjaminSiskoo** [comment]
ok, a sega ages game. Thanks
