### ISSUE TITLE
Sound and Graphical Tearing (Game Crash) Soukuu no Tsubasa: Gotha World (Abrev)

### ISSUE THREAD

**Issue by ryangrg422** [devmiyax/yabause#572]
Silhoutte Mirage all close sprites / graphics such as the wooden logs with spikes have issues in which there is space between the graphics that does not exist on the Saturn making the one object consisting of various sprites appear as separate objects.

Burning Rangers the 3D sound environment is not present and instead all that is heard after the tutorial is the flames at full volume everywhere hissing creating issues in which explosions that cause damage can no longer be avoided as they rely on sound cues along with the space station falling apart. Q Sound. Muffled tutorial. Earlier fix was a step in the right direction, but only fixed a portion of the issue.

Gothaworld refuses to play after the first cutscene and one gets in the plane for the strategy part. This may occur due to polygons being scaled inward. 

DJ Wars Slight delay in sound generation.

Some models of the Saturn do NOT have the Motorola 68000. Figure SEGA's method around it. There is a second model of the SCSP. Multiple models of VDP2 not VDP1. SH-2 and common Hitachi understanding for Hitachi VDP1 and VDP2.

**Comment by devmiyax** [comment]
works fine on 2.7.5

![image](https://user-images.githubusercontent.com/1174152/65373251-e2933400-dcb5-11e9-9137-1f64edde2446.png)
