### ISSUE TITLE
No image issue: Senkutsu Katsuryu Taisen - Chaos Seed

### ISSUE THREAD

**Issue by JoeShen832** [devmiyax/yabause#573]
This game is correct at the front part of the introduction, but it will be no image at the same place. That time the FPS was 60, but tapping any button was useless. I almost be crazy with the issue, please fix it!

**Comment by devmiyax** [comment]
@JoeShen832 need more information. please attch the screenshot and describe as-is and to-be.

**Comment by devmiyax** [comment]
no response

**Comment by JoeShen832** [comment]
你好，我发现游戏运行到进入洞窟时会死机，没有画面和音乐

**Comment by JoeShen832** [comment]
![image](https://user-images.githubusercontent.com/34231618/65374718-86cda880-dcbf-11e9-930c-dd7194e6633b.png)
![image](https://user-images.githubusercontent.com/34231618/65374721-93ea9780-dcbf-11e9-95e5-303f9d6c40e8.png)

**Comment by JoeShen832** [comment]
到这里就没有画面和音乐
