### ISSUE TITLE
Groove on fight (Characters not shown in gfx)

### ISSUE THREAD

**Issue by skelton** [devmiyax/yabause#574]
Using all windows builds. Tried both interpreter and sh2 dynarec. All graphics are ok but characters are invisible so imposssible to play. Tested with iGPU graphics openGL 4.5 and NVidia GTX 1080, so I guess is a general issue,

**Comment by devmiyax** [comment]
![image](https://user-images.githubusercontent.com/1174152/64991538-04369900-d90d-11e9-932b-78ab5619e591.png)

**Comment by devmiyax** [comment]
no issue in 1.8.0
