### ISSUE TITLE
Center Nano GUI (Enhancement)

### ISSUE THREAD

**Issue by blisstik** [devmiyax/yabause#588]
For the Retro Arena platforms, when pressing SELECT to invoke the Nano GUI, it is located in the top left of the screen.

This request would be to **center** the nano GUI menu horizontally and vertically so its always located in the middle of the screen.

**Comment by devmiyax** [comment]
fixed flickers by https://github.com/devmiyax/yabause/commit/0c192efc4a65b04b4e4e486f5d7d79b269741af4#diff-55ca76d7f92fbf1f3af132dd85bcead4
