### ISSUE TITLE
[AMOK] Map gfx problem...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [devmiyax/yabause#59]
Left Picture - Yabause Devmiyax 10.04.2015 - Software Renderer
Right Picture - Yabause Devmiyax 10.04.2015 - OpenGL Renderer

Map is not displayed properly.

![amok_ingame](https://cloud.githubusercontent.com/assets/12481242/10267194/ef5405e4-6a8a-11e5-9062-4a4e72900cce.PNG)

**Comment by devmiyax** [comment]
Normal Sprite
x = 30, y = 55
Texture address = 00051620
Texture width = 64, height = 64
Texture read direction: Normal
Pre-clipping Enabled
User Clipping Enabled
Clipping Mode = 0
Transparent Pixel Enabled
Color mode: 4 BPP(16 color bank)
Color bank: 00059060
Color Calc. mode: Replace

0x0000b20d
‭1011001000001101‬
‭1000000000000000‬

               else if (pixel & 0x8000 && colormode)
               {
                  // 16 BPP               
                  u8 alpha = 0x3F;
                  if ((SPCCCS == 3) && TestBothWindow(Vdp2Regs->WCTLD >> 8, colorcalcwindow, i, i2) && (Vdp2Regs->CCCTL & 0x40))
                  {
                     alpha = colorcalctable[0];
                     if (Vdp2Regs->CCCTL & 0x300) alpha |= 0x80;
                  }
                  // if pixel is 0x8000, only draw pixel if sprite window
                  // is disabled/sprite type 2-7. sprite types 0 and 1 are
                  // -always- drawn and sprite types 8-F are always
                  // transparent.
                  if (pixel != 0x8000 || vdp1spritetype < 2 || (vdp1spritetype < 8 && !(Vdp2Regs->SPCTL & 0x10)))
                     TitanPutPixel(prioritytable[0], i, i2, info.PostPixelFetchCalc(&info, COLSAT2YAB16(alpha, pixel)), 0);
               }

**Comment by BenjaminSiskoo** [comment]
Perfect game fix :) Thank you
