### ISSUE TITLE
Assault Leynos 2 Black Screen

### ISSUE THREAD

**Issue by blisstik** [devmiyax/yabause#590]
For Retro Arena platforms, Assault Leynos 2 ends in a black screen. It would be very nice to get this one working as a priority. Thank you!

**Comment by devmiyax** [comment]
![image](https://user-images.githubusercontent.com/1174152/66690548-b4f54580-eccb-11e9-8857-bffd759f9e4c.png)

!

**Comment by blisstik** [comment]
On v2.8g it boots using HLE bios but once you start the game, it turns to black screen. Is there an upcoming update to make it run then? This is for the Odroid N2 RetroArena

**Comment by devmiyax** [comment]
Wait. I'm working for this.

**Comment by devmiyax** [comment]
dark and not trees
![Uploading image.png…]()

**Comment by devmiyax** [comment]
![image](https://user-images.githubusercontent.com/1174152/66690830-a3ad3880-eccd-11e9-906e-fae6aa88f1f2.png)

**Comment by blisstik** [comment]
Ahh awesome. I'm sure you'll figure it out

**Comment by devmiyax** [comment]
trees are shown.

![image](https://user-images.githubusercontent.com/1174152/66691885-9e9fb780-ecd4-11e9-93fd-0563ac10f842.png)

**Comment by devmiyax** [comment]
![image](https://user-images.githubusercontent.com/1174152/66696143-51d3d500-ed04-11e9-8768-53103c6b44b0.png)

**Comment by devmiyax** [comment]
Strings are not should be transparent.

**Comment by devmiyax** [comment]
looks perfect
![image](https://user-images.githubusercontent.com/1174152/66697235-beec6800-ed0e-11e9-8222-230b369ecba5.png)

**Comment by BenjaminSiskoo** [comment]
Nice, maybe your boot fixing should be fixed others not booting games :)

**Comment by devmiyax** [comment]
regression check
![image](https://user-images.githubusercontent.com/1174152/66697734-53f16000-ed13-11e9-8794-5d2d949c73ee.png)

**Comment by devmiyax** [comment]
compute shader version
![Base Profile Screenshot 2019 10 12 - 18 46 36 80](https://user-images.githubusercontent.com/1174152/66699445-e00a8400-ed21-11e9-9a82-b0823e96402d.png)

**Comment by blisstik** [comment]
Nice! How’s the FPS?

**Comment by blisstik** [comment]
Updated to 2.8.2 on the Odroid N2, it boots but once you get into game start, it turns to black screen.
