### ISSUE TITLE
Cloud save could not be copied to the internal storage

### ISSUE THREAD

**Issue by samxchan1021** [devmiyax/yabause#595]
Hi , I have tried to copy the save from the cloud to internal / External Storage. 
However it is no luck. Nothing shown in the save list as the video stated.. 
[20190430_234047.mp4.zip](https://github.com/devmiyax/yabause/files/3183573/20190430_234047.mp4.zip)

**Comment by devmiyax** [comment]
@samxchan1021  do you have this problem still? I cannnot reproduce this issue.

**Comment by samxchan1021** [comment]
Sorry for the late reply.  The issues is fixed and i would close this issue
