### ISSUE TITLE
Crosscompiling for Amlogic S905/Odroid N2  ARM 32bits

### ISSUE THREAD

**Issue by shantigilbert** [devmiyax/yabause#596]
I am trying to cross-compile so I can use it on Amlogic S905/Odroid N2, I see that the Odroid N2 cmake rules use aarch64, so I am using the XU4 options which uses ARM.

This is the error I get: 

```
[100%] Linking CXX executable yabasanshiro
../libyabause.a(yglshaderes.c.o):yglshaderes.c:function Ygl_uniformVdp1CommonParam: error: undefined reference to 'glMemoryBarrier'
collect2: error: ld returned 1 exit status
```
if I remove the call to glMemoryBarrier 

`sed -i "s|if( glMemoryBarrier )|if( NULL )|" yabause/src/yglshaderes.c `

it finishes compiling and linking but running the binary on either the S905 or the Odroid N2 results in a "Illegal instruction" and exits.

To be able to cross-compile we had to change m68kmake and bin2c so that they compile on the host machine and use the resulting host binaries

```
sed -i "s|COMMAND m68kmake|COMMAND $PKG_BUILD/m68kmake_host|" yabause/src/musashi/CMakeLists.txt
sed -i "s|COMMAND ./bin2c|COMMAND $PKG_BUILD/bin2c_host|" yabause/src/retro_arena/nanogui-sdl/CMakeLists.txt
```

These are basically all the options I am using

```
  PKG_CMAKE_OPTS_TARGET="$PKG_BUILD/yabause \
                         -DYAB_PORTS=retro_arena \
                         -DYAB_WANT_DYNAREC_DEVMIYAX=ON \
                         -DCMAKE_TOOLCHAIN_FILE=$PKG_BUILD/yabause/src/retro_arena/xu4.cmake"

  PKG_CMAKE_OPTS_TARGET+=" -DOPENGL_INCLUDE_DIR=$SYSROOT_PREFIX/usr/include \
                           -DOPENGL_opengl_LIBRARY=$SYSROOT_PREFIX/usr/lib \
                           -DOPENGL_glx_LIBRARY=$SYSROOT_PREFIX/usr/lib \
                           -DBOOST_INCLUDEDIR=$SYSROOT_PREFIX/usr/include"

  export CFLAGS="$CFLAGS -O2 -march=armv8-a+crc -mtune=cortex-a73.cortex-a53 -ftree-vectorize -funsafe-math-optimizations -pipe"
  export CXXFLAGS="$CXXFLAGS -lEGL -lGLESv2 -lGLESv3 -ftree-vectorize -funsafe-math-optimizations -pipe"
```

Any idea how I can compile this so that it runs on Amlogic S905/Odroid N2 ARM 32bits?

Thanks!

**Comment by devmiyax** [comment]
I have no idea. If you send me a borad I'll try.
