### ISSUE TITLE
Linux Qt build does not compile

### ISSUE THREAD

**Issue by andrewmackrodt** [devmiyax/yabause#601]
## undefined reference to 'PERLinuxJoy'
`CMakeFiles/yabause-qt.dir/QtYabause.cpp.o:(.data.rel+0x58): undefined reference to 'PERLinuxJoy'`

[CMakeLists.txt](https://github.com/devmiyax/yabause/blob/3e19fff/yabause/src/CMakeLists.txt#L816) performs a check `if (!ANDROID)` before including the joystick header files. This always evaluates to false (on my machine at least). Changing it to `if (${CMAKE_SYSTEM_NAME} MATCHES "Linux")` fixes the issue.

**Debug Workaround**
`sed -i -E 's/if ?\( ?! ?ANDROID\)/if (${CMAKE_SYSTEM_NAME} MATCHES "Linux")/' yabause/src/CMakeLists.txt`

---

## 'asm' undeclared
`libchdr-prefix/src/libchdr/deps/flac-1.3.2/src/libFLAC/cpu.c:91:2: error: 'asm' undeclared (first use in this function)`

[CMakeLists.txt](https://github.com/devmiyax/yabause/blob/3e19fff/yabause/src/CMakeLists.txt#L878) uses `-std=c11` when `arch=aarch64` but compiling flac requires gnu extensions for assembly compilation, i.e. `-std=gnu99`.

**Debug Workaround**
sed -i -E 's/-std=c11/-std=gnu99/' yabause/src/CMakeLists.txt

---

## cannot find -lchdr-static

    /usr/bin/ld: cannot find -lchdr-static
    /usr/bin/ld: cannot find -lflac-static
    /usr/bin/ld: cannot find -lcrypto-static
    /usr/bin/ld: cannot find -llzma-static
    /usr/bin/ld: cannot find -lchdr-static
    /usr/bin/ld: cannot find -lflac-static
    /usr/bin/ld: cannot find -lcrypto-static
    /usr/bin/ld: cannot find -llzma-static

[CMakeLists.txt](https://github.com/devmiyax/yabause/blob/b415049/yabause/CMake/Packages/external_libchdr.cmake#L40) makes use of undefined vars `CMAKE_STATIC_LIBRARY_PREFIX` and `CMAKE_STATIC_LIBRARY_SUFFIX`.

**Debug Workaround**
`sed -i 's/${CMAKE_STATIC_LIBRARY_PREFIX}/${BINARY_DIR}\/lib/' yabause/CMake/Packages/external_libchdr.cmake`

**Comment by andrewmackrodt** [comment]
Introduced in this commit: https://github.com/devmiyax/yabause/commit/7bb918fd9b8f6201b0464e4a8c25649a29ec7c82

**Comment by mrcmunir** [comment]
I can confirm this if(!ANDROID) this will never work beucause returned always false .

**Comment by BorjaRRR** [comment]
I have this error in linux

`[100%] Linking CXX executable yabasanshiro
/usr/bin/ld: ../libyabause.a(osdcore.c.o): undefined reference to symbol 'glVertex2i'
/usr/bin/ld: /usr/lib/libGL.so.1: error al añadir símbolos: DSO faltante desde línea de orden
collect2: error: ld devolvió el estado de salida 1
make[2]: *** [src/qt/CMakeFiles/yabause-qt.dir/build.make:1661: src/qt/yabasanshiro] Error 1
make[1]: *** [CMakeFiles/Makefile2:239: src/qt/CMakeFiles/yabause-qt.dir/all] Error 2
make: *** [Makefile:152: all] Error 2`

I'm building with
`cmake -DYAB_USE_QT5=FALSE -DYAB_WANT_DYNAREC_DEVMIYAX=TRUE ../yabause
make`

**Comment by corvusd** [comment]
Same for me in this issue:
https://github.com/devmiyax/yabause/issues/565

**Comment by corvusd** [comment]
With your workarounds work like charm! Thanks!! :)

**Comment by corvusd** [comment]
Still not compile form master @devmiyax . It is necessary still apply this workaround. And plus the Recompiler SH2 not is compilated and the framerate not arrive to max. it always at half 30/60FPS VDP1=30 in a game that run at 60FPS in windows same version.
