### ISSUE TITLE
[TEST] yabasanshiro-2.5.0-c4cd45.zip 2019/05/27

### ISSUE THREAD

**Issue by CloudFR** [devmiyax/yabause#602]
Hi,
I'am newbie.
Sorry for my bad english before.
I tested your last update for yabasanshiro-2.5.0-c4cd45.zip 2019/05/27.

My specs :
windows 7 64 bits
x6 3.20 ghz
4go ram
gtx 1050ti

My first question is : are tested your release before ?
I report several bugs on this version.

1) bug switch fullscreen / windows display when i toggle. The display is not fullscreen or sometimes the display too much large for my screen. 
2) when i change the sound core in games (osd / directx), i crash.
3) i very interessing for play like HD, i tested all graphicals options, any works for me (is see any difference).
3.1) checkbox bilineare filtering (reboot required) => is see not difference
3.2) filter (fxaa, scanline, bilineare) => not work or i see not difference
3.3) tesselation => i dont know if its work, i see any difference
3.4) internal resolution => is see not difference between native and 1080p
3.5) RGB resolution => it seems working, my pc slow down in 1080p in display but i see not diference of textures or polygones between native and 1080p
3.6) use compute RGB generation => fast up my pc with RGB resolution in 1080p, it seems working
3.7 rotate 90 degrees => it's work !
4) show FPS => not work

Thanks for you job

**Comment by mrcmunir** [comment]
Apparently the show FPS option only works for me when select nanovg OSD interface .
And I can confirm the bug in the fullscreen or switch windows not correctly display .
Also I have sometimes bug in the system may hang up waiting for a busy thread. I don't know why

**Comment by devmiyax** [comment]
Sorry, all of them are as-is. I want to focus other issue. if you want, you can PR to me.
