### ISSUE TITLE
Android TV: cannot delete saved game directory in directory list

### ISSUE THREAD

**Issue by enodr** [devmiyax/yabause#617]
The delete button can only be used with a touch device in the list of saved games directories. On Android TV (NVIDIA Shield TV for example), you cannot delete a saved directory. A simple UI design change would fix the problem.

**Comment by devmiyax** [comment]
press B

**Comment by enodr** [comment]
B is "back" at least on the Nvidia Shield TV. Still cannot delete game directory.
