### ISSUE TITLE
Wrong 4:3 aspect ratio

### ISSUE THREAD

**Issue by ivanmestre** [devmiyax/yabause#619]
On the latest 2.6.6-d245e3 Windows build and 2.4.0 Android build the 4:3 aspect ratio is wrong. On windowed mode the aspect ratio is 4:3 with black bars on top and bottom, same as Android 2.6.4. On full screen the black bars are gone but the image is not 4:3, it's wider and stretched.

Windows 2.6.6-d245e3 build
![yabasanshiro exe Screenshot 2019 08 08 - 19 16 49 73](https://user-images.githubusercontent.com/6786286/62741574-cc852900-ba11-11e9-8563-8f55fee40e66.png)
![yabasanshiro exe Screenshot 2019 08 08 - 19 18 17 13](https://user-images.githubusercontent.com/6786286/62741575-cc852900-ba11-11e9-8f4f-311d9e4235d1.png)

Android 2.6.4 build
![Screenshot_20190808-193217](https://user-images.githubusercontent.com/6786286/62742056-7a450780-ba13-11e9-8c53-881f14139846.png)

Probably caused by this commit: https://github.com/devmiyax/yabause/commit/6def107209462f786b269608576b2f71e3351d28

**Comment by ivanmestre** [comment]
After the Android 2.6.6 update it now behaves in the same way as the Windows build on full screen. The image is wider than 4:3 and is stretched.

**Comment by devmiyax** [comment]
dupe #628
