### ISSUE TITLE
Compiling for macOS ? 

### ISSUE THREAD

**Issue by azoreseuropa** [devmiyax/yabause#623]
I compiled many emulators for macOS with an instruction. I need this instruction for macOS, please ?

**Comment by azoreseuropa** [comment]
Hello ??

**Comment by devmiyax** [comment]
Humm.. I need to buy Mac for your request.  :)

**Comment by azoreseuropa** [comment]
> Humm.. I need to buy Mac for your request. :)

Hi. I hope someone can help you with that. Keep up the good work!

**Comment by thebunnyrules** [comment]
I don't own a Mac but it should be close enough to linux.

go to yabause/src/android/app

make a file called local.properties. There should be two lines in this file that point to your ndk.dir and your sdk.dir. In linux it's

ndk.dir=/home/username/Android/Sdk/ndk-bundle
sdk.dir=/home/username/Android/Sdk

Don't cut and paste this, adjust to your system.

Once all of that is done, run:
chmod +x gradlew #this might be different in Mac, use google 
./gradlew #sets up gradle
./gradlew tasks #lists your build options

./gradlew assembleDebug 
#probably your best bet , just make sure it's listed in the ./gradlew tasks output.

**Comment by azoreseuropa** [comment]
> I don't own a Mac but it should be close enough to linux.
> 
> Install a variant of JDK8 (either openjdk8 or Oracle Java JDK 8). Google is your creepy friend.
> 
> Get NDK r10e for mac os x. Use that in local.properties below. NDK 20 seems to bug out with this code.
> 
> go to yabause/src/android
> 
> make a file called local.properties. There should be two lines in this file that point to your ndk.dir and your sdk.dir. In linux it's
> 
> ndk.dir=/home/username/Android/Sdk/ndk-bundle
> sdk.dir=/home/username/Android/Sdk
> 
> Don't cut and paste this, adjust to your system.
> 
> Once all of that is done, run:
> chmod +x gradlew
> #this might be different in Mac, use google to find how to make a script executable in Mac
> 
> ./gradlew #sets up gradle
> ./gradlew tasks
> #lists your build options
> 
> ./gradlew assembleDebug
> #probably your best bet , just make sure it's listed in the ./gradlew tasks output.

Thanks but I will pass. :)

**Comment by thebunnyrules** [comment]
Don't worry about it. It's not like I took a shit ton of time out of my busy life and went out of my way to painstakingly make you a tutorial or anything like that ...
