### ISSUE TITLE
Sonic 3d Blast - black screen with dynamic recompiler

### ISSUE THREAD

**Issue by Deivmsr** [devmiyax/yabause#626]
Sonic 3d Blast still has black screen issues on start screen when using "new dynamic recompiler". Would it be possible to fix this? Because the game does not run well when using the interpreter.

I'm using Galaxy Note 8, with Exynos processor, Mali G71 GPU, Android 9.0.

**Comment by devmiyax** [comment]
fixed by fc22add81ca909c181b9baa659f882fcbb0ef67c
