### ISSUE TITLE
Glitched cars in Daytona USA & freezing on Arcade mode select

### ISSUE THREAD

**Issue by Cee123** [devmiyax/yabause#631]
The cars are glitched in Daytona USA. What used to run perfectly now looks like this
![ice_screenshot_20190828-103455](https://user-images.githubusercontent.com/43462099/63821457-ace18080-c97f-11e9-8380-aaa5584aaa0c.png)

Also, there is a bug in Arcade/Saturn mode selection screen. Where if you accidentally hit the back button and it goes back to the title screen and then you re-enter the the screen to choose either Arcade mode or Saturn mode, it will freeze.

**Comment by devmiyax** [comment]
What version do you use? It seems old.

**Comment by barbudreadmon** [comment]
@devmiyax seems like the same issue you mentioned to me when i implemented redump isos

Well, i would think it's either a corrupted dump, or a bad gl driver (@Cee123 intel gpu ?)

**Comment by Cee123** [comment]
@devmiyax um, I just checked the version. It's version 2.6.8 9d1dea1 (nightly version I think from the 27th). It seems to be doing that on the Odroid XU4 as well, with both the standalone and libretro versions.

**Comment by Cee123** [comment]
@barbudreadmon Not sure. It could be a corrupt dump of Daytona USA. Strange that the Odroid XU4 does it as well with both standalone and libretro versions. I tried another dump of Daytona and same thing, which is strange.

Um, graphics card. It's a NVIDIA Geforce GTX 1060 6gb. Not really sure it could be the drivers.

**Comment by barbudreadmon** [comment]
> Um, graphics card. It's a NVIDIA Geforce GTX 1060 6gb

Is it a 32bit setup ? 32bit devices are the only thing i didn't test (i can't reproduce your issue with any daytona usa dump nor device/OS).

**Comment by Cee123** [comment]
> 
> 
> > Um, graphics card. It's a NVIDIA Geforce GTX 1060 6gb
> 
> Is it a 32bit setup ? 32bit devices are the only thing i didn't test (i can't reproduce your issue with any daytona usa dump nor device/OS).

I'm using 64-bit Windows 10. Not sure if that's the question. It seems to do it on Odroid XU4 as well, using the Retro Arena. Seems to be even worse. This is the photo I took of XU4 running libretro Yaba Sanshiro 2.6.8.

![GetAttachmentThumbnail](https://user-images.githubusercontent.com/43462099/63846240-fc46a180-c9bd-11e9-8665-39b47200f359.jpg)

And Metal Slug

![GetAttachmentThumbnail](https://user-images.githubusercontent.com/43462099/63846285-108a9e80-c9be-11e9-98fe-5367d513e675.jpg)

You said you couldn't reproduce the issue. So it could be the dump. Maybe I could try a different version or even a few different versions. There are probably some bad dumps around.

**Comment by Cee123** [comment]
@barbudreadmon Oh my god! You were right! It was more than likely the dump that was bad. I just tried another dump from a different website and it looks fine now.

![ice_screenshot_20190828-184839](https://user-images.githubusercontent.com/43462099/63849418-a0cbe200-c9c4-11e9-8457-9c492ee51e3b.png)

**Comment by Cee123** [comment]
The issue was due to a bad dump/version of Daytona USA. Found across a few different websites.

**Comment by barbudreadmon** [comment]
Just curious, what's the exact filename of the dump that wasn't working ?

**Comment by Cee123** [comment]
@barbudreadmon Just "Daytona USA.iso" it also had a Daytona USA.cue and Daytona USA.DWT.

Then I tried another one and that was also called Daytona USA.iso and had a bunch of .mp3 files with it.

**Comment by barbudreadmon** [comment]
ok, maybe there is some kind of regression with `.iso` files then (idk about the `.dwt` files either)

**Comment by Cee123** [comment]
I'm not sure because all my other ISOs seem to work fine. Except maybe one or two.
