### ISSUE TITLE
2.7.4 Fails to acknowledge R-BG Resolution + Compute Shader at Game Launch

### ISSUE THREAD

**Issue by natelawrence** [devmiyax/yabause#632]
I noticed 24 hours ago that on Yaba Sanshiro **2.7.4** on Windows: 
- _R-BG Resolution '**Fit to Emulation Resolution**'_ and 
- _Compute Shader **ON**_ 
settings are _not acknowledged when launching a game_. 

After you have booted a game, you may: 
- open Video Settings, 
- toggle the R-BG Resolution setting to a lower/different value
- toggle Compute Shader setting to OFF
- apply settings
- open Video Settings 
- toggle R-BG resolution setting back to the resolution you desire, 
- apply settings
- open Video Settings
- toggle Compute Shader setting to ON
- apply settings
but this will have to be repeated with every new game opened. 

This is quite tedious when attempting to boot many titles consecutively to test whether the current R-BG Resolution method is successful at increasing R-BG Resolution in-game.

According to my testing, the prior Windows build of Yaba Sanshiro (2.7.1) does not have this bug.

**Comment by thebunnyrules** [comment]
There is a typo in the 2.7.4 YabauseSettings.java in line 420. I think the bug is related to this.

**Comment by devmiyax** [comment]
fixed by 257305f
