### ISSUE TITLE
Game crash on Odroid N2 2GB RAM version but stable in 4GB RAM version

### ISSUE THREAD

**Issue by dewenhsu** [devmiyax/yabause#634]
Use lr-yanasanshiro 2.6.8 or standalone 2.7.4, in Odroid N2 2GB ram version, it will crash,
for example, Blast Wind, if you use frame skip and higher resolution, it will crash soon,, more often on standalone version.
Is that due to out of memory on 2GB Odroid N2 ? Can it be fixed ?
Thank you !

**Comment by devmiyax** [comment]
I think it's heat problem. can you try cooler?

**Comment by dewenhsu** [comment]
Try add usb fan for cooling but no effect. I think it’s hardware issue and send it back for RMA, still waiting the result, thank you.

**Comment by devmiyax** [comment]
hardware issue
