### ISSUE TITLE
Android Build: could not find method crashlytics() fatal error during gradle config/sync

### ISSUE THREAD

**Issue by thebunnyrules** [devmiyax/yabause#635]
Gradle is exiting with this error just short of 100% completion of sync/config:

could not find method crashlytics() for arguments [build_dm7....] on project ':app' of type org.gradle.api.Project

I've tried in both cli/gradlew and Android Studio with Fabric for IDE plugin installed (Fabric should load Crashlytics during the sync).  Neither approach worked. I've tried syncing both master and v2.7 (both with same result)

What am I missing here? Any ideas?

**Comment by Cwiiis** [comment]
For what it's worth, you can just comment out that whole section and it will build and run fine. I assume crashlytics is only necessary for sending crash reports, which you wouldn't want to do for a custom build anyway.

**Comment by devmiyax** [comment]
does not reproduce
