### ISSUE TITLE
Goiken Muyou - SFX and voices sped up

### ISSUE THREAD

**Issue by le-capitaine** [devmiyax/yabause#637]
Don't think it's been mentioned yet since it's such an obscure game. SFX and voices are played sped up, as if at the wrong frequency.

**Comment by natelawrence** [comment]
Herc's Adventures by LucasArts has a similar problem. 
I don't know if it's technically related or the two examples are separate issues.

**Comment by devmiyax** [comment]
no issue 1.8.0
