### ISSUE TITLE
Use the software display interface with the black screen! 

### ISSUE THREAD

**Issue by metalmax2** [devmiyax/yabause#638]
Yaba Sanshiro ver.2.7.5
OS:Win7 SP1
If I use the software video interface to start game, there is the black screen, but voise is normal. When I use back the openGL video
![001](https://user-images.githubusercontent.com/55258393/64819268-7131f200-d5e0-11e9-830f-8cb57a6a0dd5.png)
![002](https://user-images.githubusercontent.com/55258393/64819270-7131f200-d5e0-11e9-8e61-af6cea71fe78.png)
![003](https://user-images.githubusercontent.com/55258393/64819271-71ca8880-d5e0-11e9-879d-a584b7a984ba.png)
![004](https://user-images.githubusercontent.com/55258393/64819273-71ca8880-d5e0-11e9-8d6a-abbfc9c2c22d.png)

 interface, the display is normal.

**Comment by devmiyax** [comment]
I don't support software rendering mode any more.
