### ISSUE TITLE
[Several Games] Yabause crashes...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [devmiyax/yabause#64]
Left Picture : Yabause Devmiyax 2015.10.04
Right Picture : Yabause Devmiyax 2015.11.22

Hello Devmiyax,

Yabause crash at the character selection (Battle Arena Toshiden Remix (E)).
Yabause crash at the start of Alone In The Dark One Eyed Jack (E). 
Yabause crash at the start of Chaos Control (E).
Yabause crash at the start of Contra Legacy Of War (U).
Yabause crash at the start of Crows The Battle Action (U).
Yabause crash at the start of Slam And Jam  (U).

By the war, thanks for all yours fixes :) I'm really happy to see Yabause improve.

**Comment by devmiyax** [comment]
this issue may be fixed by 
https://github.com/devmiyax/yabause/commit/9a8e9e1396f5f43ae2a7ccb4463db7668d766791

**Comment by BenjaminSiskoo** [comment]
Nope, even this game crash :)

**Comment by BenjaminSiskoo** [comment]
Seems good now :)
