### ISSUE TITLE
Shining the Holy Ark flickers intermittently with parts of previous rendered frames

### ISSUE THREAD

**Issue by Cwiiis** [devmiyax/yabause#646]
This seems intermittent, but highly reproduceable on a GPD XD Plus. It can happen at all times, but is most evident during menu screens or battle where the screen content is changing. The regions usually correspond to bits of the screen that are updating, but very rarely I get large rectangles of the screen that won't update for some arbitrary amount of time. You can see it in this video, https://photos.app.goo.gl/L7ySBHwZwpTTu9u18 (from about 0:12 when Rodi attacks).

I'm using the GL renderer at native (720p) resolution with CPU polygon tessellation and the RBG compute shader disabled, but this issue also happens at original resolution. At the original resolution, I also notice some corruption around sprites during attack animations. I tested with the software video core, but it's too broken to really compare. If I enable the RBG compute shader, it seems to happen more readily, but that also causes issues for me in other games, so I assume the device isn't properly capable of this feature (or some driver issue is affecting it).

**Comment by Cwiiis** [comment]
I isolated this to only happening when RBG resolution is anything except native OR when RBG compute shader is on. If you leave the compute shader off and set RBG resolution to native, everything operates as normal. This is a bit of a shame though as not using the shader tanks performance too. Seems the compute shader just doesn't really work on this platform... If you'd be willing, I'd love to help debug this.

**Comment by Cwiiis** [comment]
Correction, this happens if the RBG resolution is original and/or RBG compute shader is on. Setting RBG resolution to 2x with shader off also fixes the issue without having quite as dramatic an effect on performance.

**Comment by devmiyax** [comment]
This is known issue cased by GPU driver's bug.
https://github.com/devmiyax/yabause/issues/484

Contact to Shanzen to update GPU driver.
https://www.gpd.hk/contact

**Comment by devmiyax** [comment]
This link is to the discussion with guys in Imagination Technologies(GPU maker).
https://forums.imgtec.com/t/eglswapbuffers-displays-before-rendering-has-finished/2575/14

**Comment by Cwiiis** [comment]
Is there any chance you'd consider implementing the work-around mentioned in comment #7 of that discussion? I very much doubt am updated driver will be made available by GPD/MTK for this platform and it's a shame given the performance penalty this incurs. 

Alternatively, I suppose a Vulkan backend may not hit this driver bug - is that something that's in the works?

**Comment by devmiyax** [comment]
I've already implmented #7 but there is no improvement.
https://github.com/devmiyax/yabause/blob/master/yabause/src/ygles.c#L600

**Comment by Cwiiis** [comment]
I see... Why does this work if RBG resolution is 2x or above? Is this just a side effect of increasing the amount of processing and avoiding a race condition? Is there the possibility of another work-around? Perhaps a fence or sync somewhere? Or even a customisable delay?

**Comment by Cwiiis** [comment]
I've not read the code enough to know what's going on at this point, but I do notice that one instance of glMapBufferRange is missing GL_MAP_UNSYNCHRONIZED_BIT (in VIDOGLVdp1ReadFrameBuffer, line 1001).

**Comment by Cwiiis** [comment]
I'm just skimming, trying to see why this bug only manifests when RBG is at original resolution, or when the compute shader is used - it doesn't look like the original res path is really any different from any of the other modes, so I'm guessing it is a race condition - where if VDP2 rendering finishes before some certain point (I guess VDP1 rendering and/or any other rendering that ought to be composited over the top of the RBG?) that we end up seeing incomplete rendering due to the faulty implementation of glMapBufferRange.

Could this be worked around by using mutexes and either sync objects (https://www.khronos.org/opengl/wiki/Sync_Object) or glFinish perhaps? I don't suppose you could give me some pointers as to the rendering order? It's a little tricky reading through this code (I do have some small Saturn knowledge from previous Yabause contributions)

**Comment by Cwiiis** [comment]
I also guess that another possible (but unfortunate) work-around would also be to have an option to disable async RBG drawing - using the compute shader and having synchronous RBG rendering may better than forcing slow RBG rendering on the XD+ on a separate thread, perhaps?

**Comment by Cwiiis** [comment]
Although I see that with the compute shader enabled, asynchronous rendering is disabled, so I suppose the CPU-side threads aren't the problem here, so much as the lack of GPU synchronisation. I'll see if I can get an environment setup where I can test some hypotheses.

**Comment by Cwiiis** [comment]
I have it building on Linux, Android proving a little trickier but hopefully I'll get it going soon...
