### ISSUE TITLE
Background doesn't clear between frames on Shining the Holy Ark in 2.8.2

### ISSUE THREAD

**Issue by Cwiiis** [devmiyax/yabause#647]
This is a new regression in 2.8.2 that didn't exist in 2.8.1 - if you have the rendering resolution set to anything except native on the GPD XD+, the background doesn't clear correctly.

Screenshot: https://photos.app.goo.gl/jkEysxwEENvAkyMG6

I expect this may be another manifestation of the broken glMapBufferRange driver bug.

**Comment by Kaffeebohnson** [comment]
Is this related to the visual bugs I encountered in Panzer Dragoon Saga after 2.8.2? https://github.com/devmiyax/yabause/issues/651

**Comment by Cwiiis** [comment]
> Is this related to the visual bugs I encountered in Panzer Dragoon Saga after 2.8.2? #651

Yup, looks like the same thing.

**Comment by Cwiiis** [comment]
Fixed in 2.9.
