### ISSUE TITLE
[FIXES FROM YABAUSE OFFICIAL] Could be merged ?

### ISSUE THREAD

**Issue by BenjaminSiskoo** [devmiyax/yabause#66]
Fix Vdp1 framebuffer effects in Scorcher :
https://github.com/Yabause/yabause/commit/0e332e450717d46c8c0250a059dcbbe064b4719d

Fix Chase HQ and improve sprite window test  :
https://github.com/Yabause/yabause/commit/090cce8d87f17d7129b342fc0ffaf7378d746a06

**Comment by devmiyax** [comment]
It's need to implement using OpenGL
