### ISSUE TITLE
Various Games Flickering

### ISSUE THREAD

**Issue by blisstik** [devmiyax/yabause#668]
#666 

Stellar Assault SS (Japan) boots using Odroid N2 RetroArena but the gameplay has background flickers.

<img src="https://i.imgur.com/IZs9ee9.jpg">

**Comment by blisstik** [comment]
Update: flickering also happens on other games like Soukyu Gurentai Otokuyo (Japan) and Guardian Heroes (USA) on the Odroid N2

**Comment by Cwiiis** [comment]
I see similar-looking flickers occasionally in Shining the Holy Ark. When I was messing around locally on the 2.8 codebase, I could cause similar flickering by not initialising NBG data correctly.

**Comment by blisstik** [comment]
Still exists in v2.10

**Comment by blisstik** [comment]
Seems to be fixed with v2.10.4 #687
