### ISSUE TITLE
SHINING FORCE 3 SCENARIO 1      OHTO NO KYOSHIN                                                                 

### ISSUE THREAD

**Issue by devmiyax** [devmiyax/yabause#679]
version:0.4.1
device:Redmi Note 7 Pro
cpu_type:2
video_type:1
comment:
![screenshot](http://www.uoyabause.org//system/reports/screenshots/000/004/925/original/_storage_emulated_0_yabause_screenshots_GS-9175_2019_11_05_22_06_04.png?1572962767)

**Comment by FaeTalan** [comment]
Having the same issue on Windows 10, version 2.12.0, USA cue/bin files.

**Comment by devmiyax** [comment]
@FaeTalan can you attach the state save file when this issue is happend.

**Comment by slocolo** [comment]
I have this problem at the time of spells they do not appear is only blurred image on android xiaomi mi9t pro

**Comment by slocolo** [comment]
![Screenshot_2020-03-17-17-01-00-180_org uoyabause uranus pro](https://user-images.githubusercontent.com/62319552/76922175-bc3e0200-68ae-11ea-942f-9bf777c03d75.jpg)

**Comment by devmiyax** [comment]
state file please!

**Comment by slocolo** [comment]
https://m.coolrom.com.au/roms/saturn/8273/Shining_Force_III_-_Premium_Disc.php

**Comment by slocolo** [comment]
https://m.coolrom.com.au/roms/saturn/8273/Shining_Force_III_-_Premium_Disc.php estou mandando link nao sei se isso oq pediu 😅

**Comment by devmiyax** [comment]
@slocolo 
check out this video to know how to send bug report. we need the sate file attached by this instruction. 
confira este vídeo para saber como enviar um relatório de bug. precisamos do arquivo de estado anexado por esta operação.
https://www.youtube.com/watch?v=3k3OdHxhZiM&t=18s

**Comment by FaeTalan** [comment]
![Shining Force 3 Vol 1 Issue](https://user-images.githubusercontent.com/61858343/78294465-cc85ec00-7500-11ea-89f6-ac69366f54f6.png)

![Shining Force 3 Vol 1 Issue 1](https://user-images.githubusercontent.com/61858343/78294853-706f9780-7501-11ea-990a-a8b12c8177a8.png)

[GS-9188_002.zip](https://github.com/devmiyax/yabause/files/4423257/GS-9188_002.zip)
[GS-9188_003.zip](https://github.com/devmiyax/yabause/files/4423259/GS-9188_003.zip)

Problem still happening in 3.0. Files attached.

Games are looking awesome, by the way. Yaba Sanshiro is turning our Saturn emulation dreams into reality, so thank you very much!

**Comment by devmiyax** [comment]
not rotated bitmap. it seems VRAM is corrupted or start address is worng. 
![image](https://user-images.githubusercontent.com/1174152/79058283-01cfce00-7ca7-11ea-96b1-7ddc346bdc8c.png)

**Comment by devmiyax** [comment]
start line from 120th. 
![image](https://user-images.githubusercontent.com/1174152/79058333-a3571f80-7ca7-11ea-9d98-deb1e5099c96.png)

**Comment by devmiyax** [comment]
![image](https://user-images.githubusercontent.com/1174152/79061059-01472f80-7cc7-11ea-98f4-ad9872f9b2d0.png)

![image](https://user-images.githubusercontent.com/1174152/79061062-0b692e00-7cc7-11ea-9e01-9418a1ac72cf.png)

**Comment by devmiyax** [comment]
![image](https://user-images.githubusercontent.com/1174152/79061154-15d7f780-7cc8-11ea-8dec-21f600a52d09.png)

**Comment by devmiyax** [comment]
![image](https://user-images.githubusercontent.com/1174152/79061168-4d46a400-7cc8-11ea-89cd-19534db3fef8.png)

**Comment by devmiyax** [comment]
improved
![image](https://user-images.githubusercontent.com/1174152/79063509-20e95280-7cdd-11ea-8696-f1d789af064b.png)

**Comment by devmiyax** [comment]
Fully improved.
![image](https://user-images.githubusercontent.com/1174152/79064310-c81cb880-7ce2-11ea-98ce-9e5a5caae432.png)

**Comment by devmiyax** [comment]
Still this sciene is not improved.

![image](https://user-images.githubusercontent.com/1174152/79064362-319cc700-7ce3-11ea-8556-f33bd932db48.png)

**Comment by devmiyax** [comment]
memory from 00290004 to 00290100 is broken.

```
================= CPU DMA START =============== 
CPU DMA src:00290004 dst:25F00800 val:00000000
CPU DMA src:00290008 dst:25F00804 val:00000000
CPU DMA src:0029000C dst:25F00808 val:00000000
CPU DMA src:00290010 dst:25F0080C val:00000000
CPU DMA src:00290014 dst:25F00810 val:00000000
CPU DMA src:00290018 dst:25F00814 val:00000000
CPU DMA src:0029001C dst:25F00818 val:00000000
CPU DMA src:00290020 dst:25F0081C val:00000000
CPU DMA src:00290024 dst:25F00820 val:00000000
CPU DMA src:00290028 dst:25F00824 val:00000000
CPU DMA src:0029002C dst:25F00828 val:00000000
CPU DMA src:00290030 dst:25F0082C val:00000000
CPU DMA src:00290034 dst:25F00830 val:00000000
CPU DMA src:00290038 dst:25F00834 val:00000000
CPU DMA src:0029003C dst:25F00838 val:7FFF7FFF
CPU DMA src:00290040 dst:25F0083C val:00000000
CPU DMA src:00290044 dst:25F00840 val:00000000
CPU DMA src:00290048 dst:25F00844 val:00000000
CPU DMA src:0029004C dst:25F00848 val:00000000
CPU DMA src:00290050 dst:25F0084C val:00000000
CPU DMA src:00290054 dst:25F00850 val:7FFF84E2
CPU DMA src:00290058 dst:25F00854 val:7FFF0000
CPU DMA src:0029005C dst:25F00858 val:00000000
CPU DMA src:00290060 dst:25F0085C val:00000000
CPU DMA src:00290064 dst:25F00860 val:00000000
CPU DMA src:00290068 dst:25F00864 val:00000000
CPU DMA src:0029006C dst:25F00868 val:00000000
CPU DMA src:00290070 dst:25F0086C val:00000000
CPU DMA src:00290074 dst:25F00870 val:00000000
CPU DMA src:00290078 dst:25F00874 val:00000000
CPU DMA src:0029007C dst:25F00878 val:00000000
CPU DMA src:00290080 dst:25F0087C val:00000000
CPU DMA src:00290084 dst:25F00880 val:00000000
CPU DMA src:00290088 dst:25F00884 val:00007FFF
CPU DMA src:0029008C dst:25F00888 val:80A00000
CPU DMA src:00290090 dst:25F0088C val:00000000
CPU DMA src:00290094 dst:25F00890 val:000080A0
CPU DMA src:00290098 dst:25F00894 val:000084E1
CPU DMA src:0029009C dst:25F00898 val:00000000
CPU DMA src:002900A0 dst:25F0089C val:00000000
CPU DMA src:002900A4 dst:25F008A0 val:00000000
CPU DMA src:002900A8 dst:25F008A4 val:00000000
CPU DMA src:002900AC dst:25F008A8 val:000080C1
CPU DMA src:002900B0 dst:25F008AC val:80A07FFF
CPU DMA src:002900B4 dst:25F008B0 val:00000000
CPU DMA src:002900B8 dst:25F008B4 val:00000000
CPU DMA src:002900BC dst:25F008B8 val:00000000
CPU DMA src:002900C0 dst:25F008BC val:00007FFF
CPU DMA src:002900C4 dst:25F008C0 val:80A00000
CPU DMA src:002900C8 dst:25F008C4 val:00000000
CPU DMA src:002900CC dst:25F008C8 val:80A084E1
CPU DMA src:002900D0 dst:25F008CC val:00000000
CPU DMA src:002900D4 dst:25F008D0 val:80C180A0
CPU DMA src:002900D8 dst:25F008D4 val:84E10000
CPU DMA src:002900DC dst:25F008D8 val:000084E1
CPU DMA src:002900E0 dst:25F008DC val:80A00000
cram 00000000
ddddCPU DMA src:002900E4 dst:25F008E0 val:00000000
CPU DMA src:002900E8 dst:25F008E4 val:00000000
CPU DMA src:002900EC dst:25F008E8 val:84E18522
CPU DMA src:002900F0 dst:25F008EC val:00000000
CPU DMA src:002900F4 dst:25F008F0 val:00000000
CPU DMA src:002900F8 dst:25F008F4 val:8DA484E1
CPU DMA src:002900FC dst:25F008F8 val:7FFF0000
CPU DMA src:00290100 dst:25F008FC val:00007FFF
================= CPU DMA END =============== 
```

**Comment by devmiyax** [comment]
write addr002900E0 val: 000080A0 PC=060135F2

```
0x060135FA: mov.w r1, @(r0, r5)
0x060135F8: bf/s 0x060135F4
0x060135F6: dt r6
0x060135F4: mov.w @r5+, r1
0x060135F2: add #0x02, r6
0x060135F0: add #0xFE, r0
0x060135EE: sub r0, r5
0x060135EC: shlr2 r0
0x060135EA: shlr2 r0
0x060135E8: xor r6, r0
0x060135E6: and r0, r6
0x060135E4: mov #0x1F, r6
0x060135E2: extu.w r0, r0
0x060135E0: bt/s 0x06013602
0x0601352A: tst r0, r0
0x06013528: bf/s 0x060135E0
0x06013526: tst r3, r3
0x06013524: mov.w @r4+, r0
0x06013522: bf/s 0x0601351C
0x06013520: shal r3
0x0601351E: add #0x02, r5
0x0601351C: mov.w r0, @r5
0x06013524: mov.w @r4+, r0
0x06013522: bf/s 0x0601351C
0x06013520: shal r3
0x06013600: add r0, r5
0x060135FE: bra 0x06013520
0x060135FC: add #0x02, r0
```

**Comment by devmiyax** [comment]
================= CPU DMA0 END =============== 
write addr060A0048 val: 80A000C2 PC=0601C7F4
write addr0029008C val: 000080A0 PC=0601351C
write addr00290096 val: 000080A0 PC=060135F2
write addr002900E0 val: 000080A0 PC=060135F2

**Comment by devmiyax** [comment]
Add CD command

CPU DMA src:002A0100 dst:25E0FFFC val:6F6F6F6F
================= CPU DMA0 END =============== 
cs2	: Command: calculateActualSize 0b94 5200 0000 0400 0001
Cs2Area->calcsize = 1024
cs2	: Command: getActualSize
cs2	: ret: 0bd5 0100 0400 0000 0000
cs2	: Command: getSectorData 0b54 6100 0000 0400 0001
cs2	: ret: 0bd7 0180 4101 0100 cfa2
cs2	: Command: endDataTransfer 0bd4 0600 0000 0000 0000
cs2	: ret: 0bd5 0100 0400 0000 0000
cs2	: Command: deleteSectorData 0b54 6200 0000 0400 0001
cs2	: ret: 0bd5 0180 4101 0100 cfa2
cs2	: Command: getBufferSize
cs2	: ret: 0bd5 0100 0078 1800 00c8
cs2	: Command: calculateActualSize 0b94 5200 0000 0400 0002
Cs2Area->calcsize = 2048
cs2	: Command: getActualSize
cs2	: ret: 0bd5 0100 0800 0000 0000
cs2	: Command: getSectorData 0b54 6100 0000 0400 0002
cs2	: ret: 0bd7 0180 4101 0100 cfa2
write addr060A0048 val: 80A000C2 PC=0601C7F4
cs2	: Command: endDataTransfer 0bd4 0600 0000 0000 0000
cs2	: ret: 0bd5 0100 0800 0000 0000
cs2	: Command: deleteSectorData 0b54 6200 0000 0400 0002
cs2	: ret: 0bd5 0180 4101 0100 cfa2
cs2	: Command: getBufferSize
cs2	: ret: 0bd5 0100 007a 1800 00c8
write addr0029008C val: 000080A0 PC=0601351C
write addr00290096 val: 000080A0 PC=060135F2
write addr002900E0 val: 000080A0 PC=060135F2

**Comment by devmiyax** [comment]
!? write addr060A0048 val: 80A000C2 PC=0601C7F4

**Comment by devmiyax** [comment]
PC:0x061351a

**Comment by devmiyax** [comment]
finally!
![Screenshot from 2020-04-25 08-59-59](https://user-images.githubusercontent.com/1174152/80265669-401bb300-86d3-11ea-8ce8-facc3d932dc9.png)
