### ISSUE TITLE
Retro Arena Odroid N2 source will not build

### ISSUE THREAD

**Issue by SenseiRAM** [devmiyax/yabause#697]
I've been trying to update the Odroid N2 build of Yaba Sanshiro for Retro Arena, and it fails. I tried via the built-in Retro Arena package updater, and I've also tried it manually on the command line. It looks like it's trying to get something related to libpng, but the resource isn't there and returns a 404: http://storage.googleapis.com/libpng-public-archive/libpng-1.2.53.tar.gz

![IMG_3080](https://user-images.githubusercontent.com/15986116/72909700-0cf50c80-3cfd-11ea-940a-f49716881f6d.JPG)

**Comment by SenseiRAM** [comment]
So, I edited the cmake files locally on my machine and pointed them to a mirror of libpng I found (http://78.108.103.11/MIRROR/ftp/png/src/history/libpng12/). I changed the hash to match the new file, and now everything builds correctly.

**Comment by Cee123** [comment]
Doesn't work on Odroid XU4 either. Just won't compile.

**Comment by devmiyax** [comment]
fixed by
https://github.com/devmiyax/yabause/pull/722
