### ISSUE TITLE
where are this flags?? -mcpu=cortex-a15.cortex-a7 

### ISSUE THREAD

**Issue by Askmewho** [devmiyax/yabause#701]
Hi, I cant find where are this flags... and they should not bet there at all.. why I cant set my own??
it seems than you target only xu4 only for arm linux.
Ive had accomplished to compile but the emulator doesnt work, Also, this is a gles emulator, does it?
thanks on advance.

```
cc1: warning: switch -mcpu=cortex-a15.cortex-a7 conflicts with -march=armv8-a switch
```

**Comment by devmiyax** [comment]
It's just for NVIDIA Shield TV. 
I removed it https://github.com/devmiyax/yabause/blame/master/yabause/src/CMakeLists.txt#L889
