### ISSUE TITLE
House of the Dead no longer works due to glitches

### ISSUE THREAD

**Issue by Cee123** [devmiyax/yabause#703]
It was previously playable, now it is not.

![House of the Dead-200203-091846](https://user-images.githubusercontent.com/43462099/73709806-1048b900-473d-11ea-87c7-7628c2cddf19.png)

Tested on PC, Odroid XU4, Odroid N2, Standalone Yaba Sanshiro and Yaba Sanshiro on Retroarch. All do the same thing.

**Comment by devmiyax** [comment]
Fixed by:
https://github.com/devmiyax/yabause/pull/708/commits/783612bda764fb494078ba8a8fe98a90b0d67bb9

**Comment by Cee123** [comment]
This game is working now. Thank you @devmiyax . Works better than before.
