### ISSUE TITLE
Lr-yabasanshiro RPI4 color inversion 

### ISSUE THREAD

**Issue by notthesameman** [devmiyax/yabause#704]
Hello I can't figure out what is the issue? i compiled lr-yabasanshiro, all games have either color inversion, videos run correctly, I'm not sure but I think it has to do with RGBA8888.
Thank you
here's a example of mortal Kombat trilogy and Dracula X
![IMG_20200117_201929](https://user-images.githubusercontent.com/60901930/74216317-e28dd380-4c58-11ea-9ef9-ec0f21046bde.jpg)
![Screenshot_20200102-022109](https://user-images.githubusercontent.com/60901930/74216334-ef122c00-4c58-11ea-9193-750d1bd08e3d.png)

**Comment by devmiyax** [comment]
A really bad news.

Opengl library in Rasberry pi 4 has a bug. return value of texelFetch is not have enough precision.
Is there anyone who knows where I can submit this issue? 

```cpp
"  vec4 txindex = texelFetch( s_texture, ivec2(int(v_texcoord.x),int(v_texcoord.y)) ,0 );\n"
"  if(txindex.a == 0.0) { discard; }\n"
"  vec4 txcol = texelFetch( s_color,  ivec2( ( int(txindex.g*65280.0) | int(txindex.r*255.0)) ,0 )  , 0 );\n"
```

**Comment by notthesameman** [comment]
I posted in sbc channel but not sure to ask at raspberry pi foundation.

**Comment by Cee123** [comment]
There are a tonne of glitches in the Libretro version of the core. Not just for the Raspberry Pi 4 but also on PC as well. There are very clear differences in compatibility between the Libretro core and the standalone yabasanshiro.

**Comment by dankcushions** [comment]
@devmiyax, @notthesameman has made some findings on this one - please see: https://retropie.org.uk/forum/topic/24568/is-yabasanshiro-emulator-coming-on-retropie/10?_=1586806656573 and https://www.raspberrypi.org/forums/viewtopic.php?f=68&t=270359&p=1641970#p1641970

people are theorising that the texture width is too big? I'm hoping this is useful to you.

**Comment by devmiyax** [comment]
fixed
