### ISSUE TITLE
Panzer Dragoon Saga/Azel Sound Stops, then Freeze

### ISSUE THREAD

**Issue by Edojp** [devmiyax/yabause#752]
It is version on 3.1.0 7ae0de7 via Retroarch 1.8.8

This issue has been going on for some time so thought I would raise here. Game looks/sounds perfect however after approx 10 - 20 minutes the sound will stop and after that the emulation will freeze.

Can reproduce consistently, just boot game and let it run through demo/opening loop and it will happen. Let me know if there are logs etc. I can provide.

Japan version of the game. The bios is also Japan 1.0

Thank you.

**Comment by Edojp** [comment]
[retroarch__2020_06_07__14_17_53.log](https://github.com/devmiyax/yabause/files/4741431/retroarch__2020_06_07__14_17_53.log)
I enabled logging so have attached. Do not see much useful though.

**Comment by Edojp** [comment]
I tried enable force HLE bios but made no difference.

**Comment by barbudreadmon** [comment]
Use standalone, the libretro core is unmaintained & unsupported.

**Comment by Edojp** [comment]
That is unfortunate - standalone on Windows has several (different) issues.
