### ISSUE TITLE
Windows 10 issue, v3.3.0, game not loading

### ISSUE THREAD

**Issue by MelchiorGaspar** [devmiyax/yabause#754]
I have moved on.. 
I upgraded my PC to a new motherboard, CPU, RAM, and a new NVMe SSD drive.. and Windows 10

that being the case I tried out yabasanshiro.exe v3.3.0 today.. 
found it will not load a bin/cue files, I could select the but it justs loads the BIOS and does nothing.

if u need any more info or have suggestions for fixing this please let me know..

**Comment by devmiyax** [comment]
Thank you for letting me know. fixed in 3.3.1

**Comment by MelchiorGaspar** [comment]
ok thx..
