### ISSUE TITLE
SAILORMOONSUPERS                                                                                                

### ISSUE THREAD

**Issue by devmiyax** [devmiyax/yabause#76]
version:0.1.17c
device:SGH-M919
cpu_type:0
video_type:1
In practice mode
![screenshot](http://www.uoyabause.org/system/reports/screenshots/000/000/162/original/_storage_emulated_0_yabause_screenshots_T-15701G_2015_11_28_06_49_41.png?1448715056)

**Comment by devmiyax** [comment]
8-bit(256 colors)
Tile(1H x 1V)
Plane Size = 1H x 1V
Pattern Name data size = 2 words
Plane A Address = 00040000
Plane B Address = 00040000
Plane C Address = 00040000
Plane D Address = 00040000
Screen Scroll x = -480, y = -224
Window disabled whole screen
Color Ram Address Offset = 200
Priority = 7
Special Color Calculation 0

**Comment by BenjaminSiskoo** [comment]
Yabause Devmiyax 12.13.2015 (OpenGL) 

It works !
![sailormoon](https://cloud.githubusercontent.com/assets/12481242/11766818/5035f95a-a198-11e5-9096-4f9eda52e593.PNG)

**Comment by devmiyax** [comment]
It's not still fixed at "れんしゅう" mode.

![image](https://cloud.githubusercontent.com/assets/1174152/11907109/ac1365fc-a614-11e5-957b-caaf34391fb3.png)

**Comment by BenjaminSiskoo** [comment]
Ok 

I forget to read "Practice mode"  so you're totally right ^^

![sailor moon](https://cloud.githubusercontent.com/assets/12481242/11908952/86320092-a5e1-11e5-883f-ccdd4f265ea6.PNG)

**Comment by BenjaminSiskoo** [comment]
Disable VDP1 layer and nor more artefacts.

**Comment by BenjaminSiskoo** [comment]
UoYabause 0.5.2 commit 4105 : same problem

**Comment by devmiyax** [comment]
2.7.5 works fine
![image](https://user-images.githubusercontent.com/1174152/64992752-84f69480-d90f-11e9-9c46-977c1f5ee43b.png)
