### ISSUE TITLE
3.2.BETA Memory access timing stopped fully working on nvidia jetson nano retro_arena GUI build.

### ISSUE THREAD

**Issue by mrcmunir** [devmiyax/yabause#773]
Before these change will working full speed fine with these change
It has become unstable and black screen and does not show any graph.
Tested with

- Golden Axe The duel
- Radian Silvergun .
And maybe others games don't working also seems the menu don't work when press esc ¿Gui broken too? Possible stuck in the init emu!?
Seems also happen in the latest commint master branch 7c3a843

**Comment by devmiyax** [comment]
check if it is fixed by https://github.com/devmiyax/yabause/pull/776

**Comment by mrcmunir** [comment]
Fixed by #776.
