### ISSUE TITLE
ODROID N2 Retro Arena Boot No Bios Load Screen Black Screen

### ISSUE THREAD

**Issue by Lormaxx** [devmiyax/yabause#774]
Master branch - No boot bios or HLE - Followed this link to build https://github.com/devmiyax/yabause/issues/766#issuecomment-671040868

3.4a won't build https://github.com/devmiyax/yabause/pull/770#discussion_r475526133 

3.3.1 Same as master above    

3.2.4 Able to build without the linker above. No boot bios or HLE.

3.21 Able to build without the linker above. No boot bios or HLE.

3.1.2 Latest version to successfully build/boot. Bios loads fine.

**Comment by mrcmunir** [comment]
I confirmed same problem  reported on other board aarch64 (nvidia jetson nano)  in https://github.com/devmiyax/yabause/issues/773
Seems the latest works is 68edd4cb01480d63f7fa11e3edadae7fc4df773e
Black screen/hang cause by 8475a0f72606df72cc6d3c91675a00184865c9e0

**Comment by devmiyax** [comment]
check if it is fixed by https://github.com/devmiyax/yabause/pull/776

**Comment by Lormaxx** [comment]
Fixed by #776
