### ISSUE TITLE
Deep fear sound issues

### ISSUE THREAD

**Issue by LuismaSP89** [devmiyax/yabause#810]
There are sound problems in this game, maybe inherited from yabause's code.
You can see it while ingame, some annoying sounds similar to the white noise on a TV.

I think this started at november 2019 more or less. And also it's happening on yabause.

**Comment by piau9000** [comment]
It seems to be the background music. Once the three "beeps" happen, the background music starts over again as if it glitched up.

**Comment by LuismaSP89** [comment]
> It seems to be the background music. Once the three "beeps" happen, the background music starts over again as if it glitched up.

Oops, I forgot to close this. The issue was solved 3 weeks ago on the latest development builds. Sorry.
