### ISSUE TITLE
Arena glitching in Virtua Fighter Remix

### ISSUE THREAD

**Issue by Joshinx** [devmiyax/yabause#823]
While in matches, sometimes the arenas glitches, and some parts of it appear on the screen for brief seconds and frequently
![glitchvfremis](https://user-images.githubusercontent.com/88633551/145934383-06c601c5-4615-4a5f-b64a-418c3fa69f38.jpg)

**Comment by Joshinx** [comment]
Also, this makes that sometimes, if you hit your opponent, it gets launched all the way to the other side of the ring, often resulting in a ring out

**Comment by devmiyax** [comment]
fixed by 1.8.0
