### ISSUE TITLE
VATLVA                                                                                                          

### ISSUE THREAD

**Issue by devmiyax** [devmiyax/yabause#828]
version:1.5.0-PRO
device:XP
cpu_type:3
video_type:1
comment:
[state file](https://www.uoyabause.org//system/reports/state_files/000/006/984/original/T-31501G_2021_12_07_19_54_12.zip)
![screenshot](https://www.uoyabause.org//system/reports/screenshots/000/006/984/original/screenshot.png?1638874457)

**Comment by devmiyax** [comment]
playable on 1.9.0

![image](https://user-images.githubusercontent.com/1174152/174470276-2bc943d9-faef-4835-8436-34f297d0ca91.png)

**Comment by paul-met** [comment]
Doesn't reach the title screen on version 1.16.7 (win10 x64).
