### ISSUE TITLE
[3D Baseball] Menu displays problem. ..

### ISSUE THREAD

**Issue by BenjaminSiskoo** [devmiyax/yabause#83]
Left Picture : Yabause Software 
Right Picture Yabause OpenGL

Too much transparencies (Game Selection and Start = Select) ^^

![3d baseball](https://cloud.githubusercontent.com/assets/12481242/11613040/ac1da438-9c12-11e5-8f87-71c3e6209597.PNG)

**Comment by devmiyax** [comment]
![image](https://cloud.githubusercontent.com/assets/1174152/11679407/0c83d0da-9e94-11e5-9abc-3deb7258c3bf.png)

easy mistake (T.T)

**Comment by devmiyax** [comment]
![image](https://cloud.githubusercontent.com/assets/1174152/11680143/8025681e-9e99-11e5-8f51-b05b429dda92.png)

game scene is fixed too.

**Comment by BenjaminSiskoo** [comment]
Thanks, quick fix :)
