### ISSUE TITLE
Yaba Sanshiro 2 Pro Android 1.50 aspect ratio not taking effect on load

### ISSUE THREAD

**Issue by zomgugoff** [devmiyax/yabause#842]
The global setting for the aspect ratio is not being read when starting a game. Setting the aspect ratio after a game has started will take effect as normal. Quitting and re-starting the game results in switching to the default aspect ratio, but the menu still shows the last selected setting. Re-selecting the aspect ratio will make it take effect, but it will not take effect on game load.

**Comment by devmiyax** [comment]
The global setting is copied to the game setting when you start a game. If you want to change the aspect rate after you start a game, use the in-game setting menu or select the "restore default" menu item on the game card.
