### ISSUE TITLE
Sega Rally Championship No Sky (Black) in Pro Android Version

### ISSUE THREAD

**Issue by DrBuns3n** [devmiyax/yabause#845]
On Android 9 using Retroid Pocket 2+ device, free Play store version of Yaba Sanshiro 2 (1.4.4) shows the sky in Sega Rally Championship. The pro paid version (1.7.0-PRO) with the same settings does not display the sky and is black instead. 

Settings are as follows:

- Real saturn BIOS (also tested with built in BIOS, makes no difference to sky display)
- 32bit dram
- Extend internal memory on
- cpu core = dynarec
- Video core opengl
- polygon generation triangle
- rendering resolution, aspect ratio, rgb resolution all original
- use compute shader on (tried off, make no difference to sky display)
- sound engine legacy
- sound sync real time

**Comment by devmiyax** [comment]
NO issue on 1.9.0

![IMG_20220619_153208](https://user-images.githubusercontent.com/1174152/174468918-b0e12ea3-ad69-464e-9a7f-e67d2b25b0b6.jpg)



![IMG_20220619_153301](https://user-images.githubusercontent.com/1174152/174468930-546164ce-a05e-45fe-9f6c-c545adb2bce8.jpg)

![IMG_20220619_153208](https://user-images.githubusercontent.com/1174152/174468934-3986796b-c10e-4e7e-9d49-d81cfde1b8fb.jpg)

**Comment by devmiyax** [comment]
please check if "use compute shader" is off on the in-game setting.
