### ISSUE TITLE
Flickering Virtua Fighter 1, Virtua fighter remix, Daytona circuit edition odroid n2+ emuelec

### ISSUE THREAD

**Issue by Kelvfimer** [devmiyax/yabause#848]
Hello

First of all, thx for your hard work and effort to port Yabasanshiro to emuelec. 

I would like to report that there are some games such as virtua fighter 1, virtua fighter remix, Daytona USA circuit Editiion that flicker. It's interesting that yabasanshiro libretro is working fine with no flickering but the new Stand Alone version on emuelec is the one that is having this glitch

You can see an example in the following video.

https://youtu.be/gQgSoGQ_vck

The start menu doesn't appear, the selection screen flickers (the camera didn't catch that), in game life bars and time are flickering.

Please can your help on fixing this issue?
thx so much.
KR

**Comment by qbertaddict** [comment]
Here is another example. https://youtu.be/twi51tbm_m4
It seems to be rendering incorrectly. This is also on the odroid N2+

**Comment by shantigilbert** [comment]
In the meantime we found a workaround, if you compile with `-DCMAKE_BUILD_TYPE=MiniSizeRel` it seems to work just fine and with good performance, not sure if the same performance as `-DCMAKE_BUILD_TYPE=Release` but close enough at least. This I assume also confirms is an optimization flag issue.

**Comment by Kelvfimer** [comment]
Issue already solved on pi1.9.0 branch. However there are still some minor flickers in all build versions.
