### ISSUE TITLE
[3D Baseball] Transparencies and artefacts ..

### ISSUE THREAD

**Issue by BenjaminSiskoo** [devmiyax/yabause#85]
Left picture : SSF testver (last release)
Right picture : Yabause Devmiyax 12.09.2015 (OpenGL)

Transparencies problem in the main screen : 
![3dbaseball_mainscreen](https://cloud.githubusercontent.com/assets/12481242/11683378/ac8dbe80-9e6a-11e5-8fae-f9dad542ecd6.PNG)

Artefacts in game : 

![3dbaseball_ingame](https://cloud.githubusercontent.com/assets/12481242/11683377/ab5fee3e-9e6a-11e5-8ab7-e8cf7c671b3e.PNG)

**Comment by BenjaminSiskoo** [comment]
Here a video to show the problem with the logo.

https://www.youtube.com/watch?v=UEavEiKhR8M

**Comment by devmiyax** [comment]
Memo
```
NBG0 mode
8-bit(256 colors)
Bitmap(1024x256)
Bitmap Address = 0
Bitmap Palette Address = 0
Screen Scroll x = -432, y = -482
Coordinate Increments x = 0.800000, y = 0.800000
Horizontal Reduction = 1/2
Window W0 Enabled:
Horizontal start = 68
Vertical start = 28
Horizontal end = 572
Vertical end = 212
Display inside of Window
Window Overlap Logic: OR
Color Ram Address Offset = 200
Priority = 5
Special Color Calculation 0
```

**Comment by devmiyax** [comment]
![image](https://cloud.githubusercontent.com/assets/1174152/11757921/c05a1b8a-a0a8-11e5-8794-5a1d0dd8a75b.png)

**Comment by devmiyax** [comment]
![image](https://cloud.githubusercontent.com/assets/1174152/11757987/361ec064-a0a9-11e5-95db-22dec57cceb9.png)

**Comment by devmiyax** [comment]
![image](https://cloud.githubusercontent.com/assets/1174152/11758034/99cc94ce-a0a9-11e5-8f58-8594a6b7d451.png)

**Comment by devmiyax** [comment]
![image](https://cloud.githubusercontent.com/assets/1174152/11758057/ede5b482-a0a9-11e5-81fc-4f97189fa31b.png)

**Comment by BenjaminSiskoo** [comment]
All fixes, thanks for all :)
