### ISSUE TITLE
[Breakpoint Tennis] Transparencies problem, and missing lines.

### ISSUE THREAD

**Issue by BenjaminSiskoo** [devmiyax/yabause#86]
Left Picture : Yabause Devmiyax 12.09.2015 (Software)
Right Picture : Yabause Devmiyax 12.09.2015 (OpenGL)

Transparencies problem : 

![breakpoint_tennis_language screen](https://cloud.githubusercontent.com/assets/12481242/11684278/db8a4504-9e70-11e5-8be6-1a447120259e.PNG)

Thin line around head dog :+1: 

![breakpoint_tennis_smartdog](https://cloud.githubusercontent.com/assets/12481242/11684304/01d39260-9e71-11e5-8b28-56110b219677.PNG)

Missing line on the field

![breakpoint_tennis_ingame](https://cloud.githubusercontent.com/assets/12481242/11684336/457a577e-9e71-11e5-92c8-53ee6b65432a.PNG)

**Comment by BenjaminSiskoo** [comment]
Transparencies problem fixed :)

**Comment by devmiyax** [comment]
![image](https://cloud.githubusercontent.com/assets/1174152/11761734/8a421bce-a111-11e5-96a4-f98cbf495e59.png)

**Comment by devmiyax** [comment]
![image](https://cloud.githubusercontent.com/assets/1174152/11761738/b5a2c1ec-a111-11e5-9558-b09bc9c72c29.png)

**Comment by BenjaminSiskoo** [comment]
All good :) thank you
