### ISSUE TITLE
NIGHT WARRIORS                                                                                                  

### ISSUE THREAD

**Issue by devmiyax** [devmiyax/yabause#87]
version:0.1.18
device:SHIELD Android TV
cpu_type:0
video_type:1
black characters
![screenshot](http://www.uoyabause.org//system/reports/screenshots/000/000/221/original/_storage_emulated_0_yabause_screenshots_T-7009H-50VV1.001_2015_12_11_17_49_54.png?1449885118)

**Comment by devmiyax** [comment]
Normal Sprite
x = 214, y = 94
Texture address = 0007F270
Texture width = 16, height = 16
Texture read direction: Normal
Pre-clipping Enabled
Transparent Pixel Enabled
Color mode: 4 BPP(16 color bank)
Color bank: 00038700
Color Calc. mode: Replace

**Comment by devmiyax** [comment]
PC 060172ba
ADDR 06081ADC

**Comment by devmiyax** [comment]
CPU writes Color data to VDP1 frame buffer, read from there. Frame buffer stores opengl rendering result and the data CPU written is lost. the solution is that data out of rendering region returns data cpu written.
![image](https://cloud.githubusercontent.com/assets/1174152/11916866/7f96f5b4-a72e-11e5-9783-e6ca6834da38.png)

**Comment by BenjaminSiskoo** [comment]
It looks like nice...

**Comment by fivefeet8** [comment]
The game looks great.  There seems to be a slight framerate issue when playing ingame though.  The animation is not quite a smooth when you are playing.  When you are watching the demo fights between the CPU, it's a lot smoother.
