### ISSUE TITLE
Slowdowns/Frame drops in Blast Wind and Thunder Force V

### ISSUE THREAD

**Issue by NoFairPlay** [devmiyax/yabause#883]
Issue happens when trying to shoot/hit enemies, doesn't happen in any other instances. Also happens in Thunder Force V, which was notably made by Technosoft as well.

https://youtu.be/cwqQP8bxndk

Here are my specs

![image](https://user-images.githubusercontent.com/103543343/174877384-7af3dab0-5908-49ee-b998-e86e4c93a9c0.png)

**Comment by devmiyax** [comment]
Check you sound setting

![image](https://user-images.githubusercontent.com/1174152/175328407-9401508b-3494-46c2-8fe4-0581d26655b5.png)

**Comment by NoFairPlay** [comment]
> Check you sound setting
> 
> ![image](https://user-images.githubusercontent.com/1174152/175328407-9401508b-3494-46c2-8fe4-0581d26655b5.png)

Right that fixed my issue! Thanks for your response.
