### ISSUE TITLE
[Athlete Kings] Transparencies problem and shadow problem

### ISSUE THREAD

**Issue by BenjaminSiskoo** [devmiyax/yabause#89]
Left Picture : SSF Test version (last release)
Right Picture : Yabause Devmiyax 12.12.2015 (OpenGL)

Transparencies problem.

![athlete kings_menuscreen](https://cloud.githubusercontent.com/assets/12481242/11761351/d29748c4-a0bf-11e5-8adf-d096361325f6.PNG)

Shadow problem (transparencies ???)

![athlete kings_ingameshadow](https://cloud.githubusercontent.com/assets/12481242/11761354/d88f2878-a0bf-11e5-9fe3-9a6b08c119f3.PNG)

**Comment by BenjaminSiskoo** [comment]
The last fixes to Asuka (rev 2959-2960) created a regression 

![athlete kings](https://cloud.githubusercontent.com/assets/12481242/11766608/1bc9f250-a190-11e5-9d7f-a6bda39ffbab.PNG)

**Comment by devmiyax** [comment]
![image](https://cloud.githubusercontent.com/assets/1174152/12014229/134982da-ad6b-11e5-9480-cf1dcd2f227a.png)

![image](https://cloud.githubusercontent.com/assets/1174152/12014231/19f262c8-ad6b-11e5-8679-c5418d24ce91.png)

**Comment by devmiyax** [comment]
Coefficient line color enable bit (RAKLCE, RBKLCE)

**Comment by devmiyax** [comment]
![image](https://cloud.githubusercontent.com/assets/1174152/12031768/66347c1e-ae53-11e5-9969-ac62b51db252.png)

**Comment by devmiyax** [comment]
![image](https://cloud.githubusercontent.com/assets/1174152/12033564/b533b3d4-ae67-11e5-95a4-86db5e2de2e1.png)

normal shadow
line color insertion for sprite

**Comment by BenjaminSiskoo** [comment]
Shadow seems very nice...
