### ISSUE TITLE
Nvidia AndroidWorks

### ISSUE THREAD

**Issue by fivefeet8** [devmiyax/yabause#9]
Have you looked at the newly released AndroidWorks released for Android development?  Can it be useful for the development of the emulator?

https://developer.nvidia.com/AndroidWorks

Looks to have some pretty decent debugging tools.

**Comment by devmiyax** [comment]
it seems cmake support Nsight. I'll try it.

CMake 3.1 adds support for Nsight Tegra 2.0. To generate Nsight Tegra project files, set CMAKE_SYSTEM_NAME=Android in addition to selecting a Visual Studio generator.

**Comment by fivefeet8** [comment]
Looks like OpenGL ES3.2 includes many features present in Desktop GL.  Do you think some of the new extensions could help with the emulation of Sega Saturn in Yabause?

**Comment by devmiyax** [comment]
Project files generate by cmake does not work.
