### ISSUE TITLE
[Asuka 120% Limited Burning Fest] Transparencies problem and shadow problem (transparencies ?)

### ISSUE THREAD

**Issue by BenjaminSiskoo** [devmiyax/yabause#90]
Left Picture : SSF Test version (last release)
Right Picture : Yabause Devmiyax 12.12.2015 (OpenGL)

Transparencies problem

![asuka](https://cloud.githubusercontent.com/assets/12481242/11761359/1c98ddfc-a0c0-11e5-855c-c08680961358.PNG)

Shadow problem (transparencies - looks like to athlete kings and the character shadow problem)

![asuka_shadow](https://cloud.githubusercontent.com/assets/12481242/11761364/2e3e564a-a0c0-11e5-968d-82f228b42983.PNG)

**Comment by devmiyax** [comment]
fixed.
https://youtu.be/qZLURNAEL78

**Comment by BenjaminSiskoo** [comment]
Very nice :)
