### ISSUE TITLE
[Crows - The Battle Action] Shadow transparencies problem...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [devmiyax/yabause#98]
Left picture : Yabause Devmiyax 05.05.2016
Right picture : SSF 0.12 Beta R2

The shadow is not displayed properly. 

![crows_ingame](https://cloud.githubusercontent.com/assets/12481242/11761697/7f04db88-a0cc-11e5-942c-c335582a26ba.JPG)

**Comment by BenjaminSiskoo** [comment]
Left picture : Yabause Devmiyax 05.12.2016

Shadow is better but not transparent

![crows](https://cloud.githubusercontent.com/assets/12481242/15243249/be7f6700-18fa-11e6-87f5-6b999f89e2fe.JPG)

**Comment by BenjaminSiskoo** [comment]
UoYabause 0.3.0 06.12.2016 : same problem.

**Comment by FCare** [comment]
When a sprite is having a transparent alpha, it has to be blended with the other sprites. In that case, overlapping sprites are well displayed.

Hare is a patch to fix the shadows.

[0001-Different-sprites-might-be-blended-between-them-Fix-.patch.zip](https://github.com/devmiyax/yabause/files/705361/0001-Different-sprites-might-be-blended-between-them-Fix-.patch.zip)

**Comment by BenjaminSiskoo** [comment]
UoYabause 0.4.1 : shadow's missing.

![crows](https://cloud.githubusercontent.com/assets/12481242/22854145/c96666f6-f067-11e6-98e9-fe69a824d29d.JPG)

**Comment by BenjaminSiskoo** [comment]
UoYabause 0.4.6 : shadow's missing.

**Comment by FCare** [comment]
I checked on my side, on linux build, with a fresh build from 0.4.6 and I have the shadows.

**Comment by BenjaminSiskoo** [comment]
mmm, it reminds me something. Linux opengl 3 and windows OpenGL 2. You made a change about that to get it work.

**Comment by FCare** [comment]
GLFW and Android are openGL ES3, Qt is openGL 3. Maybe it comes from here...

**Comment by FCare** [comment]
Hmmm, its not so simple... I have two PC with different HD intel GPU. One is showing the issue, the other is not showing it. Both PC on ubuntu 17.04, same compiler. So it is not linked to openGL3 vs ES 3 but it is based on openGL driver. Something might not be well initialized in the OpenGL call.

**Comment by BenjaminSiskoo** [comment]
UoYabause 0..5.0 : missing shadows.

**Comment by BenjaminSiskoo** [comment]
UoYabause 0.5.2 commit 4106

**Comment by BenjaminSiskoo** [comment]
Same problem with UoYabause 0.5.5

**Comment by BenjaminSiskoo** [comment]
Fixed with Yaba Sanshiro 1.3.0 RC
