### ISSUE TITLE
[Dark Savior (U)] Freeze after pushing start button (Slave invalid opcode)...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [devmiyax/yabause#99]
Yabause Devmiyax 05.05.2016

On the main screen, after pushing start button, the game freeze. And there is an error message :+1: Slave SH2 invalid opcode

R0 =  00000000  R12 =  00000000
R1 =  00000000  R13 =  00000000
R2 =  00000001  R14 =  06000FF4
R3 =  00000000  R15 =  06000FF4
R4 =  00000000  SR =   000000F1
R5 =  00000000  GBR =  00000000
R6 =  00000000  VBR =  06000400
R7 =  00000000  MACH = 00000000
R8 =  FFFFFE11  MACL = 00000000
R9 =  00000000  PR =   00000000
R10 = 00000000  PC =   06020290
R11 = 00000000

**Comment by BenjaminSiskoo** [comment]
UoYabause 0.3.0 06.12.2016 : same problem.

**Comment by BenjaminSiskoo** [comment]
UoYabause 0.3.8 : improvements, now black screen this screen. Same invalid opcode.

![darksavior](https://cloud.githubusercontent.com/assets/12481242/20858679/084b7dce-b94b-11e6-88dc-b124cdd64fc5.JPG)

**Comment by BenjaminSiskoo** [comment]
UoYabause 0.4.1 : same problem

**Comment by BenjaminSiskoo** [comment]
UoYabause 0.4.6 : same problem

Slave SH2 invalid opcode

R0 =  00000000	R12 =  00000000
R1 =  00000000	R13 =  00000000
R2 =  00000001	R14 =  06000FF4
R3 =  00000000	R15 =  06000FF4
R4 =  00000000	SR =   000000F1
R5 =  00000000	GBR =  00000000
R6 =  00000000	VBR =  06000400
R7 =  00000000	MACH = 00000000
R8 =  FFFFFE11	MACL = 00000000
R9 =  00000000	PR =   00000000
R10 = 00000000	PC =   06020290
R11 = 00000000

**Comment by devmiyax** [comment]
'''
0x060126C8: mov.l @(0x0C0, pc), r2 ; 0x06012788
0x060126CA: mov.l @r2, r0
0x060126CC: mov #0x11, r1
0x060126CE: mulu.w r0, r1
0x060126D0: sts macl, r0
0x060126D2: add #0x0D, r0
0x060126D4: rts
0x060126D6: mov.l r0, @r2

0x0601261E: bsr 0x060126C8
0x06012620: nop

0x06012622: mov.w @r3, r0
0x06012624: tst #0x02, r0
0x06012626: bf 0x0601261E
'''

**Comment by devmiyax** [comment]
Yeah!

![image](https://user-images.githubusercontent.com/1174152/27769250-fed88c16-5f60-11e7-9fd0-a0d242766628.png)

**Comment by BenjaminSiskoo** [comment]
Great \o/ waht was the problem ?

**Comment by devmiyax** [comment]
Synchronization between VDP1 and CPU.

**Comment by BenjaminSiskoo** [comment]
ha ok :) nice catch

**Comment by BenjaminSiskoo** [comment]
Fixed UoYabause 0.5.2 :) Congrats
